### ISSUE TITLE
A standalone equivalent as catapult trace viewer

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#102]
Hi, I'm the developer of [viztracer](https://github.com/gaogaotiantian/viztracer) and I have been using catapult trace viewer as the UI for a while. I loved the way it shows trace info but I know that project is already deprecated. So, the obvious way is to move forward to perfetto.

However, there are a couple of issues that I have for using perfetto. I was hoping to get some answers from you guys :)

First of all, is there a way, or will there be a way, to open the trace as a standalone file, or to make the user feel like they are opening a standalone file? The main request here is to have the user "open a file" then there's the trace, instead of "open a link then load the trace file", which is at least three times as hard as "opening a file".

What I'm doing now with catapult, is to user their standalone html version, and customize the html file with all the trace data, then write my own javascript code to load the trace, which was not pretty, but it works. The user can open the html file and the data will be there. Can I do something that has the similar result as this?

Second, I was curious if I could somehow customize panel. One thing that I like about viztracer now is that it can show the source code when I click on the function. This is achieved by hacking the html as well. It took me a while to figure out the point where it can be hooked to the whole trace viewer, but it works.

Both features require a local HTML file to work so I could hack on it, which perfetto does not support for now. I'm totally fine for the requirement of "being online" if the js libraries need to be loaded, but is it possible for us to customize our own local version, or to achieve what I expect with some public APIs(for example, using the url parameters to do some trick)?

Thank you for reading this long issue!

**Comment by primiano** [comment]
> First of all, is there a way, or will there be a way, to open the trace as a standalone file, or to make the user feel like they are opening a standalone file? The main request here is to have the user "open a file" then there's the trace, instead of "open a link then load the trace file", which is at least three times as hard as "opening a file".

Unfortunately there isn't a Web API I am aware of to register a browser as a file handler. Workarounds for now:
1. Drag and drop the file into ui.perfetto.dev
2. Script around that, in the same way `open_trace_in_browser` does here: https://github.com/google/perfetto/blob/master/tools/record_android_trace#L218

> The user can open the html file and the data will be there

Generating a HTML file that contains the UI was a terrible thing and really doesn't work with modern HTML/JS api:
- Some JS features are only availalble on secure (https) schemes. file:// is not considered secure by modern browsers. The vulcainzed HTML thing is unmaintanable.
- Our UI requires a web worker (a dedicated thread) and WebAssembly to work. Neither of them are availlable from a single standalone HTML file.
- That causes the UI to be pinned at the version that was used to capture that trace, which makes bugfixes and new features undiscoverable.
- That requires that traces are captured via some proxy host script, which wraps them in a vulcanized thing, but that is hard to enforce in the various ways traces can be captured from the various tools (studio, gpuinspector.dev, adb shell, ...)

> Second, I was curious if I could somehow customize panel. 

Not right now but making the UI more customizable is on our radar (but will involve writing code outside, not hacking the trace file)

> Both features require a local HTML file to work so I could hack on it

Because of the above, generating HTML trace files will never happen, it's just impossible to maintain (and even make work in the first place).

**Comment by gaogaotiantian** [comment]
Okay that's understandable. 

So it seems like perfetto is able to load a trace file through http server with url parameters? That is helpful I think. I can wrap some scripts to make the user feel like they just need to open an url in Chrome, which is still much better than dragging or selecting files. BTW is there a documentation about various parameters that I can send to perfetto(for example, this ``url``) to make it work differently?

Also, I will follow on the customize panel. When you say writing code outside, do you mean customize perfetto source? That's not how I expect to work. If there's a way to write code without having to clone the perfetto project and modify, that would be interesting. I'm totally fine about writing custom code to make it work.

For now, I have extra information in the trace file(the source files of the program) to visualize it in panel, not sure if that's how it will be in the future, but I look forward to it!

Thanks.

**Comment by primiano** [comment]
> BTW is there a documentation about various parameters that I can send to perfetto(for example, this url) to make it work differently?

Not really unfortunately. I agree we should add it.

>  do you mean customize perfetto source?

Yes

> If there's a way to write code without having to clone the perfetto project and modify, that would be interesting. I'm totally fine about writing custom code to make it work.

I am not following what you are trying to do then. How do you customize a tool without checking out its code?

**Comment by gaogaotiantian** [comment]
> I am not following what you are trying to do then. How do you customize a tool without checking out its code?

Yeah I know it sounds weird. But for example, it would be a common usage for third party users like me to add our custom panel, with our own data. The output format will always be HTML eventually. Is it possible to feed the panel with only data, not the logic? For example, perfetto can load trace file from http servers and display it, maybe it can load other files, like a md file or an HTML file in an iframe to feed the panel? I'm just brainstorming here. I know there must be other concerns like safety or maintainability on your side. I'm just saying that, if we need to do our own customization on perfetto, then we have to build our own server for the tracer UI right? It would be nice if we can still use ``ui.perfetto.dev`` and be able to display some customized information in a panel.

**Comment by primiano** [comment]
Would be nice if you could spec a bit more concretely your proposal, making very clear:
1. What's the problem you are trying to solve
2. How you propose to solve it / mocks / design proposals.

I find hard to brainstorm as-is as I see mainly generic and handwavy requests

>  It would be nice if we can still use ui.perfetto.dev and be able to display some customized information in a panel.

Which kind of information? cotextual (i.e. based on the selection?)? Static?

**Comment by gaogaotiantian** [comment]
You are right, I should be more specific. I'll try to explain my needs first:

I want the user to be able to click on a function entry(which is represented as a rectangle on canvas) and see customized panel, instead of the current default panel(current selection). For now, perfetto and catapult shows name, category, duration, etc. It would be nice if that panel is customizable.

It is definitely doable if I change the source code and run my own customized perfetto server, but it would be nice if I did not have to do that.

One way that I can think of to solve this issue is adding an optional template in trace file. Of course since I'm only using chrome trace format json file, that's what I'm thinking about. I know there's already metadata in chrome trace format, like process name and thread name. If we can add an optional html template in the trace file, then maybe perfetto can render based on the template, instead of the default panel?

Using pure HTML template will give the third party a maximum freedom to customize their own panel, but I'm not the safety expert so I'm not sure if there will be safety issues(XSS or something else). If that's an issue, maybe other templates could be used. 

For example, in the json file, we could have 
```
{
  ...
  "templates" : {
    "FEE": "'name': {name}\n 'code': {code}"  
  }
}
```
For each entry with the category "FEE", we extract ``name`` and ``code`` from the entry and fill the template. 

This will likely increase the trace file size, but we could use reference as stack frame is using now. 

In this way, anyone can customize their own panel without having to edit the source code of perfetto, and perfetto can keep all the default behaviors as it is for users that do not require this feature.

I would be also interested in know if it would be considered as a security vulnerability if the user can load customized javascript code with trace file. That would give a even more flexibility for developers.

**Comment by primiano** [comment]
This could be done, but only if limited to text-only. HTML templates is never going to fly on ui.perfetto.dev because this would effectively be an official way to do XSS attacks :). Taking data from untrusted input (a trace) and rendering as html is too problematic security-wise.

Note that there is already support for annotating traces (https://perfetto.dev/docs/analysis/trace-processor#annotations) but again they require to edit the source code.

**Comment by gaogaotiantian** [comment]
Okay I can understand the HTML part. What about md? That is like a place between pure text and html, and is safer I think? I would imagine that a common usage was to display the source code. The reason I asked for HTML or even JS was that I wanted to show the full source of a file, but scrolling to the point of this specific function. This is a more specific request, but maybe not out of the way for a generic implementation?

Anyway, it would be nice to have something like this as a data-driven feature. However, I would definitely look into changing source code and build my own custom perfetto server for my usage as well.

Thanks for the explanation!

**Comment by binDongKim** [comment]
@gaogaotiantian @primiano 
If I understood it right, do we have to download the whole perfetto ui source and embed in my html to show the perfetto UI in my page? I mean, I wish there was something like this with perfetto:

```javascript
// js
import {Perfetto} from 'perfetto';
---
const traceView = new Perfetto({data: myTraceData, options: someOptions});

traveView.init({bind: someElement(in my html)})
```

Can I achieve something like above rather than having all the perfetto source code and include them in my project code base?

**Comment by primiano** [comment]
@binDongKim this request is unfeasible.

There are too many reasons why what you ask is too hard to do:
1. The UI makes uses workers, workers imply a strict deployment model (to do `new Worker('file.js')`) where some code is built and bundled in a different piece of JS with a different global scope (worker vs window). That has implications all the way down to the build system
2. The use of WebAssembly which has other implications on the build system
3. Most of the dom elements assumes the UI is full screen, the CSS scope is global and so on. and embedding in a component would require a non-trivial rewrite + would be doomed to be constantly broken because nobody would test that workflow.
4. The presence of a security policy that would be violated by your surrounding app

In general it is NOT a goal of the project to provide an embeddable component that you can drop in a DIV. there is too much complexity and, while doing that is not strictly impossible, has a very high cost and, from my view, an extremely little benefit.

The only suported way to "embed" in some form perfetto is deep linking, as described in 
https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui

**Comment by binDongKim** [comment]
First, thanks for your detailed answer.

In my thought, I don't see much difference between passing the trace data to perfetto and have them create the UI in an embeddable component structure and the deep-linking way you mentioned in a "getting data and build UI" way no matter what you use for that UI(worker, assembly etc). The only difference is that with the deep-linking way, I need to OPEN the perfetto UI page specifically and pass the data through message. The possible design I think of is some sort of a initialize function which I could invoke which is like the `main` function executed when the page is open and some properties I could pass. 

Anyway, I took a look at the deep-linking and it seems just opening a new tab derived from one's page. I thought it was more like a iframe-ish thing at least if it was a embedding. Did I get it right?

**Comment by primiano** [comment]
It's not an iframe, it's a window.open. iframes are subjected to further restrictions and are generally too dangeous cross-origin from  a security perspective:  you could overlay invisible layers on top of that and trick users into believing they are interacting with ui.perfetto.dev while instead they are interacting with something malicious.

**Comment by binDongKim** [comment]
I know it's a window.open and I'm not suggesting it should work as an iframe. What I was trying to say is it should've been like an iframe if someone calls it "embedding".
