### ISSUE TITLE
TraceProcessor doesn't immediately process TrackDescriptors

### ISSUE THREAD

**Issue by rickvanprim** [google/perfetto#103]
When TraceProcess ingests packets with TrackDescriptors, it doesn't seem to immediately create the entries in `counter_track`.  I observe that if I ingest the packets and then immediately query `counter_track`, the entries are missing, but if I continue ingesting packets until I cross the flush window period, the entries are then present.  Given that TrackDescriptors don't have an associated timestamp, it seems like they should be processed immediately instead of being buffered.

**Comment by LalitMaganti** [comment]
Was discussed in advance offline. Seems like tracks are not being ingested until parsing time whereas they should probably be available at tokenization time.

I'll look into this once other time-sensitive projects settle down.

**Comment by LalitMaganti** [comment]
Looked into this now and turns out this might actually be WAI. A TrackDescriptor in trace processor is treated as simply a "reservation": until we have events on that track, it doesn't actually exist in the tables. I think this is a fair way of approaching things as otherwise we would create fake tracks which don't have any data on them.

For that reason, making this bug as WAI.
