### ISSUE TITLE
Handling negative timestamps

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#107]
It seems like perfetto can't handle negative timestamps like catapult. Is this a design choice? Many systems use unsigned timestamps but is negative timestamp invalid? I did not see any constraints about negative timestamps in chrome trace format docs, so is this a bug?

**Comment by chromy** [comment]
We don't support negative timestamps in `trace_processor` tables (and hence in the UI) and I think this is unlikely to change.

We might be able to parse negative timestamps at import time (and convert/offset them to be positive). We have a bunch of [fancy logic](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/importers/common/clock_tracker.h;l=37) for handling events from multiple clocks already. For example if some of your events are timestamped in ns since the machine booted and other events are timestamped in ms since the unix epoch at parse time we normalize all of the events to the same clock. However I don't know that anyone has tried this with negative timestamped events and I'm not sure it's feasible to make this work with the json parser.

Does this come up in `viztracer`? I'd be interested to know where the negative timestamps stem from.

**Comment by gaogaotiantian** [comment]
Well, it came from a bug that I found in VizTracer that the timestamp overflowed to signed bit in computation on Windows. This is undefined behavior I know, and I fixed the bug in the latest release. However, I realized that this bug has been there for months and I did not catch it, because catapult handled it well(and the compiler handled the UB well). It's not a deal breaker feature, but I don't think the feature will harm anyone. Even though I can understand if this is a design choice.

However, if this is design choice, I would expect a better error message. For now I think it reports "slice out of order" error, which was not helpful at all. It should report "negative timestamp not supported" instead.

**Comment by primiano** [comment]
Emitting a TraceProcessor::stat of type=error (which then becomes a warning in the UI) sounds a good plan.
It's not a priority though, so either send a patch or this will wait for a while.

**Comment by gaogaotiantian** [comment]
It's not a priority for me either as I already fixed the bug in VizTracer. I'm ok if this does not happen for a while.

**Comment by chromy** [comment]
Hopefully fixed!
