### ISSUE TITLE
record_android_trace script only has support for 1 connected device

### ISSUE THREAD

**Issue by reabha** [google/perfetto#115]
When having multiple devices connected to a PC (so `adb devices` shows more than one device) using the record_android_trace help script will return the following:

```
Running perfetto --background --txt -o /data/misc/perfetto-traces/2021-31-29_22-31.pftrace -c -
adb: more than one device/emulato
```

This is caused because in the help script adb is not invoked using the `-s <device_id>` option. It just runs adb but if there is more than 1 device adb does not know on which device you want to run perfetto thus resulting in an error.

Fix:
Add an argument to the help script, `-s` for example that specifies the device on which Perfetto is run which is then used when calling the adb command.

**Comment by primiano** [comment]
The canonical way to deal with sort of things is setting the ANDROID_SERIAL env var.
If you want to add a -s argument to the script I'd accept a patch for that, see https://perfetto.dev/docs/contributing/getting-started.
Otherwise we won't get to this ourselves, it's too much of a niche use case and there are too many other important things to do.

Thanks for the report,
Primiano

**Comment by LalitMaganti** [comment]
Given ANDROID_SERIAL works well and is used extensively internally I think we don't need to do anything more here. Closing this.
