### ISSUE TITLE
Question about ``trusted_packet_sequence_id``

### ISSUE THREAD

**Issue by gaogaotiantian** [google/perfetto#124]
Hi,

I've been doing some experiments on generating my own data with protobuf and visualize it with perfetto. After some struggle, I realized ``trusted_packet_sequence_id`` is a very important attribute. Without it, it seems like the track_event won't be rendered correctly. However, since I'm not using perfetto SDK to generate trace data, the concept of ``trusted_packet_sequence_id`` is vague to me. I looked through the docs for it but it did not explain it well.

Could you help me about the basic concept of ``trusted_packet_sequence_id``? Should I simply add this attribute to every single ``TracePacket`` message I generate and set to a fixed value, or there's some better way to do it? My data is continuous and from a single source.

Thanks

**Comment by primiano** [comment]
trusted_packet_sequence_id is a field appeneded by traced which uniquely identifies each "writer sequence".
A writer sequence is, in most cases, a thread.
Essentially all packets from the same sequence_id are expected to be handled in FIFO order by tools processing pipelines (e.g. trace_processor). Packets from other sequences can be arbitrarily omitted.

The sequence id is particularly important when using features like `// Trace packet sequence defaults`, where TrackEvent emit some data that is valid for all future packets on the same sequence.

Imagine it like 1 sequence = 1 stream of packets from a thread.

>  Should I simply add this attribute to every single TracePacket message I generate and set to a fixed value, or there's some better way to do it? My data is continuous and from a single source.

In that case just set it to 1. Or 42. It doesn't really matter as long as it's not 0 and is the same for the same writer.

Also remember to set `SEQ_INCREMENTAL_STATE_CLEARED` on the first packet for each sequence, otherwise TraceProcessor will drop packets until seeing that because can't tell if some previous sequence-default packet has been lost so can't tell how to interpret the packets.

**Comment by gaogaotiantian** [comment]
Thanks, this explains a lot!
