### ISSUE TITLE
Perfetto UI - load data on server side

### ISSUE THREAD

**Issue by ys2843** [google/perfetto#138]
Hi Perfetto team,

I am new to Perfetto but really enjoyed it. I wondered if it is possible to load (large) data on server side? e.g. I have large data on the cloud which I don't want to pull to my local disk, can I host the Perfetto server also on the cloud and move the data loading process there, so I can visit the url and see the visualization directly?

Thanks

**Comment by primiano** [comment]
Are you talking about:

A) a very large number of manageable files?
B) files being individually large?

In general you can push the data into the UI without touching the disk, but that still requires downloading (in the browser memory) the file and pushing it into the UI (see https://github.com/google/perfetto/issues/14#issuecomment-602802994).
That's because the UI has really no server side component. This would work for A but not B, because still involves a download. The problem, beyond the download, is that a renderer process (i.e. a tab) in Chrome  is limited to 2GB/4GB of memory, you can't use more than that.

If B, you can try to hack around with the external accelerator mode. It's designed so that the UI does only the rendering part, and all the trace loading and query execution is done outside. This has been really designed to be used in localhost to get past the aforementioned 2GB/4GB limit. The way it works is:

```curl -LO https://get.perfetto.dev/trace_processor
chmod +x ./trace_processor

# Start the interactive shell
./trace_processor --httpd trace.perfetto-trace
``` 
note the --httpd. In that mode trace_processor will parse the trace and expose a query interface over the port 9001.
ui.perfetto.dev automatically tries to connect to 127.0.0.1:9001 on startup. 
What you could do is:

- Run the trace_processor on another machine (your server)
- Have something establishing a TCP proxy from 127.0.0.1:9001 -> your_server_ip:9001  (e.g. a ssh tunnel)
- Profit

Caveats:
- you'll need one server per trace.
- You cannot have more than one tab using the native accelerator mode on port 9001.

Maybe you can build something around this?

**Comment by ys2843** [comment]
Beautiful! will definitely try this work around.

**Comment by ys2843** [comment]
btw, I am having trouble building/running Perfetto on the cloud instance, although it works on my local desktop. Here is the error, 

```
/tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8)
```

**Comment by primiano** [comment]
This is https://github.com/google/perfetto/issues/117.
You need to rebuild it on some machine that has a lower glibc (possibly on the instance itself)
See https://perfetto.dev/docs/contributing/build-instructions

Sry about that, at some point we'll fix that.

**Comment by ys2843** [comment]
Thanks for the info. But I followed the instruction to build Perfetto from source or run standalone trace_processor (https://perfetto.dev/docs/quickstart/trace-analysis) on the cloud instance, both have the same issue. Hopefully this can be fixed soon.

```
/tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8)
/tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/trace_processor_shell-linux-a3ce2cbf4cbe4f86cc10b02957db727cecfafae8)
```

**Comment by LalitMaganti** [comment]
From that error message it seems like you are running the trace_processor script *not* building from source. You need to run the binary generated in the `out` folder after building from source - that should work correctly.

**Comment by ys2843** [comment]
@LalitMaganti thanks for taking a look. Do you mind kindly pointing out the section about building `trace_processor` on this page https://perfetto.dev/docs/contributing/build-instructions? Not sure which step/config I have missed.
Btw, is there an ETA that this could be fixed? We are interested in recommending Perfetto to our customers, but need to ensure it is stable to run on our cloud instance.

**Comment by LalitMaganti** [comment]
After following all the instructions up to the "Building" section (https://perfetto.dev/docs/contributing/build-instructions#building), an artifact will be generated at `out/android/trace_processor_shell`. You should be able to run this binary instead of the `trace_processor` script.

I cannot provide any hard ETA on this issue I'm afraid. Fixing it involves a lot of moving parts internally and I'll surely be wrong about any guess I give you :)

**Comment by ys2843** [comment]
Still seeing this issue when build...

```
bash-4.2$ tools/ninja -C out/android
ninja: Entering directory `out/android'
[455/2843] compile ../../buildtools/libcxx/src/algorithm.cpp
FAILED: gcc_like_host/obj/buildtools/libcxx/src/libc++.algorithm.o 
../../buildtools/linux64/clang/bin/clang++ -MMD -MF gcc_like_host/obj/buildtools/libcxx/src/libc++.algorithm.o.d -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_DEBUG=0 -DLIBCXX_BUILDING_LIBCXXABI -D_LIBCXXABI_NO_EXCEPTIONS -D_LIBCPP_OVERRIDABLE_FUNC_VIS=__attribute__\(\(__visibility__\(\"default\"\)\)\)  -O0 -funwind-tables -fstrict-aliasing -Wformat -g -fPIC -fstack-protector-strong -Werror -fcolor-diagnostics -fdiagnostics-show-template-tree -Wno-c99-designator -fstrict-aliasing -std=c++11 -nostdinc++ -isystem../../buildtools/libcxx/include -isystem../../buildtools/libcxxabi/include      -c ../../buildtools/libcxx/src/algorithm.cpp -o gcc_like_host/obj/buildtools/libcxx/src/libc++.algorithm.o
../../buildtools/linux64/clang/bin/clang++: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/sagemaker-user/perfetto/buildtools/linux64/clang/bin/../lib/libstdc++.so.6)
[457/2843] link ./cpu_utilization
ninja: build stopped: subcommand failed.
```

**Comment by primiano** [comment]
the problem here is that the hermetic compiler perfetto is pulling also depends on GLIBC_2.18.

Set `is_hermetic_clang = false` in the GN args

**Comment by ys2843** [comment]
Make sense, but I ran into more issues with customized configs, which I am afraid might be difficult for our customers to solve. I will try to find other workaround and keep an eye on this issue. Thanks for all your help.

**Comment by ys2843** [comment]
Revisited this issue, I successfully built `trace_processor_shell` on linux with lower GLIBC version via 
```
tools/ninja -C out/android \
    trace_processor_shell
```
It can be run on old Linux OS, But the artifact size is 200MB, however I see the one pulled by the python script is only 9.8MB.

**Comment by LalitMaganti** [comment]
You need to use the trace_prcessor_shell in the stripped folder i.e. in `out/android/stripped` rather than in `out/android`

**Comment by ys2843** [comment]
Thanks, the stripped version is much smaller. Everything works on the same instance where the artifact is built.
But when I download the `trace_processor_shell` to another machine, it doesn't work. On mac, it shows `zsh: exec format error: ./trace_processor_shell`. When I tried to run it on another Linux instance which shares exactly same environment, it shows `segmentation fault`. 
Any thoughts?

**Comment by LalitMaganti** [comment]
Uhhh a Linux binary is obviously not going to work on a Mac given that it's not the same OS :D You'd need to build the binary on Mac or use our prebuilts which I think should work on all (recentish) Macs.

As for why it doesn't work on another Linux machine: the only reason I can think of the top of my head is if you're using some compiler flags like -march=native or similar. If not, the best advice I could give would be to use `gdb` to step through the unstripped binary and find the line of code which is failing and see if that gives any clues.
