### ISSUE TITLE
Is there any plan to promote java heap profiler ?

### ISSUE THREAD

**Issue by yun-ling** [google/perfetto#149]
Perfetto injects code into ART source code and dump java heap from GC roots,which is the same with MAT.Originally Android official heap profiler should be better than MAT，but the fact is  the final heapdump shown  in perfetto UI is too shallow to analyse. Is there any plan to promote java heap profiler ?

**Comment by primiano** [comment]
>. Is there any plan to promote java heap profiler ?

I am not sure what you mean with "promote". I am not aware of further plans to change the android heap profiler.

What's really missing is a converter tool from perfetto to MAT that allows reusing existing tooling. THat's on the roadmap but nobody got to that yet.
What you see in the UI it's a simplification of the data in the trace.

The real problem with the (non-perfetto) heap dumps is that (1) those dump contain the full heap and as such can be enormous; (2) perfetto's heap dump happen in a forked process and don't block the profiled process for seconds (conversely to what am dumpheap used to do). The main difference is that perfetto's heap dump doesn't store the heap contents (e.g. the string payload or the bitmap contents) but only the size. The heap dump can be still big because it's O(number of managed objects) but it's not O(managed object size).

If anybody is willing to contribute, a heapdump trace -> MAT converter wouldn't be too hard and would be a welcome and useful addition to `traceconv`.

**Comment by yun-ling** [comment]
What's the key value of a heap profiler ? Detecting memory leak ,analysing memory usage to optimize our program,I think those are the  key value .Perfetto  native profiler use malloc hooks to precisely capture native memory allocation stack .According to those tree-view we can directly find out which function is using the most memory.

However,unlike native memory, Java heap allocation is more like a directed graph due to garbage collection.It's hard to find out  which object is really using the most memory.For reaching that goal, MAT provides  a   lot of useful tools to analyse this graph like dominator tree,top consumer view ,histogram,etc. I hope Perfetto will go beyond MAT and  help developer to know Java heap better.

**Comment by LalitMaganti** [comment]
Closing because I don't think there's anything actionable here. There's no plans to do anything significant with the Java heap profiler atm: the current state has proved actionable for us to rootcause and identify performance problems.
