### ISSUE TITLE
cant trace event

### ISSUE THREAD

**Issue by dengxbin** [google/perfetto#157]
![image](https://user-images.githubusercontent.com/9322198/127118153-7aab4200-0a97-46a1-ad3b-805ef7952d97.png)

Hi, I traced with above commands, but only get 631 bytes, The trace result is empty in perfetto UI, anything wrong?

**Comment by primiano** [comment]
Something failed somewhere. Can you attach the logcat output?
Maybe the tracing service is not running at all?

Please see https://perfetto.dev/docs/quickstart/android-tracing for instructions.

P.S. this bug is too vague: you are not saying which version of Android you are using, which device, not attaching any logs.

**Comment by primiano** [comment]
Closing because the bug is too vague and no follow up happened.
