### ISSUE TITLE
Perfetto can't load Bazel profiles

### ISSUE THREAD

**Issue by ulfjack** [google/perfetto#160]
Bazel (https://bazel.build/, another of Google's OSS projects) can generate performance profiles that supposedly follow the Chrome json file format spec. I can load such a profile into the 'legacy' UI, but the new UI just shows nothing at all. Any idea what's going wrong there?

[bazel-profile-a23bd20b-f0b9-472b-9a07-b9e5bc629b30.json.gz](https://github.com/google/perfetto/files/6935073/bazel-profile-a23bd20b-f0b9-472b-9a07-b9e5bc629b30.json.gz)

**Comment by chromy** [comment]
Hi Ulf!

This was a bug we fixed recently. The commit that fixed the issue was https://github.com/google/perfetto/commit/d6135d08af409f7cee29421d931f86884ae022ac.
However the fix hasn't reached the stable or canary versions of the UI yet.
I plan to update canary shortly so hopefully it shouldn't be too long of a wait.

Here you can see the trace loading on the autopush version of the UI:

<img width="1367" alt="Screenshot 2021-08-05 at 09 30 20" src="https://user-images.githubusercontent.com/351085/128318730-ae82ad58-4be4-47a2-ab83-3e41f97f8a04.png">

See https://perfetto.dev/docs/visualization/perfetto-ui-release-process#changing-release-channel for more on how to change release channel.

**Comment by chromy** [comment]
The fix has now reached the canary channel (v18.0.9).
