### ISSUE TITLE
Nested processes/hierarchy

### ISSUE THREAD

**Issue by akarafilis** [google/perfetto#167]
It seems right now the only mechanism for having hierarchy in a trace is through processes & the `pid` key on events, which lets you have one "level" of hierarchy/collapsible categories. Is there currently a way or will there be a way to have further and more arbitrary nesting?

**Comment by ammarwa** [comment]
Is this feature available right now?
If not, when is it expected to be available?

**Comment by LalitMaganti** [comment]
No it is not currently available. We still plan on doing this and there has been some infra work to allow this to happen but it's not there yet and there is no timeline for this ATM.

**Comment by ammarwa** [comment]
In process tracks, can we possibly remove the Process NUM and replace it with another name?
so that we can use process tracks as a one-level hierarchy at least?

**Comment by LalitMaganti** [comment]
You should already be able to specify a process name by setting the "name" field in the track descriptor (https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/trace/track_event/track_descriptor.proto;l=60?q=f:perfetto%20f:track_desc)

If you're using the SDK, this is described in the Track comment here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/include/perfetto/tracing/track.h;l=72?q=f:perfetto%20f:track.h

**Comment by LalitMaganti** [comment]
Going to fold this into https://github.com/google/perfetto/issues/321

**Comment by christoph-hart** [comment]
I'm also trying to move the hierarchy one level up so that I can collapse threads (my app is running in a single process but with a highly complex multithreading setup that I would like to collapse).

Unfortunately changing the name of the single process as suggested [here](https://github.com/google/perfetto/issues/167#issuecomment-1292453516) does not make it use multiple "root" items, but just rename the single root item, so I also need a way of generating multiple "root" items using one of the two options:

1. Fake other processes (but there is only one static integer variable for the `ProcessTrack` class)
2. Tell the UI viewer to use the thread level as root level.
