### ISSUE TITLE
Web site: Optimize load time

### ISSUE THREAD

**Issue by paulmenzel** [google/perfetto#175]
Perfetto’s Web site – despite being mostly text and images – takes more than a second t load. [Google PageSpeed Insights suggests to optimize the images.][1]

[1]: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fperfetto.dev%2F

**Comment by primiano** [comment]
Thanks for the report, it's a known issue really.
The real issue here is not images, is the fact that perfetto.dev is served from a low-tier single-region appengine instance (even though the site is fully static and has no server generated content).

No particular reason other than it was the quickest thing to setup.
At some point will evaluate Cloud NLB.

**Comment by paulmenzel** [comment]
> Thanks for the report, it's a known issue really.
> The real issue here is not images, is the fact that perfetto.dev is served from a low-tier single-region appengine instance (even though the site is fully static and has no server generated content).

Static is good. Less bits to transfer still should result in faster load times.

> No particular reason other than it was the quickest thing to setup.

I totally understand.

> At some point will evaluate Cloud NLB.

In my opinion the current state is totally fine. Maybe, the source files (or Web site directory) could be published to (on GitHub), so people can take a look? Lastly, maybe using GitHub pages would also solve the requirement (network load balancer or content delivery network).

**Comment by primiano** [comment]
> Less bits to transfer still should result in faster load times.

Yeah but those optimizations are not trivial because you need to do screen-size and density detection.
I prefer one (larger) file as it keep the site more maintainable.

At some point we need to decide if we spend our time building tracing or sites :)

> Maybe, the source files (or Web site directory) could be published to (on GitHub), so people can take a look? 

It is already, pretty much everything we do is released in the repo, including all the infra.

The site lives here: 
https://github.com/google/perfetto/tree/master/infra/perfetto.dev

You can build it yourself with that `infra/perfetto.dev/run-dev-server` script.

**Comment by LalitMaganti** [comment]
Closing because I don't think this is actionable given the current state of affairs.
