### ISSUE TITLE
PID namespace handling

### ISSUE THREAD

**Issue by mariuszwicker-garmin** [google/perfetto#179]
When running Perfetto in a containerized Linux environment the PID handling becomes rather tricky due to the different PID namespaces in play. Consider the following setup where we try to gather a timeline for the entire system using ftrace mixed with some of the processes using the SDK for instrumentation:
```
Host                traced
                    traced_probes

LXC Container A     application using SDK

LXC Container B     application using SDK
```

Directly on the host everything will be fine and PIDs seen by `traced_probes` match the root ns. Ftrace event parsing is also fine. However the SDK instances in applications A and B operate in their respective PID namespaces which means they will calculate different uuids for their `ProcessTracks` and `ThreadTracks` which in turn will cause these processes to show up twice in the recorded trace. Once with the Host PID and a second time with the respective Container PID.

I can think of several ways to solve this:

1. Make `traced_probes` aware of the namespaces a PID lives in and make it use the container PID. Downsides: Will require translation of PIDs in ftrace events and also increase the risk of collision between PIDs.
2. Add a way for `traced` to send the host PIDs to a client once it connects and receives the trace config so that it can use the host PIDs and report matching uuids accordingly. The major challenge here is that we need to keep this updated as the application spawns new threads.
3. Solve this in post processing using `trace_processor` by making it transparently merge uuids if they originate from the same process. This would require `traced` or `traced_probes` to record all the different PIDs a process or thread is known by so they can be merged later. 

Has this scenario ever been considered? Do you have a preferred way on how to approach this?

Thanks!

**Comment by primiano** [comment]
Oh hey,
yes I know namespaces are very tricky.

We have been discussed this internally in the last month, the proposed solution involves a mixture of: (1) scraping the NS fields from /proc/pid/status (as part of traced_probes), (2) using the socket peer identity to resolve to the root pid identity, (3) doing massaging at import time in trace_processor.

It's very nuanced because:
- ftrace events always emit events with the root namespace PIDs (The thread id really) 
- userspace events coming form the SDK instead will see only their own in-namespace pid
- traced_probes will see the outer one but not necessarily know the namespace.

Let me try to clean up the document and share it publicly.
If you are interested in the discussion there are 15 pages of nuances :)

**Comment by mariuszwicker-garmin** [comment]
Awesome, that should come down to what I tried to (possibly oversimplified) sketch as option 3.

I would be very interested to learn about the nuances and what the proposed solution turned out to look like. So I look forward to and appreciate you preparing the document.

**Comment by primiano** [comment]
I just asked the author to share the doc (turns out I don't have ownership and I can't move it myself), ping me if you don't see the doc linked here in 24h.

3 alone won't work, because we need to correlate ftrace data (e.g. scheduling with root PIDs) with track-event data (With non-root pids). This involves changes in traced, traced_probes and trace_processor.

**Comment by mariuszwicker-garmin** [comment]
Thank you for that - an interesting read for sure.

From looking through the document I learn there is already a WIP at https://android-review.googlesource.com/c/platform/external/perfetto/+/1711848 adding initial support for this. Considering the WIP was not touched since May - do you happen to know if there is plans and/or resources allocated to drive this to production? Would you be open to accepting contributions on this very change from my side?

**Comment by cervantesyu** [comment]
An update about this feature: we've recently landed the support of tracing processes running inside PID namespaces. To enable this:

- Use a build that contains [this fix](https://r.android.com/1936453).
- Ensure that processes running in containers are visible to both traced and traced_probes. The easiest way to do this is running traced and traced_probes are in one of the ancestor of the PID namespace tree, or just running traced and traced_probes in the root PID namespace.
- Use the canary channel of Perfetto UI (the [trace_processor change](https://r.android.com/1936453) may not hit the stable channel yet). This is unnecessary after the trace_processor change is on the stable channel.

Let us know if you see any bugs. Thanks for your patience!

**Comment by mariuszwicker-garmin** [comment]
Thanks a lot for the update. I will pull my local build and try if this is all we need for our use case.
