### ISSUE TITLE
Building seems to require a checkout and doesn't work from release.tar.gz

### ISSUE THREAD

**Issue by q-p** [google/perfetto#185]
When attempting to build (after download and unpacking from a release archive) e.g. release v20.1, I get the following error

```
> tools/ninja -C out/mac
ninja: Entering directory `out/mac'
ninja: error: '../../.git/HEAD', needed by 'gen/perfetto_version.gen.h', missing and no known rule to make it
```

**Comment by LalitMaganti** [comment]
This appears to be because we unconditionally require .git/HEAD from the [gen_perfetto_version_header.gni](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/gn/gen_perfetto_version_header.gni;l=33?q=.git%2FHEAD%20f:perfetto&sq=)

**Comment by primiano** [comment]
Ah right.

The write_version_header.py deals with the absence of .git but I forgot that the ninja rules don't.

I am a bit conflicted on what to do here.
I could remove the `inputs += [ "${perfetto_root_path}.git/HEAD" ]` in the gni file, and that would make things mostly work. 
But then if you did `git checkout other_branch && ninja`, the version would stay stale.

At the same time I don't want to force the rule to run on every build, because that breaks the principle "if I run ninja twice back to back without touching anything, the 2nd invocation should be a no-op (chromium has some checks in place for this)"

**Comment by primiano** [comment]
https://android-review.googlesource.com/c/platform/external/perfetto/+/1859117 should fix this.
