### ISSUE TITLE
GpuRenderStageEvent not showing in UI with new iid fields

### ISSUE THREAD

**Issue by djdeath** [google/perfetto#204]
Hi there,

I'm struggling to figure out how to have `GpuRenderStageEvent` events showing up in the UI after switching from legacy fields (`hw_queue_id`, `stage_id`) to the new ones (`hw_queue_iid`, `stage_iid`).

Not quite sure what I'm doing wrong. Please find attached a trace file.

Hopefully you can put me on the right track :)

[trace.perfetto.zip](https://github.com/google/perfetto/files/7656908/trace.perfetto.zip)

**Comment by LalitMaganti** [comment]
Paging @pmuetschard again :)

**Comment by pmuetschard** [comment]
This is either a data issue (i.e. the producer isn't outputting the right data) or a trace processor issue. I say this, because the `gpu_tracks` table only contains the Vulkan Events track, but none of the GPU activity tracks. Will take a closer look at the data in the trace later.

**Comment by pmuetschard** [comment]
I looked at the trace data and the way the interned handles are created appears to be OK. However, trace processor is ignoring the interned packets, because of the incremental state validation check: [`if (!state->IsIncrementalStateValid())`](https://github.com/google/perfetto/blob/master/src/trace_processor/importers/proto/proto_trace_reader.cc#L300).
In the trace, the state is invalid for the packets with the interned GPU data and so it is ignored. I do indeed see a bunch of `previous_packet_dropped: true` when using `trace_to_text`. @LalitMaganti can you please take a look at this trace and provide hints as to why the state gets invalidated?

**Comment by djdeath** [comment]
Ah thanks, that was exactly what I was missing : 
```
packet->set_sequence_flags(perfetto::protos::pbzero::TracePacket::SEQ_INCREMENTAL_STATE_CLEARED);
```
