### ISSUE TITLE
Perfetto on QNX

### ISSUE THREAD

**Issue by dionysus1016** [google/perfetto#205]
I am wondering whether perfetto works on QNX,  if the user wants trace from process only ( exclude the system trace), does perfetto can achieve it by only calling POSIX API?

Thanks,
Dion

**Comment by chromy** [comment]
Hi @dionysus1016! As far as I know nobody has tried compiling Perfetto on QNX. I imagine some non-trivial changes to the codebase would be necessary. On the other hand the code you are interested in (for in process tracing that is to a first approximation `src/traced`, `src/tracing`, `src/base`, `src/ipc`) has few dependencies and has been ported already to run on MacOS, Windows, Linux, and (via Chromium) others so I imagine it could be done. Please let us know if you try.

**Comment by dionysus1016** [comment]
Thanks chromy, I am not sure I have enough effort to try, but sure, I will keep here updated if I tried.

**Comment by Zard-C** [comment]
I am trying to do this now 😸 

> nly ( exclude the system trace), does perfetto can achieve it by only calling POSIX API

**Comment by randyqmartin** [comment]
i'm commenting on an old post, but hopefully my comment is useful to some.   it is fairly simple to convert the text-based trace output of the qnx kernel event files (kev) in to the perfetto format.
then bring it up in perfetto

there are some examples on how to do this in the qnx hypervisor section of gitlab.com/qnx

its in hypervisor section because most people merge android tracing (when android runs as a guest on qnx hypervisor) with tracing that occurs in the hypervisor host
