### ISSUE TITLE
MSVC2019: Explicit specialization; static_state_ has already been defined

### ISSUE THREAD

**Issue by miklelappo** [google/perfetto#214]
![image](https://user-images.githubusercontent.com/11200321/146551180-f277d332-49eb-4b14-b2b7-a2f5a5369029.png)
![image](https://user-images.githubusercontent.com/11200321/146551187-1536df0e-7111-4a69-95ee-4ba07871ff2d.png)
MSVC 2019, std=C++17

The problem may be solved with `/permissive` flag, but that's not a good way to go and also not documented this way.

**Comment by LalitMaganti** [comment]
I believe the problem here is that you are calling `PERFETTO_TRACK_EVENT_STATIC_STORAGE` from multiple CC files.

Please let us know if this is not the case and this is still happening with the latest SDK.

**Comment by LalitMaganti** [comment]
@betasheet for thoughts.

We've observed `PERFETTO_TRACK_EVENT_STATIC_STORAGE` to be the problem in other cases.

**Comment by betasheet** [comment]
Sounds like you're hitting the error mentioned in this comment: https://source.chromium.org/chromium/chromium/src/+/main:third_party/perfetto/include/perfetto/tracing/data_source.h;drc=f848e2608cce3eb20db8734aaf7a1bc5249f8bcf;l=615

Which links to this MSVC issue: https://developercommunity.visualstudio.com/t/explicit-specialization-of-static-data-member-inco/319447

It seems to have been at least partially fixed in recent MSVC releases, but some requests remain open here: https://developercommunity.visualstudio.com/t/compile-error-on-definition-of-an-explicit-special/908173

@skyostil Did you consider any alternative solutions to avoid this more fundamentally?
