### ISSUE TITLE
can ui.perfetto.dev support wifi-connected adb devices?

### ISSUE THREAD

**Issue by artrointel** [google/perfetto#224]
I frequently use "adb connect 123.123.123.123:1234" for device connection, but the web-site looks that it does not support the connection at least now. Can I get the wifi-connected device in future?

**Comment by primiano** [comment]
Not right now, because there is no way for a browser to directly open a TCP socket.

However, there is something in the works. 
You can get a sense by looking at r.android.com/1883832 and r.android.com/1911458

Once that work happens, I think you'll be able to use this by doing:

- adb connect ....
- Use the websocket bridge.

I am not 100% sure as I didn't test that `adb connect` still proxies localhost:5037 onto the remote endpoint. If that doesn't, the only option would be adding some remote connect option to the websocket bridge.

**Comment by LalitMaganti** [comment]
I believe the websocket bridge now exists and solves this problem so closing.

**Comment by MagicAndre1981** [comment]
> websocket bridge now exists and solves this problem so closing.

how to use the bridge? I want to profile my `Chromecast with Google TV 4K` with adb over WIFI

**Comment by chromy** [comment]
Enable RecordingV2:
![image](https://github.com/google/perfetto/assets/351085/0282b384-8bff-4d9b-b4db-93960ba9ea6e)

Navigate to the recording page:
![image](https://github.com/google/perfetto/assets/351085/8ead90d6-275b-4843-9be3-51c54f86cf71)

Follow the instructions here:
![image](https://github.com/google/perfetto/assets/351085/a0097440-2bab-415e-9814-6849b9a7e422)

**Comment by MagicAndre1981** [comment]
> Enable RecordingV2: ![image](https://user-images.githubusercontent.com/351085/249760707-0282b384-8bff-4d9b-b4db-93960ba9ea6e.png)

> Follow the instructions here: ![image](https://user-images.githubusercontent.com/351085/249760802-a0097440-2bab-415e-9814-6849b9a7e422.png)

Does this also work for me as Windows 10 user?
