### ISSUE TITLE
Broken rendering in Perfetto UI

### ISSUE THREAD

**Issue by asl** [google/perfetto#226]
Consider the following trace file:
[spades_time_trace_21_0.json.zip](https://github.com/google/perfetto/files/7845812/spades_time_trace_21_0.json.zip)

Rendering of legacy UI (correct) <img width="1421" alt="Screenshot 2022-01-11 at 13 45 09" src="https://user-images.githubusercontent.com/67392/148928541-40aac405-6d68-4804-a437-9e28c1735404.png">
 
Rendering of Perfetto: <img width="1108" alt="Screenshot 2022-01-11 at 13 46 15" src="https://user-images.githubusercontent.com/67392/148928702-48b0ee90-a292-4675-bcd8-20ac1b57aee0.png">

Note that "Extension index construction" entry has depth 3 there (overlapped with "partask::task::process") and everything is shifted afterwards.

**Comment by LalitMaganti** [comment]
The problem appears to be that you have two events (partask::broadcast and Extension index construction) which start at the same timestamp (52036207). There is a known issue in trace processor that if you are using X (complete events) and events at the same timestamp, they can be inverted. (For Googlers: this is the internal bug b/154775248)

This is a real bug but the complexity of fixing it is quite high. Also a) the protobuf format does not support X events b) since proto trace format has nanosecond precision, the chance two events in the same thread happen at the same time are extremely low. All this together means that this is not a high priority bug to fix - sorry about that.

**Comment by LalitMaganti** [comment]
Realistically, the JSON format is very much in maintenance mode so fixing this is not going to happen. Closing for this reason.
