### ISSUE TITLE
Loading trace input file as URL attribute

### ISSUE THREAD

**Issue by DoronRippel** [google/perfetto#235]
AFAIK - Perfetto can load a trace file only from the menu.
Is there a way to load it upon starting directly from the URL, something such as:
[GET https://ui.perfetto.dev/load?file_name=my_trace.json](https://ui.perfetto.dev/load?file_name=my_trace.json)
This could be great for systems that a user can test by calling an endpoint on the system, which will return a trace file that will be automatically opened for the user in Perfetto without the need to download the trace file, then opening Perfetto then manually selecting the file to load.
Another alternative - a POST endpoint on Perfetto that will accept in the body the complete trace file in some format.

**Comment by primiano** [comment]
> something such as: GET https://ui.perfetto.dev/load?file_name=my_trace.json

Unfortunately what you ask is unfeasible due to the security model of browsers. There is no way to do file-based access without browser-mediation via the "open file" dialog. If you think about that, it would be a big security issue if that was possible.

It is possible instead of specifying a url, see what https://cs.android.com/android/platform/superproject/+/master:external/perfetto/tools/open_trace_in_ui does

> Another alternative - a POST endpoint on Perfetto that will accept in the body the complete trace file in some format.

A POST is not feasible because Perfetto has - by design - no server-side component. This is so users can be guaranteed that their traces are only processed locally and are NOT sent to any google server. Local-only HTML+JS code cannot see POST. Instead something similar to what you ask is possible via window.open() + postmessage.

See https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui

**Comment by DoronRippel** [comment]
Thank you!!

**Comment by fabiospampinato** [comment]
Does Perfetto support loading a trace from a query parameter or url fragment? If not is there any interest in accepting a PR that adds support for that?

**Comment by LalitMaganti** [comment]
This is covered in our documentation: https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui#why-can-39-t-i-just-pass-a-url- and also in Primiano's comments above. 

If you have a proposal which addresses these concerns there we'd be happy to hear it but otherwise this is not going to happen.

**Comment by fabiospampinato** [comment]
Yeah what I meant is doing something like this basically:

```
https://ui.perfetto.dev/load?file_content=U29tZSBzaW1wbGUgYmFzZ...TY0LWVuY29kZWQgY29udGVudA==
```

Where the URL contains the trace itself directly, so there's nothing else to fetch, no requests to make. 

I think the only problem is that browsers have limits on URL lengths, so this wouldn't generalize to arbitrary traces, in theory, but I think it would still be pretty handy for a lot of traces.

**Comment by LalitMaganti** [comment]
I struggle to see how that would be useful for anything more than trivally small traces. Afaik browser limits on URL sizes are really quite small, are we going to be able to pass anything more than toy traces?

**Comment by fabiospampinato** [comment]
What prompted my suggestion was a series of convoluted steps I had to take to open up a trace in Perfetto via some internal tools I was using, for context that trace was measuring the work done by some server to handle a request, and that trace weighs ~700kb, but the crucial thing is that once gzipped it only weighs ~35kb, and Chrome's URL limit IIRC is 2MB, so that real trace I had to look at would have handily fit into the URL, another one 10 times bigger would have also easily fit, and if one would usually get even better compression ratios for bigger traces potentially even 100 times bigger ones might fit. So I think if that was supported it would actually come in handy for scenarios like the one I had. Without compression I think this is probably still worth having, but as you say it would be much easier to hit the limit.

**Comment by LalitMaganti** [comment]
Curious though, why not make your internal tool just support the deep linking as described in https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui? Would solve your problem once and for all and doesn't need any work from the Perfetto side either. And it would be a lot more flexible if you wanted to e.g. zoom into a particular part of the trace or run a set of commands in a plugin on startup etc. In general, we are fully invested in the postMessage approach because that's what we use extensively in Google so there is full incentive for us to develop and improve that (as we have done since it was first introduced). Our traces are far too big (10MB low side, 1GB+ on the high side) to be able to use URLs.

If you did want to send a PR for this, I think we would be fine to accept it as long as it was small, self-contained and didn't require a lot of changes throughout the UI. Please follow https://perfetto.dev/docs/contributing/getting-started#contributing if you are going to do that. I think we'd prefer it as a query parameter rather than a URL endpoint though.

**Comment by fabiospampinato** [comment]
> Our traces are far too big (10MB low side, 1GB+ on the high side) to be able to use URLs.

Is that 10MB before or after compression? If it's before it'd be interesting to see how much it weighs after compression, these traces seem fairly redundant.

Overall yeah I think setting up deep linking may be a set-and-forget kind of solution that just works 🤔 I need to look a bit deeper into it. Thanks 👍

**Comment by LalitMaganti** [comment]
> Is that 10MB before or after compression? If it's before it'd be interesting to see how much it weighs after compression, these traces seem fairly redundant.

After compression, it's ~40MB before.
