### ISSUE TITLE
could not detect android bitmap alloc

### ISSUE THREAD

**Issue by swallowzhang** [google/perfetto#252]
hi, perfetto could not detect android bitmap alloc? according to my test, perfetto not hook calloc method, but android bitmap alloc mem by calloc.  could this to be supported?

**Comment by LalitMaganti** [comment]
As you can see here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/profiling/memory/malloc_interceptor_glibc_preload.cc;l=61?q=external%2Fperfetto%2Fsrc%2Fprofiling%2Fmemory%2Fmalloc_interceptor_glibc_preload.cc
calloc is indeed hooked by heap profiler.

As is, this issue is completely unactionable. Please reopen with:
1. Repro steps
2. Snippet of the code you are profiling
3. The trace which is missing the allocations
4. Information about device, OS version, user/userdebug status, whether the app is profilable etc.

**Comment by swallowzhang** [comment]
Ok, i test again. Exactly, perfetto hooked the calloc, and perfetto detected the allocation when  using "calloc(1, size)". But bitmap alloc not be detected, because bitmap alloc mem like this "calloc(size, 1)". 
The repro steps is:
1. Create a demo alloc a large mem by calloc (calloc(40*1024*1024, 1)), when click a button
2. Run the demo and click "Record native allocations" in Profiler
3. Click the button alloc mem
4. Stop recording in Profiler
5. The 40 MB mem not appear in the result

My test environment is:
device: google pixel3a
os version: 10
as version: 4.1.3

**Comment by primiano** [comment]
I strongly doubt that the order of arguments makes any difference.
When I look at wrap_calloc in https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/profiling/memory/wrap_allocators.cc;l=42?q=calloc%20perfetto%20wrap_calloc

that does:

```
AHeapProfile_reportAllocation(
    heap_id,
    reinterpret_cast<uint64_t>(addr),
    nmemb * size);
```

Note the nmemb*size.

Likely the problem is somewhere else.
Can you please attach a source that repros the problem?

**Comment by LalitMaganti** [comment]
Actually I think the problem is that you are running a build which is missing this CL: https://android-review.googlesource.com/c/platform/external/perfetto/+/1170201/

This was a bug in the Q (10) released but was fixed in a QPR release. Can you please update to the latest QPR or use a newer version of Android?

**Comment by swallowzhang** [comment]
yes, that works on 11, thanks! 👍
