### ISSUE TITLE
Packaging Perfetto as an application in Linux

### ISSUE THREAD

**Issue by dorindabassey** [google/perfetto#255]
Hello, Perfetto is a really great tool, It would be interesting to have it enabled as an application on the Linux desktop. I am currently working on providing Perfetto as a Flatpak package. Suggestions and questions are welcomed in the comments. How to install and run applications in Linux using flatpak can be found [here](https://flatpak.org/), more information about Flatpak packaging - [here ](https://docs.flatpak.org/en/latest/introduction.html)

**Comment by primiano** [comment]
@ddiproietto is looking into debian packaging

I am not too familiar with Flatpak, but one thing I'd warn you is: containers. Many perfetto services (traced, traced_probes) need to be NOT in containers in order to see the whole PID and UID namespace.

You might get some weird traces if Flatpak runs apps in pids/uid namespaces.
