### ISSUE TITLE
Add Method Names for .NET 6.0 applications 

### ISSUE THREAD

**Issue by Alois-xx** [google/perfetto#259]
I have discussed with LalitMaganti at Discord about support for symbol resolution for .NET 6.0 applications running on Linux. 
He advised to open a design discussion. 
How could that be added to perfetto or some instructions how to make it work natively (crossgen2 with proper symbols?), without breaking anything would be great. 

At least CPU sampling like this 

```
data_sources: {
    config {
        name: "linux.perf"
        perf_event_config {
        timebase {
            frequency: 1000
        }
        callstack_sampling {
            kernel_frames: true
        }
        }
    }
}
```

should work. I am not asking for UI support in perfetto. I would prefer to correlate these and other events in WPA which can process perfertto traces already today.

**Comment by primiano** [comment]
Can you expand a bit more? What would you require to make symbol resolution for .NET 6.0  work?

The config you pasted here seems a regular config.
What are you proposing we should do in technical terms?

**Comment by Alois-xx** [comment]
@primiano: I have raised that question at MS. They will follow up here on this thread. I am jsut connecting the loose ends from a customer point of view to use the tracing infrastructure provided here.

**Comment by brianrob** [comment]
Starting with .NET 5, it is possible to resolve symbolic information using the perf_events jitdump capability - https://lwn.net/Articles/633846/.  To turn this on, the .NET app must be run with COMPlus_PerfMapEnabled=1.

If you use the `perf` command line too, then the jitdump file can be consumed by a call to `perf inject --input perf.data --jit --output perf-jit.data`.  From here on out, the `perf-jit.data` file will contain the properly resolved symbolic information.

**Comment by primiano** [comment]
Folks I want to set some realistic expectations here so that nobody gets disappointed in miscommunications or misunderstandings.

If you want something to happen here, somebody need to be commited and come up with a design proposal (and later patches). The design proposal needs to clearly spell what changes to Perfetto you intend to do, where, why you think it's best that way, alternatives etc. I am happy to help you with refine your design, but somebody needs to put work on:

- Explaining clearly what you want to achieve
- Understanding how .net internals work
- Understanding how perfetto works
- Make a prototype / proposals

What I see right now on this bug is a bunch of folks saying:
- I'd like this.
- This command here will do X.


This will not go far. Nobody in our team will have bandwidth to pick up a feature request for .NET sampling.

If you want anything to happen here, somebody must champion this, design-wise and implementation-wise.

**Comment by ivberg** [comment]
What you said @primiano is fair to mention and understandable. This is new customer ask at this point, and also is not committed from the Microsoft side either.

This was just to get a conversation started, and the issue documented.

Research needs to be done first (with your help) before we could even have an idea of the design or costs involved.

Does this work today (method/func names on callstack_sampling) w.r.t other JITed code such as Java?
If so, it would help if someone can explain how this mechanism works.

**Comment by primiano** [comment]
@rsavitski is the right person for this

The short version from my side is the union of:
- https://sourceware.org/gdb/onlinedocs/gdb/JIT-Interface.html#JIT-Interface
- https://sourceware.org/gdb/onlinedocs/gdb/MiniDebugInfo.html 

GDB came up with a way to express frames outside of dward debugging symols using a known symbol name and a sort of linked list populated by the runtime. The Android Runtime (ART) populates that and the unwinding library we use  on Android/linux (libunwindstack) knows how to process that while unwinding frames.
