### ISSUE TITLE
What are top yellow slices mean?

### ISSUE THREAD

**Issue by soolaugust** [google/perfetto#265]
I saw there are several yellow slices at top of the ui. what does thoese slice mean?

![image](https://user-images.githubusercontent.com/10558124/159875753-df197a2d-4040-46d4-83a6-7783d056bc35.png)

**Comment by LalitMaganti** [comment]
If this is a Chrome trace (which it looks like) those slices are just a summary of the tracks underneath; it's difficult to say exactly which track without a bit bigger screenshot - what you've provided is super cropped.

**Comment by chromy** [comment]
Those yellow boxes show where the search results are concentrated in the trace (kind of like how they show up in browser window in the scroll bar if you do Ctrl-F but horizontal rather than vertical).

If you watch how the yellow boxes change in this clip as I type in the search bar you can see them in action:

![SearchExample](https://user-images.githubusercontent.com/351085/159988054-0c0674f9-4f8c-4523-9bc4-66ad25991297.gif)

**Comment by soolaugust** [comment]
I see, Thanks :)
