### ISSUE TITLE
After the new version of perfetto opens the trace, the binder transaction cannot jump

### ISSUE THREAD

**Issue by Dopezh1** [google/perfetto#278]
HI all，After updating the new version of perfettoui today, binder transaction cannot be jumped. This was a very good function before. Is there any way to adjust this setting back?

**Comment by chromy** [comment]
Oops I imagine that was an unintended byproduct of some other change. @octaviantu maybe we should revert the stable roll until this is fixed?

**Comment by LalitMaganti** [comment]
I don't think this is actually broken. I intentionally removed the "Jump to slice" feature because it was a special casing but it was replaced with flows connecting the request/recieve pairs. These have the benefit of being standardised and also having keyboard shortcuts ([ to jump backward ] to jump forward).

Here's what the replacement looks like: ![image](https://user-images.githubusercontent.com/679100/163393318-68912ac6-4eef-4888-9ed7-05708c165fa6.png)

**Comment by Dopezh1** [comment]
@LalitMaganti  Hello But I think flow events are just some general content. Can the original jump function be added back while retaining flow events? Because in normal work, it is very important to quickly jump to the binder reply and see the running status of the peer thread.
