### ISSUE TITLE
[UI] Event not displayed

### ISSUE THREAD

**Issue by TApplencourt** [google/perfetto#287]
Hi,

First thanks a lot for this tool! Perfetto has been really useful in our HPC community. 

When displaying a trace generated by our tools, I found a bug where events are not displayed (they are hidden between each other).

```
{
"traceEvents":[
{"dur":1916208,"name":"sleep0","ph":"X","pid":0,"tid":0,"ts":3333468},
{"dur":1916866,"name":"sleep1","ph":"X","pid":0,"tid":0,"ts":3334086},
{"dur":1576710,"name":"sleep2","ph":"X","pid":0,"tid":0,"ts":5249691},
{"dur":1576499,"name":"sleep3","ph":"X","pid":0,"tid":0,"ts":5250957}
]}
```
Graph generated using `[v25.0-d6574](https://android.googlesource.com/platform/external/perfetto/+/d657416b1e2e47754e012fbe60816fd6f4953d91/ui)`

<img width="1030" alt="Screen Shot 2022-05-04 at 12 48 25 PM" src="https://user-images.githubusercontent.com/6524907/166748508-7548e113-4045-47b0-8301-ddd59a5ae1fc.png">

as you see `sleep2` is not displayed. 

Maybe related to  #226 ? Should we switch to not using `X` event? 
Hope this help,

**Comment by LalitMaganti** [comment]
This is because your events are not meeting the tracing spec [1]. Specifically,
```
While duration events allow you to trace the function flow, they must be nested. It is not possible to have non-nested duration events for a given thread. If you need to have durations that do not nest property you should use Async events instead.
```

(while this is under B/E events, this also applies for X events because X events are simply a B and E event put together).

As the spec says, you should use async events instead but note that we do not support ingesting these in the Perfetto UI (see https://github.com/google/perfetto/issues/60)

[1] https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview

**Comment by TApplencourt** [comment]
Thanks a lot. I missed that when reading the spec!
