### ISSUE TITLE
Selecting area highlights wrong section in Canary UI

### ISSUE THREAD

**Issue by benjaminRomano** [google/perfetto#289]
**Background**

When the page is scrolled while viewing a chrome trace, the selection highlighting is offset from the actual tracks being selected. 

For example, if I begin selecting the track where the arrow is, the selection box while dragging will appear where the red box is
<img width="811" alt="Screen Shot 2022-05-06 at 6 28 55 AM" src="https://user-images.githubusercontent.com/9221137/167141187-9e374709-ed90-4ae9-bfa8-cb42ca94c74d.png">

This can be reproduced on the latest canary by opening the example chrome trace, opening some of the panel containers to get a scroll bar, scroll slightly down and then try selecting either of the first two tracks in the first panel container.

**Workaround**
This appears to be fixed by reverting this change: https://github.com/google/perfetto/commit/64e41ec3ae7a65c5186f6901c572403bdd480b3e

**Comment by ddrone** [comment]
Thanks for the report! Looking at the bug

**Comment by ddrone** [comment]
Doesn't look like anything to do with layerX as far as I can tell: selection is performed correctly, the issue is that while you're doing the selection the box is displayed incorrectly. Rendering is done in this function, probably some assumption that was correct does not hold anymore: https://crsrc.org/c/third_party/perfetto/ui/src/frontend/panel_container.ts;l=420?q=panel_container.ts

**Comment by ddrone** [comment]
Pending fix: https://r.android.com/2089347

**Comment by benjaminRomano** [comment]
Fixed in 625c0da53fbd4efd26d5a6878a91264b4feb2d35
