### ISSUE TITLE
Undefined reference to WriteTrackDescriptor error when calling TRACE_EVENT.

### ISSUE THREAD

**Issue by Suhail-Mohamed** [google/perfetto#299]
Using branch: v23.

compiling my program outputs the error below:
```
void perfetto::internal::TrackRegistry::SerializeTrack<perfetto::Track>(perfetto::Track const&, protozero::MessageHandle<perfetto::protos::pbzero::TracePacket>): ...../third-party/perfetto/sdk/perfetto.h:13451: undefined reference to perfetto::internal::TrackRegistry::WriteTrackDescriptor(std::string const&, protozero::MessageHandle<perfetto::protos::pbzero::TracePacket>)
```

occurs when program calls the TRACE_EVENT macro. 

Project is compiled using Makefiles, which links object files to a shared library call libperfetto.so

Similiar to this:
```
g++ -I<path_to_perfetto_sdk_folder> -c main.cpp
g++ -I<path_to_perfetto_sdk_folder> -c includedHeader.cpp
g++ -L<path_to_shared_library> -o execuetable main.o includedHeader.o -lperfetto -lpthread
```

Any help is appreciated. Thanks

**Comment by LalitMaganti** [comment]
What you're doing is strongly discouraged and unsupported - see [this](https://perfetto.dev/docs/design-docs/api-and-abi#static-linking-vs-shared-library) page.

We're working on defining a C API which you will be able to do this which will be available in O(months).

**Comment by primiano** [comment]
If yuou really want to go there you need to NOT build with-fdefault-visibility=hidden

The current C++ API surface has never been designed to work across a .so boundary. Not even sure will ever work.
Also it's a C++ ABI so if you go there you need to be 100% sure to use the same c++ library, same compiler, same flags.

**Comment by Suhail-Mohamed** [comment]
Any recommendations for how to integrate in a non-cmake environment? Makefiles only.

**Comment by chromy** [comment]
Hey :)

If you are using the [amalgamated build](https://perfetto.dev/docs/instrumentation/tracing-sdk#getting-started) then everything has already been bundled into two files:
- perfetto.cc
- perfetto.h

Include these files as you normally would any other C++ files in your makefile.

In terms of flags you'll need at least `-std=c++11` or later and `-lpthread` but I doubt that is the issue here.

What does the trace event macro invocation look like? If it looks like:

```
  TRACE_EVENT("rendering", "LayerTreeHost::DoUpdateLayers");
```

you must declare the matching storage:

```
PERFETTO_DEFINE_CATEGORIES(
    perfetto::Category("rendering")
        .SetDescription("Events from the graphics subsystem"),
    perfetto::Category("network")
        .SetDescription("Network upload and download statistics"));
```

as in the example here: https://perfetto.dev/docs/instrumentation/tracing-sdk#track-events

Are you using a custom data source? If so have you ensured you have defined `PERFETTO_DEFINE_DATA_SOURCE_STATIC_MEMBERS(CustomDataSource);`?

Do debug this efficiently it would be useful to know:
- Which operating system
- Which architecture
- Which compiler (I see gcc but which version?)
- The full compile log

and, ideally, a minimal example that reproduces the issue.
