### ISSUE TITLE
Using perfetto from android app

### ISSUE THREAD

**Issue by preetdhiman06** [google/perfetto#30]
Hi,
I'm trying to integrate perfetto in an app so that I can capture system trace from the app only, just like system tracing in developer options.
Looked into the source code of Traceur and found things like persist.traced.enable. However, no success yet.
Could you please tell if it's feasible or not? If yes, please suggest the best way to do it.

**Comment by primiano** [comment]
This request seems extremely generic. 
If your question is "can I do this" in general the answer is "yes" but YMMV depending on the details.

Note that you will never be able to start/stop/capture the trace from a standard app.
Traces contains extremely sensitive contents and apps are not allowed to access the trace controlling endpoint, to prevent they can tell which other apps are running in the system.

In this sense Traceur is special. Traceur is a system app (i.e. is built as part of the system package). As such it gets assigned a dedicated selinux domain [traceur_app.te](https://cs.android.com/android/platform/superproject/+/master:system/sepolicy/private/traceur_app.te?q=f:traceur%20f:sepolicy).
That domain is allowed to control tracing because of this (still from taceur_app.te)

```
# Allow to access traced's privileged consumer socket.
unix_socket_connect(traceur_app, traced_consumer, traced)
```

Any other apps is not and will never be able to collect tracing data.

What's your use-case here? What's the problem you are trying to solve?

**Comment by preetdhiman06** [comment]
Being from an OEM development team, I can make system app. That won't be a problem. In fact, I already tried it, but it cannot find system property and gives me this:
 Access denied finding property "persist.traced.enable"
I'm trying to use the same code as Traceur but in a different system app. Looks like normal system apps don't have rights to control tracing.

**Comment by primiano** [comment]
As I explained above, that's governed by selinux. This is what makes the difference between a "normal" system app and Traceur.

**Comment by preetdhiman06** [comment]
Thanks a lot. It was really helpful. :)

**Comment by primiano** [comment]
Cool!
Beyond the technical aspect, I'd love to understand more about your use case. Always curious to hear how OEMs use perfetto, what works and what not.

Mind dropping me a mail @ primiano@google.com ? We can take it from there.
Thanks!

**Comment by tilal6991** [comment]
Seems like a solution was found offline so closing now.
