### ISSUE TITLE
Panning jumps throwing off context on Windows

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#320]
Why does panning jump left and right through our captures on WIndows Chrome?   It's like Perfetto is trying to snap to something, but it's unclear what that is.  This jarring behavior throws off the whole point of smooth panning.  

This was reproduced using Windows 10 running in Parallels in Chrome on macOS 14.2.   When I pan on macOS Chrome, Perfetto panning is smooth as butter.  From experience, dealing with inertial events in the browser is a major pain on Windows.  

This is using the trackpad on a MBP 16".  Moving small amounts pans.  If I pan slowly, the jump doesn't occur.  But a swipe or normal pan causes the jump.

**Comment by alecazam** [comment]
I tried the Perfetto samples (not quite the same file) on a Razer laptop, and the buttery panning is fine there.   So something about macOS translating mouse (and inertial mouse) events over to Windows causes this jumpy behavior.   The browser's typically convert the pan to a mousewheel operation, but then drop the "inertia" flag on the floor on Windows.

**Comment by primiano** [comment]
I think that is the issue, and frankly there isn't much wort doing here.
On a native (Dell XPS) windows laptop it works all smooth.
I think the issue is that parallels might NOT emulate a precision touch device and instead implements an absolute input device (many Hypervisors do) and sends discrete scroll events instead.
