### ISSUE TITLE
API for converting my own trace format to perfetto protobuf?

### ISSUE THREAD

**Issue by ihavnoid** [google/perfetto#322]
I understand that this may not be what perfetto was intened to be for, but I appreciate any help/comments. :)

We are trying to see how to visualize a "system simulator" - think something like gem5 (https://www.gem5.org/) but at a higher abstract level.  The simulator itself spews out its own format of trace (with its own pid/tid) and we want to visualize it on perfetto.  Currently we wrote a script that parses the trace and generates the chome trace format with some success, but things are getting quite ugly as the traces are getting bigger and bigger.

I tried to use perfetto's tracing API, writing my own C++ application which reads traces and generates traces for perfetto, until I hit this:

```
// A process track represents events that describe the state of the entire
// application (e.g., counter events). Currently a ProcessTrack can only
// represent the current process.
```

Which seems to suggest that no matter how hard try, the "supported" API won't let me create traces with more than one process, and I should go with a lower-level API... any help?

**Comment by LalitMaganti** [comment]
I would just write the protobufs directly instead of using the SDK. The [proto documentation](https://perfetto.dev/docs/reference/trace-packet-proto#TrackEvent) is pretty good at explaining how the protos work so you should be able to use that to reverse engineer.

For a while now I've been meaning to write a guide on how JSON events map to the Perfetto protobuf format - I'd advise you to try figuring out for yourself if you can (to avoid being blocked on me) but if you run into blockers, leave a comment here and I'll take a crack at writing that guide up.

**Comment by ihavnoid** [comment]
Thanks for your comment.  I started using the protobuf itself and (after a couple of hours of trial-and-error) got a minimal trace generation working. :)

**Comment by ihavnoid** [comment]
In case people are intested, I created this:

http://github.com/ihavnoid/tg4perfetto/

Just used the proto format and created a perfetto-trace-generating library which can also be used for instrumenting your own code!
