### ISSUE TITLE
trace_processor can not compiled

### ISSUE THREAD

**Issue by wjj1928** [google/perfetto#357]
When I run trace_processor from tools folder: I got below error:

./tools/trace_processor 
This executable requires a x86_64 cpu that supports SSE4.2, BMI2 and AVX2.
Rebuild with enable_perfetto_x64_cpu_opt=false.

So I try to rebuilt it but target not found:

perfetto$ tools/ninja -C out/linux trace_processor
ninja: Entering directory `out/linux'
ninja: error: unknown target 'trace_processor', did you mean 'graph_processor'

What's correct command to rebuilt trace_processor?

**Comment by LalitMaganti** [comment]
`trace_processor_shell` is the target you are looking for.

`trace_processor` is a Python wrapper where we removed `_shell` because
a) the ambiguity which `_shell` was added for does not exist for consumers of Perfetto - it's something we need in the codebase because `trace_processor` is a C++ library for GN/Ninja
b) Less characters = less typing :)

**Comment by wjj1928** [comment]
Thanks, exactly, 

So do we have official release with enable_perfetto_x64_cpu_opt=false.? the default download prebuild not work for my PC! 

I would like use official release instead of build myself.

**Comment by LalitMaganti** [comment]
Nope sorry there is no official non-optimized build. If we publish an "official" non-optimized build we will have to make sure it's tested, all the infra supports building it etc, handle publishing binaries for all the arches we support etc. We simply don't have the capacity to do this.

We understand it's not ideal but we're a small team with limited resources and this case doesn't make the cut. Sorry about that but hope the reasoning makes sense.
