### ISSUE TITLE
process trackers sorting support in perfetto sdk

### ISSUE THREAD

**Issue by horusli** [google/perfetto#376]
Hi perfetto team,

Is there any open api to allow multiple processtrack sorting in perfetto sdk, like according to accending or decenting pid or process name.
Just run several run with the same input, and it appears the display order for processtrackers is random, and the order is not changable. it would be nice to have this feature support for convenient analysis purpose.

**Comment by LalitMaganti** [comment]
The order of processes is not random - it depends on the "activity" of each process - i.e. how many and how long the slices are in each process.

The way to group tracks of interest is by starring them. We may support UI reordering in the future but we intentionally don't plan on configuring track order from the trace (legacy JSON format had this and it turned out to be a bad idea to decide UI from the trace).

**Comment by horusli** [comment]
> The order of processes is not random - it depends on the "activity" of each process - i.e. how many and how long the slices are in each process.
> 
> The way to group tracks of interest is by starring them. We may support UI reordering in the future but we intentionally don't plan on configuring track order from the trace (legacy JSON format had this and it turned out to be a bad idea to decide UI from the trace).

I was geneating the tracker with const input(same amount and timing of events and fixed order for all processes, and several run the same input generate different process tracker order, which makes to guess that the order is random behind :-).

Anyway it would still be nice to have some fixed sort order that user can interfere directly or indirectly, like by process priority or something else, it would be great that the process weight most can be show up on top.

**Comment by LalitMaganti** [comment]
Folding this into https://github.com/google/perfetto/issues/429
