### ISSUE TITLE
Process sorting is (seemingly) broken

### ISSUE THREAD

**Issue by noomorph** [google/perfetto#378]
I have a parent and a child process in my timeline, and the parent's lifespan is longer: it starts earlier and ends later.

However, the currently running Perfetto version (as of November 8th, 2022) weirdly sorts my processes, making the child process look like it is more important:

![Screen Shot 2022-11-08 at 12 41 06](https://user-images.githubusercontent.com/1962469/200544243-55289e10-3280-460b-9d56-91dcb7b5b35b.png)

As a workaround, I used `process_sort_index` metadata events to enforce the sorting order, but it seems that there's no support for those events in the source code of Perfetto.

Here's the gist of my stack trace to reproduce the issue:

https://gist.github.com/noomorph/57bb8a80ea44d1ff6fdee6695e9b7afd

I raised a little discussion in Discord, and @chromy helped to discover that the default sorting strategy relies on the number of slices in each process. Perhaps, it makes sense for some projects, but what can I do in my case?

Thanks in advance!

**Comment by chromy** [comment]
Me on Discord:
> @eseckler @altimin @noomorph Hey 🙂 @noomorph and I were talking in ui-dev about tweaking the sorting order. Specifically changing https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/controller/track_decider.ts;l=1503?q=track_decider&ss=android%2Fplatform%2Fsuperproject:external%2Fperfetto%2Fui%2Fsrc%2F to sort processes by first slice timestamp rather than by slice count. I think that would effect Chrome more than Android since on Android we are more likely to have the sched events so I wanted to know your thoughts 😄

@betasheet @altimin let me know :)

**Comment by betasheet** [comment]
Hm, I think that the chromeProcessRank rank would help ensure that the browser process remains top (although I have a feeling that's not true for system traces). I'd also be a little worried about the behavior in ring buffer traces, because slices/TrackEvent data can start at different points for different threads/processes after the ring buffer wraps, even if all of them were "alive" for the full duration of the trace, and it's rather random which thread emits/retains the first slice then.

**Comment by altimin** [comment]
Re: chromeProcessRank: I think we should switch it to use chrome_processes.sql , which should be more reliable anyway. 

For this specific problem, I don't think that relying on the trace events themselves is a good idea — I'd rather look into populating `parent_upid` column in the `process` table and using that to order the processes.

**Comment by LalitMaganti** [comment]
Folding this into https://github.com/google/perfetto/issues/429

**Comment by noomorph** [comment]
@LalitMaganti, so will the sorting issue ever be handled? 🙏

**Comment by LalitMaganti** [comment]
We're not going to address this directly but we are looking into how we can reorganise and filter the tracks in the UI.

**Comment by nya3jp-google** [comment]
Do you mean that it is an intentional behavior that Perfetto UI

**Comment by xunnanxu** [comment]
@LalitMaganti could you help clarify if we plan to support `process_sort_index` in Perfetto?
Asking because pretty sure the chrome trace tool does honor that but seems like it's ignored in perfetto.
Perfetto is much better in terms of perf so wonder if this minor feature can be supported. Thanks!

Chrome trace:
![image](https://github.com/google/perfetto/assets/1372575/cc1f410c-5531-455e-82a3-c56de80a25f2)


Perfetto:
![image](https://github.com/google/perfetto/assets/1372575/0cbaa5ff-db92-4d5a-ab24-6cf9e80f5bff)

**Comment by LalitMaganti** [comment]
> @LalitMaganti could you help clarify if we plan to support `process_sort_index` in Perfetto? 

Our stance of this has been discussed many times, most recently in https://github.com/google/perfetto/issues/555.

**Comment by LalitMaganti** [comment]
With https://github.com/google/perfetto/pull/3273 landing, we now support thread_sort_index and process_sort_index keys from JSON. Proto traces are still preferred to be written of course but for those writing JSON traces, it might be a nice quality of life improvement.
