### ISSUE TITLE
false alert when first loading trace using perfeeto under electron application

### ISSUE THREAD

**Issue by horusli** [google/perfetto#383]
Hi Perfetto Team，

I am trying to put perfetto into a applicaiton instead of webserver using Electron (https://github.com/electron/electron-quick-start) .

One issue I met every time I start the application and load trace for the first time(any subsequently loading trace will not incur this error again if the application is not closed) is as below 

![image](https://user-images.githubusercontent.com/6522657/201526263-612bdaff-6010-4d1a-b215-70934c17e7a1.png)

I don't support it to be a real bug since the trace loading activity is working in background and if the dialog is closed, the data on these tracker will eventually show up.

I also test it using wepage after start dev server using 'ui/run-dev-server  --out out/default', this also never pop up.

it looks to me to be a false alert, can this be fixed?

**Comment by chromy** [comment]
There are a handful of places we use `Cache` in the UI:
- https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/common/cache_manager.ts;l=142?q=f:perfetto%20f:%5C.ts$%20cache
- https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/service_worker/service_worker.ts;l=57?q=f:perfetto%20f:%5C.ts$%20serviceworkerhttps://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/frontend/service_worker_controller.ts;l=40?q=f:perfetto%20f:%5C.ts$%20cache&start=21

So I imagine the cause is one of those, probably the first one since the error mentions `put`.
Possibly we should not try to do any cacheing the the UI is loaded off a file:// URL?

I'm not familiar with how the Electron quick start serves the web content.
If it's via a file:// URL I would expect a lot of things to not work quite right like this.

We don't embed the UI into Electron so its going to be hard for me to test any potential fix.
You can probably change the code here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/common/cache_manager.ts;l=109?q=f:perfetto%20f:%5C.ts$%20cacheTrace to `return false;` if `document.location.origin === "file://"` to avoid this error.

Patches welcome :)
See https://perfetto.dev/docs/contributing/getting-started#quickstart for details.

**Comment by primiano** [comment]
Loading things from file:// scheme is a terrible idea. file:// is NOT considered a secure browser context (unlike http://127.0.0.1:*) and that breaks a bazilion APIs that work only in secure contexts.

I wouldn't not try to fix this. THe longtail of things to support file:// is just too long. IIRC not even workers work on file://

I'd consider changing strategy. I don't know Electron, but I am pretty sure htere must be a better way to embed content in electron and treat it as a secure context.

**Comment by horusli** [comment]
> There are a handful of places we use `Cache` in the UI:
> 
> * https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/common/cache_manager.ts;l=142?q=f:perfetto%20f:%5C.ts$%20cache
> * https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/service_worker/service_worker.ts;l=57?q=f:perfetto%20f:%5C.ts$%20serviceworker
> * https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/frontend/service_worker_controller.ts;l=40?q=f:perfetto%20f:%5C.ts$%20cache&start=21
> 
> So I imagine the cause is one of those, probably the first one since the error mentions `put`. Possibly we should not try to do any cacheing the the UI is loaded off a file:// URL?
> 
> I'm not familiar with how the Electron quick start serves the web content. If it's via a file:// URL I would expect a lot of things to not work quite right like this.
> 
> We don't embed the UI into Electron so its going to be hard for me to test any potential fix. You can probably change the code here: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/ui/src/common/cache_manager.ts;l=109?q=f:perfetto%20f:%5C.ts$%20cacheTrace to `return false;` if `document.location.origin === "file://"` to avoid this error.
> 
> Patches welcome :) See https://perfetto.dev/docs/contributing/getting-started#quickstart for details.

thanks for the reminder, just local tried with this walkaround, it fix the problem.:-)
