### ISSUE TITLE
[Feature request]vertical scroll bar for pin tracker area

### ISSUE THREAD

**Issue by horusli** [google/perfetto#384]
Hi perfetto team,

Is it possible to add vertical scroll bar support for the pinned tracker area.
There are occasions that we generate some tracker that longer enough to occupy the whole screen size, and it is impossible to pin it to top since lacking of vertical scroll bar makes it difficult to check other pinned trackers simultaneously.

**Comment by LalitMaganti** [comment]
I'm going to fold this into https://github.com/google/perfetto/issues/429 because the more general problem is increasing vertical real estate. We probably don't want a scroll-bar for starred tracks because nested scrolling is a complete pain but generally we agree that we need to preserve vertical space more.
