### ISSUE TITLE
Unable To Load Trace In Perfetto UI

### ISSUE THREAD

**Issue by brianmichel** [google/perfetto#410]
In the [Arc browser](https://arc.net) we use Chromium's tracing support to produce diagnostics that our members can send us if they have an issue with the browser. In addition to some Chromium specific categories, we add a custom category that let's us bridge tracing information from our Swift application into the tracing report. 

Internally, we use Chromium's `TRACE_EVENT_NESTABLE_ASYNC_BEGIN1` and `TRACE_EVENT_NESTABLE_ASYNC_END1` respectively to begin and end span information from the Swift application.

When loading the trace into https://ui.perfetto.dev we are typically greeted with an error that says the following:

```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: https://ui.perfetto.dev

Error: Error @ row: 39 col: 'name': SQL value is NULL but that was not expected (expected type: STR). Did you intend to use NUM_NULL or STR_NULL?
Error: Error @ row: 39 col: 'name': SQL value is NULL but that was not expected (expected type: STR). Did you intend to use NUM_NULL or STR_NULL?
    at RowIteratorImpl.tryMoveToNextBatch (https://ui.perfetto.dev/v31.0-0392f51dc/frontend_bundle.js:325412:23)
    at RowIteratorImpl.next (https://ui.perfetto.dev/v31.0-0392f51dc/frontend_bundle.js:325309:23)
    at new RowIteratorImpl (https://ui.perfetto.dev/v31.0-0392f51dc/frontend_bundle.js:325279:14)
    at new RowIteratorImplWithRowData (https://ui.perfetto.dev/v31.0-0392f51dc/frontend_bundle.js:325428:22)
    at QueryResultImpl.iter (https://ui.perfetto.dev/v31.0-0392f51dc/frontend_bundle.js:325015:22)
    at TrackDecider.<anonymous> (https://ui.perfetto.dev/v31.0-0392f51dc/frontend_bundle.js:345878:41)
    at Generator.next (<anonymous>)
    at fulfilled (https://ui.perfetto.dev/v31.0-0392f51dc/frontend_bundle.js:4524:62)

v31.0-0392f51dc 0392f51dc49c47aa5754d6e987b1b4bf4fab32d1
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
```

However loading the trace into the legacy UI (or converting it and loading it) shows all of the tracing tracks without issue (albeit in the old UI). 

I've attached a trace that triggers the error and I'm very much looking forward to debugging further but am just unsure how to proceed and would love some advice, however since the tracks load in the legacy UI and not the modern tool I wanted to file this issue as a jumping off point.

[trace_log_2022-12-20_09-50-02.json.gz](https://github.com/google/perfetto/files/10269563/trace_log_2022-12-20_09-50-02.json.gz)

**Comment by LalitMaganti** [comment]
Took a look into this. A few things which stand out:
1) Your file name is not accurate: inside the gzip container is not a JSON trace but actually a proto trace. I tried to open this with a text editor and was surprised to see binary nonsense come up.
2) The root cause of this issue is null track names for global scoped and process scoped tracks. We always expect those to have a name inside the Perfetto UI so when they are null, the UI just fails. It's questionable whether the UI should treat this as an error but given we always expect well-formed traces to have a non-null track name, it's not super unreasonable.
3) The null track names are coming from the the fact that we don't seem to be associating names correctly when `legacy_event` is specified in `track_event`. As the name implies, this stuff is legacy for a reason and was always intended as a short-term solution which would go away at this point.

I don't have cycles to look  more into this but I'll cc @betasheet @skyostil and ping some people internally about whether they can dig more into this.

**Comment by LalitMaganti** [comment]
Note also that many people are off for the holidays so it may not be anyone can look into this until after. I'd consider following up on this after the holidays if you don't hear anything here over the next few days.

**Comment by brianmichel** [comment]
Thanks so much for the info @LalitMaganti and to @primiano who I see pushed a commit trying to fix some portion of this. I assume the correct thing for us to do is to migrate off of whatever these legacy APIs are internally to something a bit more modern? @vivekg-ai any thoughts here for us?
