### ISSUE TITLE
Python query result is not correct

### ISSUE THREAD

**Issue by zhangxianbing** [google/perfetto#411]
For the same profile file，i use python api and sql query on https://ui.perfetto.dev/, got diff result.

Here is my python code:

```python
def perfetto(profile_file, slice_name):
    import pandas as pd
    from perfetto.trace_processor import TraceProcessor

    tp = TraceProcessor(trace=profile_file)

    qr_cmd = "SELECT dur,name FROM slice"
    if slice_name:
        qr_cmd += f" WHERE name == '{slice_name}'"
    qr_df = tp.query(qr_cmd).as_pandas_dataframe()
    qr_df = qr_df.sort_values(by="dur")
    print(qr_df.to_string(float_format="%.2f"))
```

Here is my web query:

```sql
select name,dur from slice where name == "slice_name" order by dur desc; 
```

and the web query result is correct.

**Comment by LalitMaganti** [comment]
The UI and the Python API are not synced in versions so it's very possible for them not to return identical results (due to parsing some new events/different events). What we really need to know is what is the problem not that there is the change.

Without: a) the trace file b) what the results are you expect to see c) what you're actually seeing, this bug is completely non-actionable. For us to look further, please reopen providing these pieces of information.
