### ISSUE TITLE
fail to setup trace_processor_shell

### ISSUE THREAD

**Issue by arthurlang** [google/perfetto#413]
% ./trace_processor trace.perfetto-trace
Downloading https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v31.0/mac-arm64/trace_processor_shell
curl: (7) Failed to connect to commondatastorage.googleapis.com port 443 after 17629 ms: Connection refused （1st time）

{ # after I figure 142.250.10.128  commondatastorage.googleapis.com  in my etc/hosts , change to another problem below:
   curl: (35) error:02FFF036:system library:func(4095):Connection reset by peer()
}
Traceback (most recent call last):
  File "/Users/langjian/systrace/./trace_processor", line 294, in <module>
    run_perfetto_prebuilt(TRACE_PROCESSOR_SHELL_MANIFEST)
  File "/Users/langjian/systrace/./trace_processor", line 286, in run_perfetto_prebuilt
    bin_path = get_perfetto_prebuilt(manifest)
  File "/Users/langjian/systrace/./trace_processor", line 279, in get_perfetto_prebuilt
    return download_or_get_cached(
  File "/Users/langjian/systrace/./trace_processor", line 243, in download_or_get_cached
    subprocess.check_call(['curl', '-f', '-L', '-#', '-o', tmp_path, url])
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', '-f', '-L', '-#', '-o', '/Users/langjian/.local/share/perfetto/prebuilts/trace_processor_shell.tmp', 'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v31.0/mac-arm64/trace_processor_shell']' returned non-zero exit status 35.

macpro
<img width="330" alt="image" src="https://user-images.githubusercontent.com/6771583/209303151-43e9bcae-9d89-4bce-bb8c-d209c89193dd.png">
My colleague and I both getthis error in m1 macpro

try solusion:
Download https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v31.0/mac-arm64/trace_processor_shell by hand,but no how what is next?
most likely curl is the problem

Happy MerryChristmas for team!
please help me skip this error , thanks a lot

**Comment by LalitMaganti** [comment]
This is a problem with your curl on your system: the error message is telling you as such. Really you need to figure out why the command:
```
curl -L -o /Users/langjian/.local/share/perfetto/prebuilts/trace_processor_shell.tmp https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v31.0/mac-arm64/trace_processor_shell
```
Is failing on your system. I would not try any workarounds for this as this is an important problem.

If you really insist on workaround instead of fixing you'll want to do the following:
1. Place the downloaded file in `/Users/langjian/.local/share/perfetto/prebuilts/trace_processor_shell`
2. Create a file at `/Users/langjian/.local/share/perfetto/prebuilts/trace_processor_shell. sha256` containing just `d500226e1d53c3e8db4f29f44df463139f8fbc81ba2364934f6a69e76d9d065d` (which you can get by looking at the SHA256 corresponding to the mac-arm64 URL at https://cs.android.com/android/platform/superproject/+/master:external/perfetto/tools/trace_processor;l=1?q=tools%2Ftrace_pro&sq=)

But really you should just figure out why curl is not working.

**Comment by arthurlang** [comment]
thanks

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/6771583/209340267-7cd0d215-f5ee-4fa1-b685-6f6a77fca23c.png">
but it is a good way to workaround

**Comment by primiano** [comment]
Unfortunately some ISPs in some countries restrict access to google cloud storage.
I've seen this problem frequently on the chromium-dev mailing list.
There is nothing we can do sorry.
Maybe consider using a VPN or some similar solution.
