### ISSUE TITLE
Couldn't show any slices in Trace Viewer when using ring buffer

### ISSUE THREAD

**Issue by apple-balm** [google/perfetto#414]
We want to profile my application using Perfetto C++ SDK.

We set the policy of central trace buffer as ring buffer.
We traced many slices for a long time and save them into a file.
And then, we uploaded the file at Trace Viewer website.
But we couldn't see any slices.

We converted the file to text using traceconv binary.
We couldn't find a track_descriptor packet.
Could this observation cause problems?

How can we solve this problem?

**Comment by ddiproietto** [comment]
The problem is discussed in:

https://perfetto.dev/docs/concepts/buffers#incremental-state-in-trace-packets

As explained in the link, you can solve the problem by setting TraceConfig.IncrementalStateConfig.clear_period_ms to a non-zero small value. An appropriate clear_period_ms interval depends on the expected amount of time it takes to fill your ring buffer for your trace config.

There are plans to simplify this in the future, nothing concrete yet, but stay tuned.

In the meantime, please feel free to reopen if setting clear_period_ms doesn't work for you.
