### ISSUE TITLE
Perfetto connection to trace_processor does not show up from locally built and deployed web server

### ISSUE THREAD

**Issue by rohanaggarwal7997** [google/perfetto#433]
Hi 
I generated a trace file and loaded it into trace_processor. When I go to the online perfetto UI it works fines, an automatic prompt comes up which asks me whether it wants to use the trace file from trace_processor. But when i try to do the same from locally built perfetto deployed on apache it doesn't work. If i load a file that requires lesser memory than 2GB, it works fine on locally built perfetto. When I run the larger trace file on locally built perfetto, it complains that it requires more memory and asks me to run trace_processor and perfetto will automatically recognize the trace_processor on reload but that doesn't happen.

**Comment by LalitMaganti** [comment]
Almost certainly the cause of this problem is that your custom domain is not on the CORS allowlist [here](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/rpc/httpd.cc;l=44?q=f:perfetto%20CORS). We only allow certain domains to talk to the trace processor to try to preserve security.

There are two options:
1. Build your own version of trace processor where you add your domain to this list
2. Send a patch to add a command line flag to allow adding to this allowlist. The instructions on contributing are [here](https://perfetto.dev/docs/contributing/getting-started). The place where you'd need to add the flag is [here](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/trace_processor_shell.cc;l=820)
