### ISSUE TITLE
raw trace_processor table behaves differently over HTTP and CLI 

### ISSUE THREAD

**Issue by douglas-raillard-arm** [google/perfetto#442]
After installing perfetto for Python and trace_processor today:
```
curl -LO https://get.perfetto.dev/trace_processor
pip install perfetto
```

I tried to run the following snippet:
```
import perfetto

from perfetto.trace_processor import TraceProcessor
tp = TraceProcessor(trace='trace.perfetto-trace')

query="""SELECT * FROM raw WHERE name = 'sched_switch'"""

qr_it = tp.query(query)
for row in qr_it:
  print(row.name)
```

It does not error but the iterator is empty. Executing the exact same query in the interactive CLI mode of trace_processor provides pages of result.

**Comment by LalitMaganti** [comment]
This is WAI: by default we disable raw table ingestion in the Python API because of scalability concerns. If you need this table, you need to enable `ingest_ftrace_in_raw` option in the config: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/python/perfetto/trace_processor/api.py;l=48

**Comment by douglas-raillard-arm** [comment]
Thanks, the performance is indeed not great but it works so now LISA will be able to consume Perfetto traces, which might be convenient in some situations.
