### ISSUE TITLE
Perfetto crashes/incorrectly loads buildreport.json trace file from Unity

### ISSUE THREAD

**Issue by Holo-Krzysztof** [google/perfetto#461]
There's multiple layers to this, but here's what happens when I try with Firefox (doesn't matter if Perfetto Stable or Canary).

```
Viewed on: https://ui.perfetto.dev

Error: RuntimeError: index out of bounds
perfetto::trace_processor::Rpc::OnRpcRequest(void const*, unsigned long)@https://ui.perfetto.dev/v31.0-8adbb1e97/engine_bundle.js line 1287 > WebAssembly.Module:wasm-function[5590]:0x41eca6
trace_processor_on_rpc_request@https://ui.perfetto.dev/v31.0-8adbb1e97/engine_bundle.js line 1287 > WebAssembly.Module:wasm-function[245]:0x1afcf
createExportWrapper/<@https://ui.perfetto.dev/v31.0-8adbb1e97/engine_bundle.js:1256:20
ccall@https://ui.perfetto.dev/v31.0-8adbb1e97/engine_bundle.js:870:17
onMessage@https://ui.perfetto.dev/v31.0-8adbb1e97/engine_bundle.js:6681:33


stderr: 


v31.0-8adbb1e97 8adbb1e97c506f8394acc93b881d8e116c787238
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
```

Using Edge 110.0.1587.63 I can at least open the file, but it will not show any events; it looks like this:
![not-quite-perfetto](https://user-images.githubusercontent.com/22612985/223164486-1630317e-de71-4daf-84f9-fd1db251ee2d.png)

And here's the result in `edge://tracing` (as it should look like):
![edge-tracing](https://user-images.githubusercontent.com/22612985/223164745-d107b169-1f1a-4dec-88b3-f95a9d83b156.png)

The file to reproduce is here: 
[buildreport.json](https://github.com/google/perfetto/files/10900189/buildreport.txt)

**Comment by LalitMaganti** [comment]
The trace is actually fine on edge just scrunched up in the left most part. If you zoom in fully, you will see the following:
![image](https://user-images.githubusercontent.com/679100/223180579-c97cb280-5169-46ed-8b56-1a0c7ddd99c5.png)

And also some more on the right most part:
![image](https://user-images.githubusercontent.com/679100/223181146-c3b5151b-9974-46ed-85bd-4c17f470a0d9.png)

The root cause is the following:
```
{ "pid": "Unity", "tid": 1,"ts": 1.67811817037212E+15,"dur": 7252510, "ph":"X", "name": "Build player"},
{ "pid": 0, "tid": 1, "ts": 1678118170863842, "dur": 1678413, "ph": "X", "name": "Build ScriptAssemblies", "args": {} },
```

The timestamp being emitted are not consistent so there seems to be some order of magnitude difference between the two types of timestamps. Patches to fix this are welcome but this is a very niche problem in the grand scheme of things so not something we will be able to look at ourselves (especially as JSON traces are supported on a best-effort basis).

As for Firefox, again we would not have any bandwidth to debug why things break there. We have enough trouble keeping with the nuances of WASM on Chrome without needing to support another rendering engine.
