### ISSUE TITLE
Cannot find the root_distance column in the head_graph_object table

### ISSUE THREAD

**Issue by will7856** [google/perfetto#464]
I run the command `./trace_processor -e java_heap.sqlite trace` and get a SQLite database, but I can't find the root_distance column in the head_graph_object table
<img width="586" alt="image" src="https://user-images.githubusercontent.com/33977657/226293449-f51b42a9-cc45-4763-8a0c-d5cf63f1cba3.png">

**Comment by ddiproietto** [comment]
[root_distance](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/trace_processor/tables/profiler_tables.h;l=340;drc=e2a745672fba6837e622583ca59aa4507861bf62) is a **hidden** column of the `heap_graph_object` table.

I believe it's hidden because it's an implementation detail of the algorithm that builds the flamegraph, so we might change its semantics or remove it.

The algorithm that builds the flamegraph doesn't even run by default (you have to acutally query the flamegraph table for that), so the column will not even be populated most of the times.

Also, I'm told that the `-e` mode for trace_processor is supported on a best-effort basis. I wouldn't be surprised if something else doesn't fully work.
