### ISSUE TITLE
Feature Request: Docker-Compose workflow for Linux quick start

### ISSUE THREAD

**Issue by rayanht** [google/perfetto#47]
Would be nice to have a docker-compose configuration instead of manually building from source and running the services via tmux

**Comment by primiano** [comment]
Hmm it's a bit tricky because tracing neeeds to acces to so many resources that the only way would be running it as --privileged . But at that point there is 0 difference between that and just downloading a binary and running it on the host.
The thing that is really missing IMHO is a self-contained binary, so one could just run ./perfetto --args... instead of starting the services manually.

**Comment by rayanht** [comment]
Would it necessarily need to be a binary? It might be easier to have a python script that simply spawns subprocesses and distributes the CLI arguments to the relevant process

**Comment by primiano** [comment]
Well 100% we need the binary for the perfetto code itself. At that point we need to decide on whether this takes a python script + a binary, or just the "perfetto" binary doess it all. I was thinking the latter.
Essentially, on Linux, I am thinking of a mode where the "perfetto" (which typically is only the cmdline client, but not the service) works a bit like busybox: the binary contains everything (code for both service, probes and client) and it does fork()+exec(/proc/self/exec) to spawn the various subprocesses. 
What would be the advantage of a python binary doing this?
A binary has the nice advantage that, once everything (% libc, libc++) is statically linked, you can just download it and run it.

**Comment by rayanht** [comment]
That makes sense. I can't really think of anything that a python script could do that a self-contained binary couldn't. It was more of a question rather than an opinionated statement tbh

**Comment by primiano** [comment]
okie, no prob. Just checking if I missed something else :)

**Comment by LalitMaganti** [comment]
I think we can close this issue because https://github.com/google/perfetto/commit/6aa736ae0a0d394ceeb5614b1e673f9ded18e6d3 introduced the monolithic binary called `tracebox` which combines all the service, probes and client as described in https://github.com/google/perfetto/issues/47#issuecomment-656639007
