### ISSUE TITLE
Using Perfetto alongside trace-cmd

### ISSUE THREAD

**Issue by mrkajetanp** [google/perfetto#481]
Hi, at least in theory it should be possible to use Perfetto and trace-cmd at the same time. trace-cmd can make use of ftrace's instance functionality and isolate all of its tracing away from the top level buffer. However, Perfetto fails to set up its ftrace Data Source if ftrace is being used by something else. The furthest I got was setting up trace-cmd, manually switching off tracing through ftrace and then enabling Perfetto. This led to fine output from trace-cmd but the Perfetto trace looked broken - some of the timeline was there but with some warnings about mismatched tids from sched_switch and such. Are there any hard reasons why this type of parallel tracing would not be possible? Looking through the codebase I found some comments about how the tool tries to make a 'best effort' to work alongside other users of ftrace.

**Comment by chromy** [comment]
Hey :)

Couple of questions:
- Is this Android or Linux?
- Which version of traced_probes are you using (HEAD? or something prior)

I'm suspicious you are on an older version because while in the past we errored out if someone had already enabled ftrace now we remember the state so we can put it back the way it was: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/src/traced/probes/ftrace/ftrace_config_muxer.cc;l=619?q=current_state_%20f:perfetto

In short: This should be possible now although maybe a little awkward.

The codebase recently got support for a) 'taking over' [a running ftrace instance](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/config/ftrace/ftrace_config.proto;l=173?q=ftrace%20instance%20f:perfetto) and b) [using a non-main instance](https://cs.android.com/android/platform/superproject/+/master:external/perfetto/protos/perfetto/config/ftrace/ftrace_config.proto;l=194?q=ftrace%20instance%20f:perfetto). Some combination of these features should be sufficient possibly with some judicious hacks should make it work alongside trace-cmd.
