### ISSUE TITLE
fileURL support

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#493]
I am trying to open .trace json files in Perfetto, but the example scripts here fire up and leave running an http server for what is really a local fileURL.  I'm actually using "record_android_traces.py --view", so maybe I should try the following script to see if it terminates.

https://github.com/google/perfetto/blob/master/tools/open_trace_in_ui

Can I pass a file URL to Perfetto instead, or is that some blocked browser security breach?  On Windows, the problem is that I'm launching the python scripts from a system() call using cmd or start /B, and this code blocks.  So I've got 100's of command prompts that never end as well.

**Comment by LalitMaganti** [comment]
Unfortunately this is a limitation of how browsers work: websites cannot access the local filesystem without the user explicitly selecting the file from the browser filepicker. Exposing the file via a HTTP server is really the only scriptable way to pass data which is exactly why the script is written that way.

Instead of launching with a system call, if you're already in Python, why not simply start a new thread and run the contents open_trace_in_ui script in your code? If you're not in Python, you should be able to very easily write a wrapper script which does the same threading trick and call that as using a single system() call from your code.

In any case, not much we can do on the Perfetto side about this unfortunately.

**Comment by alecazam** [comment]
These files are opened from C++ app writing out a json trace file, and then spawning a system() call to display the profile.  I know there's a faster method using C++ api instead of json.  Seemed like sometimes the HTTPServer didn't stop which would cause the system() call to block.  But that seems to not be happening now.
