### ISSUE TITLE
Deep linking issue

### ISSUE THREAD

**Issue by JayThomason** [google/perfetto#525]
At my company we have been successfully using perfetto [deep linking](https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui) for a few years in production, but recently it stopped working properly.

The issue that I am seeing is that after opening a new browser window and posting a "ping" message to it, we are not getting a "pong" response. It seems like we can't post any message to perfetto in a different window.

I have tested in both Firefox and Chrome and neither seems to work as it used to. I don't know exactly when it stopped working, but we only noticed today.

I would appreciate any advice or help debugging this!

Here is the javascript code we are using:
```javascript
/**
 * Opens a trace in Perfetto using deep linking.
 *
 * For details see: https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui
 *
 * @param {ArrayBuffer} arrayBuffer - The JSON trace data to load in perfetto, serialized to an ArrayBuffer.
 * @param {String} title - The title to use for the Perfetto window.
 * @returns {boolean} - Return true on success and false if the Perfetto window couldn't be opened.
 */
function openTrace(arrayBuffer, title) {
    const PERFETTO_ORIGIN = "https://ui.perfetto.dev";
    const win = window.open(PERFETTO_ORIGIN);
    if (!win || win.closed || typeof win.closed == "undefined") {
        console.log("Popup blocked!");
        return false;
    }

    const ping_func = () => {
        win.postMessage("PING", PERFETTO_ORIGIN);
    };

    const timer = setInterval(ping_func, 50);

    const onMessageHandler = (evt) => {
        if (evt.data !== "PONG") return;

        // We got a PONG, the UI is ready.
        window.clearInterval(timer);
        window.removeEventListener("message", onMessageHandler);

        console.log("Posting message with buffer length: " + arrayBuffer.byteLength)

        const message = {
            perfetto: {
                buffer: arrayBuffer,
                title: title,
            },
        };
        win.postMessage(message, PERFETTO_ORIGIN);
    };

    window.addEventListener("message", onMessageHandler);
    return true;
}
```

**Comment by chromy** [comment]
Hi @JayThomason!

Glad you are finding Perfetto useful.

Yesterday we released a new versions of the canary and stable UI so this is likely related to that some how.

That said deeplinking continues to work on our internal sites with the new versions of the UI so there must be some difference.

To could confirm a couple things to help me debug this:
- Is the source website is served over https:// ?
- Does devtools in both the source website and Perfetto show any unusual errors?
- the version of ui.perfetto.dev you are on (this is visible in the lower left at the bottom of the sidebar)

Thanks!

**Comment by JayThomason** [comment]
Thanks for the prompt response @chromy.

* The source website is served over https in dev/prod and http for local development -- bothexperience the same issue.
* Sometimes I see this error in the console for the source site, but it is not happening every time: 
```Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://ui.perfetto.dev’) does not match the recipient window’s origin (‘https://...)```
I also see this warning which happens consistently ```Storage access automatically granted for origin “https://ui.perfetto.dev/” on “[https://](https://...)```
* The ui.perfetto.dev version is `v34.0-ad24a`

**Comment by chromy** [comment]
Thanks :)

So one thing that can cause this issue is serving the source site with `Cross-Origin-Opener-Policy: same-origin` header.
For example see the following gist which reproduces a similar issue: https://gist.github.com/chromy/e83deb52558724fc332181050af18521

You can see if this is happening by looking at the headers in devtools:
<img width="1406" alt="Screenshot 2023-07-07 at 09 33 11" src="https://github.com/google/perfetto/assets/351085/8296b5f4-38b6-4496-a0ca-30d659747030">

In general given the symptoms I suspect some form cross origin browser security getting in the way.

If its not `Cross-Origin-Opener-Policy` the next steps for debugging are to work out if https://ui.perfetto.dev is receiving the ping or not. The easiest way may be to set a breakpoint in ui.perfetto.dev near here: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/frontend/post_message_handler.ts;l=62?q=%27PONG%27%20

**Comment by JayThomason** [comment]
This is fixed now. Thanks for the help!
