### ISSUE TITLE
Interning data

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#526]
I find the doc not super clear on how to use `InternedData`

What I have so far is sth like
- a Map<String, Long> internedStrings = new HashMap<>();
- InternedData.Builder internedDataBuilder = InternedData.newBuilder();
when I want to add a new event I'm doing sth like

```
TrackEvent.newBuilder()
  .setNameIid(toTrackName(name))
 //  ... other stuff
```
and I have
```
    private long toTrackName(String name) {
        var iid = internedStrings.computeIfAbsent(name, __ -> iidCounter.getAndIncrement());
        var eventName = EventName.newBuilder()
            .setIid(iid)
            .setName(name)
            .build();
        internedDataBuilder.addEventNames(eventName);
        return iid;
    }
```

basically get an ID for each new 'name' string, and add that to the interned data, but store the iid and not the name on the track.
I also add the interned data to my trace packet like so
```

TracePacket.newBuilder()
            .setTrustedPacketSequenceId(1)
            .setInternedData(internedDataBuilder.build())
            .build()
```

but in the generated trace, the track names are all null.
What am I doing wrong ?

**Comment by facewindu** [comment]
See this [textproto](https://github.com/google/perfetto/files/11977403/textproto.txt.zip) representation.

What's probably weird is that I have my map to get unique ids, so for instance for each `TaskStarted`, the map returns ID 4
I then store it in my interned data builder (only once) via 
```
        var eventCategory = TrackEventOuterClass.EventCategory.newBuilder()
            .setIid(4)
            .setName("TaskStarted")
            .build();
        internedDataBuilder.addEventCategories(eventCategory);
```

and below, for the event that should reference this, you can see e.g. this packet
```
packet {
  timestamp: 9447
  trusted_packet_sequence_id: 1
  track_event {
    category_iids: 4                     <------------------------------- this is what I understood would link it to the proper interned string
    debug_annotations {
      name_iid: 5
      dict_entries {
        name_iid: 6
        string_value_iid: 7
      }
      dict_entries {
        name_iid: 8
        string_value_iid: 9
      }
      dict_entries {
        name_iid: 10
        string_value_iid: 11
      }
      dict_entries {
        name_iid: 12
        string_value_iid: 13
      }
      dict_entries {
        name_iid: 14
        string_value_iid: 15
      }
      dict_entries {
        name_iid: 16
        string_value_iid: 17
      }
    }
    type: TYPE_SLICE_BEGIN
    name_iid: 3
    track_uuid: 2
  }
  timestamp_clock_id: 64
}
```

**Comment by ddiproietto** [comment]
Thanks for sharing the trace. I think these changes should solve your problems:

1. The first packet you emit should have `sequence_flags: 1` (documented in [trace_packet.proto](https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/protos/perfetto/trace/trace_packet.proto;l=254-280;drc=a977e772941ffda7e0f421c2787f0479fce740b8)). You're basically telling trace_processor that the interned data from this point on can be considered complete.
2. 0 is not a valid iid. The iids should start from 1.
3. Iid "spaces" are separate for each type. DebugAnnotation.string_value_iid uses a different "space" from TrackEvent name_iid. For example, in your textproto, you have:
```
    event_names {
      iid: 108
      name: ":core:analytics:generateDemoReleaseResources"
    }
```

and then later:

```
      dict_entries {
        name_iid: 8
        string_value_iid: 108
      }
```

That string_value_iid cannot refer to 108, because it's an event_name. If you want something that can be used as a string_value_iid, you should replace the first block with:

```
    debug_annotation_string_values {
        iid: 108
        str: ":core:analytics:generateDemoReleaseResources"
    }
```

This also means that if you want, you can reuse the same iid number for different types and they will not conflict (smaller iids will save space due to varint encoding).

Hope this helps, let me know if this doesn't solve you problem

**Comment by facewindu** [comment]
Hey @ddiproietto 
sorry for answering only now, but this is indeed working correctly now
thanks
