### ISSUE TITLE
DataSource silently dropping packets

### ISSUE THREAD

**Issue by djdeath** [google/perfetto#575]
I have created a data source inside the Mesa3D project to report GPU activity.
The activity is generated out of GPU timestamp taken at the boundary of GPU operations (draw calls, dispatches, etc...)

For some reason when trying to capture the draw calls, the entire set of GPU data goes missing : 
![Screenshot from 2023-08-30 16-12-33](https://github.com/google/perfetto/assets/434333/79d0a01f-0e5c-4cb5-80a5-814190831d79)

That seems to correlate with when ftrace datasource is starting to produce data.

If I remove the draw calls from the recording, then I'm not missing anything on the GPU timeline and I have a full CPU/GPU timeline showing ftrace & GPU data.

Afaict the GPU datasource is working properly. I can see on the ftrace timeline that it's still doing some work and I've added CPU traces to show that it is in fact generating data. But things seems to go to /dev/null.
So my guess is that there is something inside the perfetto SDK silently dropping the data, or the receiver somehow ignore it.

Any idea how to debug this?

**Comment by ddiproietto** [comment]
There are many ways in which things can go wrong. The SDK and the whole perfetto tracing system is designed to be low overhead. This sometimes means that we consciously decide to lose some data over slowing down your process. Let me explain a few possible scenarios of data loss and let's see if one of those applies here.

First of all, for a lot of cases of data loss, we show a big orange bubble with an exclamation mark on the top right corner of the UI. Do you see that? If you click on it it should point to some error counters, which could help you understand a little bit better what's happening.

There could be loss in the central tracing buffer. What does your config look like? How big are your buffers? Are you using separate buffers? Are you using `DISCARD` mode or `RING_BUFFER` mode for the buffers? Are you using long tracing mode with `file_write_period_ms`?

Can you tell more about your data source? Are you using a [custom data source or track events](https://perfetto.dev/docs/instrumentation/tracing-sdk#custom-data-sources-vs-track-events)? If you're using a custom data source, what kind of protos are you emitting?

If your data source is using incremental data (if packets are marked as `SEQ_NEEDS_INCREMENTAL_STATE`), it's possible that a single packet loss is causing the UI to stop displaying the rest of the events. Cay you manually inspect the trace with `traceconv text` and see if you're seeing the missing events or if you have packets with `previous_packet_dropped: true` (the first packet for each data source will have this, if other packets have this, it's a problem)?

A single packet loss can happen because, the shared memory buffers between your process and the central tracing service are not big enough. You can configure the shared memory buffer size in your tracing config (only the first time you start tracing a process) or in the instrumented code with `TracingInitArgs::shmem_size_hint_kb`. Or, if you really don't want to lose any data (at the cost of slowing down and potentially crashing your process), you can use BufferExhaustedPolicy::kStall for your data source (not recommended in production).

How are you enabling the "draw calls"? Is it just a config option for the data source with conditionals in the tracing lambda, or do you require a separate data source?

Reference (I strongly advise a read): https://perfetto.dev/docs/concepts/buffers#buffer-sizing

**Comment by djdeath** [comment]
Thanks for the quick answer.

> First of all, for a lot of cases of data loss, we show a big orange bubble with an exclamation mark on the top right corner of the UI. Do you see that? If you click on it it should point to some error counters, which could help you understand a little bit better what's happening.

Yeah I see that but I don't see any loss counter != 0

The top header says this : 
```
The following errors have been encountered while importing the trace. These errors are usually non-fatal but indicate that one or more tracks might be missing or showing erroneous data.
```

| Name | Value | Type |
| -- | -- | -- |
| invalid_clock_snapshots | 1 | error (analysis) |

> There could be loss in the central tracing buffer. What does your config look like? How big are your buffers? Are you using separate buffers? Are you using DISCARD mode or RING_BUFFER mode for the buffers? Are you using long tracing mode with file_write_period_ms?

Here is the config file https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/tool/pps/cfg/intel.cfg

I did bump the buffer size to 524288 kb, that didn't change the outcome.

The datasource is a bit custom : https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/intel/ds/intel_driver_ds.cc
The types of trace points we use is describe here in python : https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/intel/ds/intel_tracepoints.py

I did manually inspect the trace with `traceconv text` and it appears that data is missing there too (so not a UI issue).

Tried `BufferExhaustedPolicy::kStall` too, no difference.

We can turn on/off the GPU tracepoints with an environment variable. If turned off the GPU doesn't even record a timestamp and so there is not perfetto tracepoint generated.

**Comment by ddiproietto** [comment]
Interesting

> > How are you enabling the "draw calls"? Is it just a config option for the data source with conditionals in the tracing lambda, or do you require a separate data source?
> 
> We can turn on/off the GPU tracepoints with an environment variable. If turned off the GPU doesn't even record a timestamp and so there is not perfetto tracepoint generated.

You said:

> If I remove the draw calls from the recording, then I'm not missing anything on the GPU timeline and I have a full CPU/GPU timeline showing ftrace & GPU data.

What do you mean by "remove the draw calls from the recording"?

Can you share a good trace and a bad trace, please?

**Comment by djdeath** [comment]
By "remove" I meant "turn off"

Good one : https://drive.google.com/file/d/1vLEQH0H7zmeyX9mr7Q6GFRD81wPsA4Rw/view?usp=drive_link
Bad one : https://drive.google.com/file/d/1vM_gkf2KtSTLuoiQ655GnNhFF_omea3o/view?usp=drive_link

**Comment by ddiproietto** [comment]
> Tried to direct things into 3 different buffers and have each source target a different one. Results are puzzling :

I think this is expected, since each buffer wraps independently. The buffer for the ftrace data source produces a lot of data and wraps very quickly, therefore only the last few milliseconds are kept.

I'd advise to use just one big buffer.

> Good one : https://drive.google.com/file/d/1vLEQH0H7zmeyX9mr7Q6GFRD81wPsA4Rw/view?usp=drive_link
> Bad one : https://drive.google.com/file/d/1vM_gkf2KtSTLuoiQ655GnNhFF_omea3o/view?usp=drive_link

Thanks for sharing.

I don't see anything obvious that could explain the difference between these two. (I'm not familiar with the data sources in mesa, so it's hard for me to understand what's going on).

**Comment by LalitMaganti** [comment]
All questions seem to be answered and it doesn't seem like there's any action needed from our side.
