### ISSUE TITLE
Can we support zip file in webui?

### ISSUE THREAD

**Issue by rollysys** [google/perfetto#584]
The trace files are too large usually, so it's hard to store many trace files locally.
It will be great helpful if perfetto webui support zip file.
Thanks!

**Comment by LalitMaganti** [comment]
zip files are a complicated format to support because they can be multiple files inside a single zip file.

We already support compressing by gzip and transparently decompressing or collecting traces which are internally compressed using the deflate algorithm. Either of these options should be more than sufficient so there should not be a need for zip compression.

**Comment by rollysys** [comment]
Thanks so much for reply!
But I have tried using trace.tar.gz in the web ui, it fails.
As can be found in the changelog, gzip format only be supported in traceconv?
Hope the web ui could support any compresss format.
Thanks again

**Comment by LalitMaganti** [comment]
.tar.gz has the same problem as zip where it supports multiple files
inside. You want to just gzip without tarring.

gzip is also supported in the UI not just in traceconv
