### ISSUE TITLE
Why do the "copy query" and "copy result" buttons in the SQL query interface not work?

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#586]
Perfetto v37.0
Clicking the “copy query” button displays the following error message:
Failed to copy "xxxxxx" to clipboard: TypeError: Cannot read properties of undefined (reading 'writeText').

I hope you can give me an answer, thanks.

**Comment by stevegolton** [comment]
Hi @duokuiwang,

It seems `navigator.clipboard` is `undefined` in your enviromnet for some reason.

How are you acessing the UI? You'll need to access it thorugh a secure context in order to have clipboard available.

See: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

**Comment by duokuiwang** [comment]
Thank you.
