### ISSUE TITLE
Failure parsing JSON: unable to parse string

### ISSUE THREAD

**Issue by ag583** [google/perfetto#598]
Whenever I try to load a trace now, I get an error message saying "Failure parsing JSON: unable to parse string". 

This happens even on traces that loaded fine a few days ago. How do I fix this?

Thank you!

**Comment by chromy** [comment]
Sorry to hear that :/

Please attach a trace so we can debug this.

**Comment by Idate96** [comment]
i have the same issue. [Link](https://drive.google.com/drive/folders/1t00JoKjyx84pBlTxVRW1YYLAFXLKwYnw?usp=drive_link) to trace

**Comment by xylcbd** [comment]
same here!

**Comment by barnett-yuxiang** [comment]
> i have the same issue. [Link](https://drive.google.com/drive/folders/1t00JoKjyx84pBlTxVRW1YYLAFXLKwYnw?usp=drive_link) to trace

@chromy check this link? 

I highly recommend establishing a mechanism for synchronizing GitHub issues to the discrod group（a bot）, so that user issues can be followed up in a timely manner. Perfetto also needs an active user group

**Comment by LalitMaganti** [comment]
> i have the same issue. [Link](https://drive.google.com/drive/folders/1t00JoKjyx84pBlTxVRW1YYLAFXLKwYnw?usp=drive_link) to trace

Took a look at the trace: the problem is that one of your traces contains the control character ^A (or 0x01 in Hex) in an event name. Specifically `"|||S(1): <module>"` has it hiding in there.

The JSON specification says that any control codes (between (U+0000 through U+001F) must be escaped. Our parser follows the spec in this case so refuses to parse the JSON.

We could probably have a better error message here but I'd say this is WAI.
