### ISSUE TITLE
Error displaying thread status for rendering

### ISSUE THREAD

**Issue by Gitxg** [google/perfetto#609]
The thread status is no longer displayed under the current thread, but instead runs to a separate process for display

 
![image](https://github.com/google/perfetto/assets/50760172/8eee189c-9302-4d5a-9d2d-6b57c721ad74)

**Comment by Gitxg** [comment]
[myperfetto.zip](https://github.com/google/perfetto/files/13022388/myperfetto.zip)

**Comment by chromy** [comment]
Sorry I'm not sure I understand the problem here.

**Comment by barnett-yuxiang** [comment]
> There is an issue with the status information display of RenderThread 6308 thread. It has been separated and displayed in a single process, so that I cannot see its running status in the child thread, For specific questions, please download the trace information I uploaded to view. Thank you very much.

Is the method of trace collection correct? Can systrace be opened correctly? And what is the device model being captured?

**Comment by LalitMaganti** [comment]
> Is the method of trace collection correct? Can systrace be opened correctly? And what is the device model being captured?

The trace is a Perfetto one not systrace. The trace contains information on the model etc.

> The thread status is no longer displayed under the current thread, but instead runs to a separate process for display

If I had to guess, this issue is a one-off error with this particular trace where for whatever reason we failed to capture the link between the process and the RenderThread.  I'd imagine if you try to collect another trace you would not see the issue.

One huge problem (and potentially related to the issue) I see though by opening your trace though is that your buffer sizes are completely out of this world. All your main buffer sizes are 5GB with your per-cpu buffer (indicated by buffer_size_kb) being 9GB *per CPU*. This is likely causing a ridiculous amount of stress on the system and can significantly distort the trace. I'd strongly suggest switching to some more reasonable sizes instead of just maxing out these numbers.

Also you should not be using DISCARD buffers with write_into_file traces: such traces should always use RING_BUFFER traces.

Please reopen if you can reproduce this issue with a more normal configuration and I'll take a deeper look.
