### ISSUE TITLE
I would like to ask if it can be stored in a new trace file according to a fixed file size or duration.

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#634]
hello！
Now all the data is stored in a trace file, which is not friendly to capturing data for a long time. I would like to ask if it can be stored in a new trace file according to the fixed file size or duration.

thank you~

**Comment by LalitMaganti** [comment]
I think the request here is for a way to split a large trace files into many smaller trace files based on size or duration.

Unfortunately, this is not supported as is because trace files have too much contextual information (i.e. information at the start of the trace can affect how the end of the trace is parsed).

The suggestion instead if you need the smaller trace files is to collect both a big long trace and many smaller traces: Perfetto fully supports concurrent overlapping sessions so you can have multiple traces running at the same time.
