### ISSUE TITLE
How to forward and store trace files to a specified machine through the network？

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#643]
hello~

When you use the perfetto command to capture trace files, they are stored on the local machine by default. So how do you store the trace files on a remote designated machine?

my platform：linux

thank you~

**Comment by primiano** [comment]
I am not fully sure I understand what you want to do. I can offer two options

1. Capture the trace locally, maybe on tmpfs, and then use ssh/scp/sftp to move it to another machine.
2. Capture the trace remotely forwarding the cmdline client via a SSH tunnel. Something like the below:

- Start perfetto services (traced, traced_probes) on the target machine, forwarding the consumer socket over ssh: `ssh -L/tmp/perfetto-consumer:/tmp/perfetto-consumer lon /s/perfetto/tools/tracebox traced`  (remember also to start traced_probes and other damons as needed)
- Start the cmdline client on your local machine, using the forwarded socket path:  `PERFETTO_CONSUMER_SOCK_NAME=/tmp/perfetto-consumer tracebox perfetto -o out.pftrace --txt -c config_file`

**Comment by duokuiwang** [comment]
> I am not fully sure I understand what you want to do. I can offer two options
> 
> 1. Capture the trace locally, maybe on tmpfs, and then use ssh/scp/sftp to move it to another machine.
> 2. Capture the trace remotely forwarding the cmdline client via a SSH tunnel. Something like the below:
> 
> * Start perfetto services (traced, traced_probes) on the target machine, forwarding the consumer socket over ssh: `ssh -L/tmp/perfetto-consumer:/tmp/perfetto-consumer lon /s/perfetto/tools/tracebox traced`  (remember also to start traced_probes and other damons as needed)
> * Start the cmdline client on your local machine, using the forwarded socket path:  `PERFETTO_CONSUMER_SOCK_NAME=/tmp/perfetto-consumer tracebox perfetto -o out.pftrace --txt -c config_file`

I tried the method you mentioned, however, the collected data is local, not remote. It feels like this PERFETTO_CONSUMER_SOCK_NAME does not take effect. May I ask if you have any other methods?

**Comment by primiano** [comment]
I am sorry but if you want to get some help you need to be more specific in your requests.
Please word your bugs in the form of:
1) The exact commands you are running and where
2) What you expect to happen
3) What happens instead

**Comment by duokuiwang** [comment]
> I am sorry but if you want to get some help you need to be more specific in your requests. Please word your bugs in the form of:
> 
> 1. The exact commands you are running and where
> 2. What you expect to happen
> 3. What happens instead

```
machine A:  10.10.10.10   arch: arm   os: linux
machine B:  192.168.9.1   arch: x86    os: linux
```

**Purpose: I want the data captured on machine A to be stored in machine B in real time and generate a trace file.  
I used method 2.**

machine A:  
1. `./traced --background`
2. `./traced_probes --background --reset-ftrace`
3. `ssh -L 10.10.10.10:/tmp/perfetto-consumer:192.168.9.1:/tmp/perfetto-consumer user_name@192.168.9.1 bash /machineB/run.sh`

The content of file run.sh is:
> #!/bin/bash
> ./traced --background
> ./traced_probes --background

Since ftrace is not enabled on machine B, there is no --reset-ftrace parameter.

machine B:  
`PERFETTO_CONSUMER_SOCK_NAME=/tmp/perfetto-consumer ./perfetto --txt -c demo.cfg -o out.ftrace`

****Problem:** The captured out.ftrace file does not store the data of machine A, but of machine B, which is contrary to my purpose.**

Please tell me where I wrote it wrong? What should I do to achieve this purpose? 
I'm looking forward to your reply, thank you so much.

**Comment by primiano** [comment]
> ./traced --background
> ./traced_probes --background --reset-ftrace

Wait, you are running traced and traced_probes both on Machine A and Machine B (via run.sh). DO you really want both? I thought you wanted only Machine B's tracing, not Machine A.

In all the instructions below I'm going to assume that you want only Machine B's trace data, and no tracing at all from Machine A (if that's the case we need to tweak things a little bit)

> ssh -L 10.10.10.10:/tmp/perfetto-consumer:192.168.9.1:/tmp/perfetto-consumer user_name@192.168.9.1 bash /machineB/run.sh

Why the forwarding is not just `-L/tmp/perfetto-consumer:/tmp/perfetto-consumer` ? You are forwarding a unix socket, not a TCP connection, there should be no IP addresses in the fwd config.


> machine B:
PERFETTO_CONSUMER_SOCK_NAME=/tmp/perfetto-consumer ./perfetto --txt -c demo.cfg -o out.ftrace

This is wrong, this command should be run still from Machine A.

What's going to happen is the following

- Machine B will start traced and traced_probes
- Machine B will by default listen on /tmp/perfetto-consumer
- The SSH cmdline will forward connections for MachineA:/tmp/perfetto-consumer to MachineB:/tmp/perfetto-consumer (This will be used by the next command)
- Then you run perfetto's cmdline client on Machine A (This is your mistake)
- Perfetto cmdline tries to connect to /tmp/perfetto-consumer 
- Because of the forwarding, the perfetto cmdline client running on machine A will be talking to the traced server on machine B

Let me change the names a little bit so you might be able to tell more what's happening and we can avoid confusion:


Machine A:

- `ssh -L /tmp/forwarded-socket:/tmp/perfetto-consumer user_name@192.168.9.1 bash /machineB/run.sh`
- PERFETTO_CONSUMER_SOCK_NAME=/tmp/forwarded-socket ./perfetto --txt -c demo.cfg -o out.ftrace

That's it

This will generate an out.trace on Machine A. The trace will be obtained by the perfetto cmdline client (which will run on Machine A) talking to the traced service running into Machine B, tunneling the socket via SSH forwarding.

Does it make sense?

**Comment by duokuiwang** [comment]
hello~  
I tried it as you suggested, but when I executed this command(`PERFETTO_CONSUMER_SOCK_NAME=/tmp/forwarded-socket ./perfetto --txt -c demo.cfg -o out.ftrace`) on machine A, I did not run traced and traced_probes separately on machine A.

I got an error:
`[162.402]    perfetto_cmd.cc:1040 Disconnected from the Perfetto traced service`


The perfetto cmdline client running on machine A will **not** be talking to the traced server on machine B.

I saw the forwarded /tmp/forwarded-socket on machine A.
What is the reason for this? I'm looking forward to your reply, thank you so much.

**Comment by duokuiwang** [comment]
hello, first of all thank you~
Now the perfetto cmdline client will always be stuck,  the error message is `channel 2: open failed: unknown channel type:`
![image](https://github.com/google/perfetto/assets/31888567/7f469fb1-209c-4ecc-83ac-c3bebbf87025)
![image](https://github.com/google/perfetto/assets/31888567/6c633fab-fa25-485e-b377-cf990d3de4b9)

Is this because the ssh versions of machine A and machine B are different? 
```
machine A:  10.10.10.10   arch: arm   os: linux  ssh version: Dropbear v2019.78
machine B:  192.168.9.1   arch: x86   os: linux  ssh version: OpenSSH_8.2p1 Ubuntu-4ubuntu0.9, OpenSSL 1.1.1f  31 Mar 2020
```
machine A's /etc/ssh/sshd_config:   
```
AllowTcpForwarding yes
#PermitTunnel no
```
machine B's /etc/ssh/sshd_config:   
```
#AllowTcpForwarding yes
#PermitTunnel no
```

 I'm looking forward to your reply, thank you so much.

**Comment by primiano** [comment]
Try setting `AllowStreamLocalForwarding yes` as that is not a TCP connection

Unfortunately this seems a SSH-tunneling issue now. Probably dropbear doesn't support something there.
I don't know how to help on this sorry.

**Comment by duokuiwang** [comment]
hi~
Both machines now use the same version of openssh and no longer use dropbear. 
write_into_file=true is set in my configuration file all.cfg, I got an error:
![image](https://github.com/google/perfetto/assets/31888567/bb21589d-ff72-418f-bfed-c423adf976a1)

If write_into_file is not set, the trace data can be captured correctly. 
However, I need to set write_into_file=true, how should I solve this problem? 
I'm looking forward to your reply, thank you so much.

**Comment by primiano** [comment]
write_into_file=true cannot work across forwarding because relies on the cmdline client to forward a file descriptor to traced, which can be done only on the same machine.

Aahhh I see you want long traces.

Okay if you want long traces, then we need to change strategy completely.
Let me propose something completely different. Let's run all 3 (traced, traced_probes, and perfetto_cmd) onto MachineB and let's forward only the output. 

To be honest this is even easier, I am not sure why I didnt' think about this earlier. Let's start everything from scratch:

From Machine A:
`ssh MachineB './tracebox --txt -c /tmp/cfg.txt -o /dev/stdout' > /tmp/trace`

The beauty of tracebox is that takes care of running traced, traced_probes and perfetto all together without having you do deal with 3 processes.

That simple. I tried it with this cfg.txt and it works

```
write_into_file: true
duration_ms: 30000

buffers {
  size_kb: 32768
  fill_policy: RING_BUFFER
}

# Enable various data sources as usual.
data_sources {
  config {
    name: "linux.ftrace"
    target_buffer: 0
    ftrace_config {
      ftrace_events: "sched_switch"
      ftrace_events: "sched_wakeup_new"
      ftrace_events: "sched_wakeup"
      ftrace_events: "sched_waking"
      ftrace_events: "task_newtask"
    }
  }
}

data_sources {
  config {
    name: "linux.process_stats"
    target_buffer: 0
  }
}

```

**Comment by duokuiwang** [comment]
hi~ 
The new method you mentioned can correctly generate the trace file. However, the file cannot be opened using perfetto ui. It should be that the file format is wrong.

![image](https://github.com/google/perfetto/assets/31888567/5e2a2583-c7c4-4d59-b86a-49c25a67c681)

Is it possible that the`/dev/stdout` output content is then written to the file, causing a format error? How should I solve it?
I'm looking forward to your reply, thank you so much.

**Comment by duokuiwang** [comment]
> hi~ The new method you mentioned can correctly generate the trace file. However, the file cannot be opened using perfetto ui. It should be that the file format is wrong.
> 
> ![image](https://user-images.githubusercontent.com/31888567/284911035-5e2a2583-c7c4-4d59-b86a-49c25a67c681.png)
> 
> Is it possible that the`/dev/stdout` output content is then written to the file, causing a format error? How should I solve it? I'm looking forward to your reply, thank you so much.

I solved this problem, thanks you~

For some reason I'm using the perfetto command instead of tracebox.

Wrong command:
`ssh MachineB './traced --background; ./traced_probes --background --reset-ftrace; ./perfetto --txt -c /tmp/cfg.txt -o /dev/stdout' > /tmp/trace`

When I split the above command into 3 commands it works correctly.

Correct command:
`ssh MachineB './traced --background`
`ssh MachineB './traced_probes --background --reset-ftrace`
`ssh MachineB './perfetto --txt -c /tmp/cfg.txt -o /dev/stdout' > /tmp/trace`

Thank you very much for your patient guidance these days. See you soon.☺

**Comment by primiano** [comment]
what's happenig is that you are forwarding to /tmp/trace the stdout of the other 2 commands (Traced and traced_probeS) that emit some PIDs in stdout.

Why are you not using tracebox btw?

The right way to combine them is something like

`ssh MachineB './traced --background > /dev/null; ./traced_probes --background --reset-ftrace > /dev/null; ./perfetto --txt -c /tmp/cfg.txt -o /dev/stdout' > /tmp/trace`
