### ISSUE TITLE
[BUG] perfetto UI cant show slice end point

### ISSUE THREAD

**Issue by garretzou** [google/perfetto#645]
perfetto can't show slice end point in many brand phones like xiaomi/vivo/oppo. Please help me figure it out.
![image](https://github.com/google/perfetto/assets/7679315/e7b77d21-09fc-4f8b-9c71-cf81a6e1c808)

**Comment by LalitMaganti** [comment]
This usually happens for one of the following reasons:
1) There is data loss in the trace (this appears in the "Info and Stats" page of the UI)
2) There is some slice in that stack which is not correctly ending in the trace itself.

Without access to the the trace there's little we can do to help debug this.

**Comment by garretzou** [comment]
Yes,  "Info and Stats" page alerts many ftrace errors, but why its Okay in chrome://tracing/? 

And how to figure it out?

**Comment by LalitMaganti** [comment]
It's very common to chrome://tracing to simply misrepresent (i.e. basically lie) what is in the trace and show a very distorted view of what is actually going on. Perfetto is a lot better about making that very obvious to the user instead of hiding problems.

We have quite detailed guidance on how you can debug data losses in [our docs website](https://perfetto.dev/docs/concepts/buffers#debugging-data-losses).

**Comment by garretzou** [comment]
Many Thx @LalitMaganti 

Many ftrace_setup_errors appear in "Info and Stats" page like below. 
```text
Ftrace event unknown: dpu/tracing_mark_write
Ftrace event unknown: g2d/g2d_perf_update_qos
Ftrace event unknown: g2d/tracing_mark_write
Ftrace event unknown: mali/tracing_mark_write
Ftrace event unknown: mdss/mdp_cmd_kickoff
Ftrace event unknown: mdss/mdp_cmd_pingpong_done
Ftrace event unknown: mdss/mdp_cmd_readptr_done
Ftrace event unknown: mdss/mdp_cmd_release_bw
Ftrace event unknown: mdss/mdp_cmd_wait_pingpong
Ftrace event unknown: mdss/mdp_commit
Ftrace event unknown: mdss/mdp_compare_bw
Ftrace event unknown: mdss/mdp_misr_crc
Ftrace event unknown: mdss/mdp_mixer_update
Ftrace event unknown: mdss/mdp_perf_prefill_calc
Ftrace event unknown: mdss/mdp_perf_set_ot
Ftrace event unknown: mdss/mdp_perf_set_panic_luts
Ftrace event unknown: mdss/mdp_perf_set_qos_luts
Ftrace event unknown: mdss/mdp_perf_set_wm_levels
Ftrace event unknown: mdss/mdp_perf_update_bus
Ftrace event unknown: mdss/mdp_sspp_change
Ftrace event unknown: mdss/mdp_sspp_set
Ftrace event unknown: mdss/mdp_trace_counter
Ftrace event unknown: mdss/mdp_video_underrun_done
Ftrace event unknown: mdss/rotator_bw_ao_as_context
Ftrace event unknown: mdss/tracing_mark_write
Ftrace event unknown: sched/sched_stat_blocked
Ftrace event unknown: sde/sde_cmd_release_bw
Ftrace event unknown: sde/sde_encoder_underrun
Ftrace event unknown: sde/sde_evtlog
Ftrace event unknown: sde/sde_perf_calc_crtc
Ftrace event unknown: sde/sde_perf_crtc_update
Ftrace event unknown: sde/sde_perf_set_danger_luts
Ftrace event unknown: sde/sde_perf_set_ot
Ftrace event unknown: sde/sde_perf_set_qos_luts
Ftrace event unknown: sde/sde_perf_update_bus
Ftrace event unknown: sde/tracing_mark_write
```

**Comment by LiangliangSui** [comment]
Hi @LalitMaganti ,

I open many traces every day, and many of them are like what is described in this issue.

It causes me a lot of trouble, because the nesting between unfinished slice levels prevents me from easily viewing the normally ended slices. Maybe I don’t care much about the unfinished slices, but it prevents me from viewing the normal ones. 

So, is it possible to add an option in the flags menu to ignore slices that have not ended normally in the UI? I think that should be very practical and a strategy that has the best of both worlds.

**Comment by stevegolton** [comment]
Hi @LiangliangSui, this sounds like a very reasonable idea. I suppose we could either ignore them, or display them as instant-like events so at least they still appear on the timeline in some capacity.

I'll look into it and try to schedule some time to work on it.

**Comment by LiangliangSui** [comment]
![image](https://github.com/google/perfetto/assets/116876207/11899a14-a28d-468c-8bdd-62b98cc52bfc)


![image](https://github.com/google/perfetto/assets/116876207/6b3250a9-4b04-48c9-8b6b-b363cc97eebb)

Like this? But it seems that the depth of other slices cannot be changed, because the depth is generated by tp.

Or do you have other better display solutions?

I'm more than willing to discuss this or contribute

**Comment by LiangliangSui** [comment]
Or like this?
![image](https://github.com/google/perfetto/assets/116876207/8c693b6a-1917-48f5-8cdb-85bdaa9bf57e)

------

![image](https://github.com/google/perfetto/assets/116876207/09dbc9dd-8c0e-4d8c-9b1c-fa47977ba1e9)

**Comment by LiangliangSui** [comment]
> How wide are the little boxes? Are they a fixed pixel width or a fixed time width?

I set it to fixed pixel width, 20px.


> In future it might be nice to make a guess at the min/max length the slice must be by looking at it's parent and it children and splitting the difference

Yes, my initial idea was also to guess an endTs based on the child slice, but I encountered some problems, such as
depth 0: &nbsp;&nbsp;&nbsp;   -------------------slice1-----------------------------(Did not end)-----

depth 1: &nbsp;&nbsp;&nbsp;  ----slice2---  &nbsp;&nbsp;&nbsp;   ---------------slice3-----------  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   ---------------slice4-------------

On the same track, the level depth is 2, slice1 is an unfinished slice, slice2 and slice3 are the child slices of slice1, slice4 is not the child slice of slice1, but since slice1 is not ended, TP will also judge slice4 as slice1's. child.

If the child slice with the largest endTs among all child slices is used as the endTs of slice1, then in the current situation, the endTs of slice1 is the endTs of slice4, which is obviously wrong (because slice4 is not actually a child of slice1).

Perhaps, it is guessed that endTs needs the support of tp.

> It looks a bit odd that we have child slices floating in mid air - took me a while to grok.

It's odd that child slices are floating, but you can eliminate the impact of unfinished slices on normal slices.

> On the other hand, perhaps this was the guesswork [@LalitMaganti](https://github.com/LalitMaganti) was referring to and we should avoid it.

We should indeed avoid this problem as much as possible, but I always encounter similar situations in my daily work. Every day, many users find system performance problems and use System Tracing on the mobile phone to help me record traces, but they During the capture process, the correct buffer size may not be set or other configuration may cause trace loss events. I cannot ask users to help record traces with the same problem again because they may not be able to reproduce the problem again. I can only Analyze existing traces, but most of the traces are available.
​

**Comment by LiangliangSui** [comment]
I uploaded a [patch](https://android-review.googlesource.com/c/platform/external/perfetto/+/2848882), PTAL!
