### ISSUE TITLE
A crash happens  in libperfetto.so when capture perfetto-trace

### ISSUE THREAD

**Issue by Shi-Yukun** [google/perfetto#646]
When I try to capture  a perfetto-trace by using  'adb shell perfetto -o /data/misc/perfetto-traces/trace_file.perfetto-trace -t 5s sched freq idle am wm gfx' , a crash happens  in libperfetto.so.
The main error log is: 
[284.765] ranslation_table.cc:133 Failed to infer ftrace field type for "f2fs_truncate_partial_nodes.nid" (type:"nid_t nid[3]" size:12 signed:0) (errno: 2, No such file or directory)'
Which configuration should I check to solve this problem？ 

Android version：T
kernel version: 5.4

**Comment by ddiproietto** [comment]
> Which configuration should I check to solve this problem？

Unfortunately this is not a problem you can solve with a configuration change. This is a problem that needs to be fixed in the perfetto code.

The fix has been merged in https://r.android.com/2583173, your device manufacturer needs to include this patch in the system image.

What device are you using?

**Comment by Shi-Yukun** [comment]
Thank you very much for your answer！
I am sorry for mistaking the kernel version. It is 5.15 instead of 5.4 
The device I used is our inner engineering which is not yet sold. I will promote the merge of this patch.
