### ISSUE TITLE
Interested in Bazel for JS?

### ISSUE THREAD

**Issue by alexeagle** [google/perfetto#667]
Hey there, I'm a lead for Bazel and noticed your https://github.com/google/perfetto/blob/master/ui/build.js is fairly bespoke. Would you be interested in a minimal PR illustrating some part of that build process written as BUILD files?

**Comment by primiano** [comment]
Hey @alexeagle,
I'm the person who wrote the initial version of build.js

I can give you a quick answer to the bespoke part: the bespoke build.js is mainly due to:

1) Due to the (sad) way the JS ecosystem works, the only way to have fast incremental builds is to mount a pipeline of processes (tsc compiler,  rollup bundler, scss transpiler) in --watch mode and keep them alive, so each process consumes live updates form the previous one in the pipeline. Unlike what happens in C/C++/Java, trying to handle incremental builds as "re-invoke the compile from scratch" leads to 10x slower incremental builds.

What happens in that build.js that some of the compilation pipeline stages is handled by the various processes running in --watch mode. In turn they re-trigger (via fsnotify) portions of the build.js file that reacts to those changes. So You'd need a mixture of "external processes that do things in reaction to files changing " and "build rules being retriggered when their inputs change"

2) Livereload feature, to detect fs changes in the final dist folder and turning them into HTTP events for the livereload client

3) The fact that we have nodejs already bundled as a dependency, because it's needed to build anyways (And it can be downloaded as a standalone executable without any complex installation)

If we ended up in something bazel-based that handled only full compilations, without the process pipeline in --watch mode, that would be completely uninteresting for me an my team. 

Our initial UI build was based on GN+ninja (which I adore) and we moved away precisely for the reasons mentioned above:

Here's my skepticism about bazel:
- I am not sure it can handle case 1 (general build systems are not a good fit for keeping processes around indefinitely while at the same time re-triggering rules on change)
- In any case I'd need some dedicated JS file for the http server + livereload
- I suspect even if it worked we'd end up with more lines of code/rules to maintain, with the extra burden for our deves of having to understand two languages/tools, not one

But I'm happy to be proven wrong

Primiano

**Comment by primiano** [comment]
> use tools which don't suffer that slow startup time, for example we recommend using https://swc.rs/ to transpile .ts -> .js

Sorry we are not going to move away from the official typescript compiler. That is beyond a build system discussion and generally is going to move us on our smaller tech island. Not going there.


> use tools which don't suffer that slow startup time

If this was the premise, then I'd argue: why not just GN+Ninja? What does Bazel buy? Ironically, one of the things I found irritating about bazel is the startup time of each bazel invocation :D

> I agree about adding another build tool being a maintenance burden but I saw you do already have Bazel BUILD files in the repo

Those files are auto-generated from our GN files (which is the source of truth). 99% of the times nobody in the team has to think about bazel, only about GN.

> My interest here was in possibly building perfetto into Bazel itself to make it more convenient to view traces. 

This does not follow to me. How is changing the perfetto buildsystem going to improve its convenience of trave vieweing? Can you expand?
