### ISSUE TITLE
The lock in the “TRACE_EVENT” interface causes the running thread to sleeping

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#694]
Add the TRACE_EVENT interface in the function to capture trace data. Load trace files using UI, find that the thread where the function is located is in the running state at first, then **sleeping for a period of time**, and then converts to the runnable state (awakened by Tracing Muxer).
The Sleeping introduces unnecessary time overhead to the our app. For example, it will increase the delay of a function.

By capture syscall data, we found that **sys_futex** was called during sleeping.

![image](https://github.com/google/perfetto/assets/31888567/7976d588-89ab-4897-870b-c732f1a70174)

There are a few questions:
（1）Why does a normally running thread switch to sleeping state? The reason is lock?
（2）Is there a lock mechanism in the TRACE_EVENT interface? But I didn't find any lock.
（3）How to avoid thread switching from running to sleeping in a friendly way when using TRACE_EVENT？

Thank you so much~

**Comment by ddiproietto** [comment]
Hi!

> (1) Why does a normally running thread switch to sleeping state? The reason is lock?

In this case, it looks like the reason is a lock

> (2) Is there a lock mechanism in the TRACE_EVENT interface? But I didn't find any lock.

Yes, there are some locks, I'm afraid:

* Every thread normally writes to its own shared memory chunk, so it doesn't need to take any lock. When the memory chunk is finished though (every 1Kb), it does take this lock to acquire another chunk: https://github.com/google/perfetto/blob/13e65b2e4748f79c355d6390e11162812fcb8db2/src/tracing/core/shared_memory_arbiter_impl.cc#L113
* The first time each thread sees a Track https://github.com/google/perfetto/blob/13e65b2e4748f79c355d6390e11162812fcb8db2/include/perfetto/tracing/internal/track_event_internal.h#L252 it will take a lock: https://github.com/google/perfetto/blob/13e65b2e4748f79c355d6390e11162812fcb8db2/include/perfetto/tracing/track.h#L364

Most of the times these are not taken and tracing goes through the fast path, but sometimes TRACE_EVENT can actually take a lock.

> (3) How to avoid thread switching from running to sleeping in a friendly way when using TRACE_EVENT?

I'm afraid there's no solution. Perfetto has to perform cross thread synchronization from time to time and that involves taking a lock in the current implementation.

Please, let me know if you have any other questions.
