### ISSUE TITLE
Can't see CPU Frequency in Perfetto UI (chrome works fine)

### ISSUE THREAD

**Issue by Over17** [google/perfetto#72]
Hi!

I've recorded a trace file having checked the CPU Frequency checkbox (for that purpose, I use old monitor tool UI which still works on Windows).
Opened the trace file in Perfetto UI. Works well, except for I cannot see the CPU frequency (should be the height of the bar in the CPU section?).
Checked in chrome://tracing - the data is there.

I'm happy to share the trace file but for some reason github doesn't want it here.
Also tried to report the bug from Perfetto UI itself - redirects to moma internal Google system which I don't have access too.

Thanks!

**Comment by primiano** [comment]
I think this might be an old outstanding issue where cpu frequency is displayed only if cpuidle information is also present (because they are rendered in the same track).
Can you try also enabling cpuidle recording?

**Comment by Over17** [comment]
Thank you. Just tried - no luck. Maybe the device doesn't allow for cpu_idle collection (got an EU S8 SM-G950F)?

**Comment by primiano** [comment]
There's one way to tell:  open the "query" tab and paste the current query:
`select name, count(1) from counters where name like 'cpu%' group by name`

if it shows only cpufreq, that's the issue.
On a good trace it shows something like this:
![image](https://user-images.githubusercontent.com/7137473/99411116-264df180-28eb-11eb-923a-626818a89343.png)

**Comment by Over17** [comment]
ha, it only shows cpuidle and no cpufreq. (but the frequency is still there in chrome tracing!)

**Comment by primiano** [comment]
That's really weird. Which format is the trace? how did you capture it?
Is there any chance you can attach it somewhere?

**Comment by Over17** [comment]
The trace has entries like
   cfinteractive-953   (  953) [000] ...1  1461.607586: cpu_frequency: state=1456000 cpu_id=0
   cfinteractive-953   (  953) [000] ...1  1461.607594: cpu_frequency: state=1456000 cpu_id=1
   cfinteractive-953   (  953) [000] ...1  1461.607598: cpu_frequency: state=1456000 cpu_id=2
   cfinteractive-953   (  953) [000] ...1  1461.607601: cpu_frequency: state=1456000 cpu_id=3

Try here: https://drive.google.com/file/d/1zYVbRciZvNvNiLgSpG5SDCbL45SG37cD/view?usp=sharing

**Comment by primiano** [comment]
Ahh, ahahah, yes. The problem is here:
https://github.com/google/perfetto/blob/8d2a9ab275b5761104956281bf07a41f4ecb143a/src/trace_processor/importers/systrace/systrace_line_parser.cc#L115

The text importer does not handle cpufreq.
The text importer is maintained best-effort and has some missing features. Most traces are captured directly through `adb shell perfetto` in the new proto format.

That seems not too hard to fix. If you were willing to contribute we would happily accept a fix for that.
Essentially we need some code in `systrace_line_parser.cc` that does something similar to [`FtraceParser::ParseCpuFreq`](https://github.com/google/perfetto/blob/8d2a9ab275b5761104956281bf07a41f4ecb143a/src/trace_processor/importers/ftrace/ftrace_parser.cc#L631) (The latter is the proto-based parser).

See also https://perfetto.dev/docs/contributing/getting-started for contrib instructions.

**Comment by ankit-16** [comment]
Hello,

I am Beginner and I want to contribute. can you please guide me how i can reproduce this?

**Comment by LalitMaganti** [comment]
[Here's a link](https://drive.google.com/file/d/1Q1XGg1kRN0v8OA9emx7wNAj5d3qQo0-q/view?usp=sharing) to a systrace which contains cpu frequency events. To fix this issue, you basically need to follow what Primiano said in the comment above yours.

You can test if your change works by building `trace_processor_shell`and running:
`<out directory>/trace_processor_shell <path to trace>`

If you then write the query:
`select * from counter_track`
you should see some cpu_frequency tracks if it worked correctly.

Feel free to hop into our [Discord](https://discord.gg/Y79ZQXwyzZ) if you want more pointers without the latency of commenting back and forth on GitHub :)

**Comment by ankit-16** [comment]
ok thanks. I will try it now.

**Comment by LalitMaganti** [comment]
This has now been implemented
