### ISSUE TITLE
[UI] Minor UX regression with Tabs V2

### ISSUE THREAD

**Issue by cphlipot1** [google/perfetto#720]
New behavior has appeared when clicking and dragging over counter tracks that appears to be a minor regression UX. It used to display counter aggregations by default, but now shows an "area selection" pane without useful data. 

Flagging since this change in  default behavior seems like it may have been unintentional.

I believe this is a regression in UX because:
- Initial pane doesn't contain much in the way of useful info
- Accessing the counter aggregations requires an extra click
- Flow event aggregation isn't relevant for counter tracks

Some example screenshots of this behavior from the "Android example" from the UI.

Tabs V2 when clicking and dragging over a counter track (mem.rss in this case):
<img width="1416" alt="image" src="https://github.com/google/perfetto/assets/77857237/91fa72ba-cf43-4bc5-8881-762356f6a1a2">

Tabs V1 when clicking and dragging over the same counter track from the same trace:
<img width="1413" alt="image" src="https://github.com/google/perfetto/assets/77857237/f133861d-c420-4a15-a637-cf089445fda5">

**Comment by stevegolton** [comment]
Hi @cphlipot1,

Thanks for reporting this - you're absolutely right!

One of the big issues we're trying to tackle with tabsv2 is tab predictability. The tab strip traditionally contained both auto generated tabs based on selection, and user controlled tabs. The code & underlying state to handle this was messy, and the resulting tab that was shown to the user was mainly only correct by chance (if at all) rather than being strictly defined.

The underlying ethos of tabs v2 was to only change the open or active tabs via explicit user action. However, this model does't work well for the aggregation style tabs that are only relevant for certain selection types. The links in the current selection panel were a stop-gap, but ultimately didn't go far enough.

I landed a patch yesterday which hopefully addresses this issue, giving us the best of both worlds. This patch moves the aggregation panels inside the current selection tab under a new sub tab strip, replacing the somewhat pointless area selection panel. The tabs in this sub-tab strip are now entirely automatic like they used to be (appearing and disappearing with selection) saving clicks, while the main tab strip is still (mostly) controlled via direct user action.

This does come at the cost of consuming more vertical height which might be problematic for those on smaller screens, but I imagine this is only a temporary measure as we are planning on re-working how area selections and aggregations work in the near future anyway.

For example:
![image](https://github.com/google/perfetto/assets/6147146/bf40788b-ffaf-4f72-9ed8-6a51ba2e371c)

I'd love to hear any feedback you have about this new patch.

**Comment by stevegolton** [comment]
I'm going to mark this as closed for now. Feel free to re-open if you want to discuss further.

**Comment by cphlipot1** [comment]
@stevegolton  Hi sorry for the delay. Just took a look. the new version looks much better!

I think the biggest pain point before was the extra clicks needed to get to the counter aggregation, which now seems to be gone.
