### ISSUE TITLE
Error "col: 'name': SQL value is NULL but that was not expected"

### ISSUE THREAD

**Issue by facewindu** [google/perfetto#741]
I just had this in Perfetto UI.
It seems related to debug annotation added to some `TYPE_SLICE_END` track event.

If I remove those debug annotation it loads.
If I replace them with some static ones (eg "foo" -> "bar" on all my slice ends packets), it fails too.
It don't think my code is at blame.
Particularly, since some of those slices can be opened fine (the ones at the beginning of the trace), but at some point, all packets from a given point seem affected by the problem below.

```
UI: https://ui.perfetto.dev/v43.1-5457e2afa

PromiseRejection: Error: Error @ row: 1 col: 'name': SQL value is NULL but that was not expected (expected type: STR). Did you mean NUM_NULL, LONG_NULL, STR_NULL or BLOB_NULL?
Query:

    SELECT
      id,
      name,
      ts,
      dur,
      track_id as trackId,
      depth,
      parent_id as parentId,
      thread_dur as threadDur,
      thread_ts as threadTs,
      category,
      arg_set_id as argSetId,
      ABS_TIME_STR(ts) as absTime
    FROM slice
    WHERE id=8049
 - RowIteratorImpl.makeError (frontend_bundle.js:326924:18)
 - RowIteratorImpl.tryMoveToNextBatch (frontend_bundle.js:327063:30)
 - RowIteratorImpl.next (frontend_bundle.js:326951:25)
 - new RowIteratorImpl (frontend_bundle.js:326918:16)
 - RowIteratorImplWithRowData (frontend_bundle.js:327078:24)
 - QueryResultImpl.iter (frontend_bundle.js:326648:24)
 - getSliceFromConstraints (frontend_bundle.js:346646:23)
 - async getSlice (frontend_bundle.js:346688:21)
 - async ChromeSliceDetailsTab.load (frontend_bundle.js:353496:26)

Trace: not available (FILE). Provide repro steps.
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Referrer: 
```
[my.trace.zip](https://github.com/google/perfetto/files/14588329/my.trace.zip)

**Comment by LalitMaganti** [comment]
I cannot repro this with the trace you provided. It opens fine for me on both autopush and stable.

**Comment by facewindu** [comment]
sorry for not mentioning it, the problem is not that it doesn't open.
The error is thrown when clicking most of the slices like the ones around here
<img width="413" alt="image" src="https://github.com/google/perfetto/assets/5922961/326e4069-f623-4b9f-a5b6-f7a21d929a07">

**Comment by LalitMaganti** [comment]
Thanks for the additional info.

Actually the problem does appear to be in your trace: you can see that none of your slices have names and that is actually what is causing the UI crash. I'm not sure why this is only showing up when you specify debug annotations on end slices but not having slice names is sort of UB anyway meaning anything can happen.

The root cause of this appears to be that you are using interning but have not set the `SEQ_NEEDS_INCREMENTAL_STATE` flag on the packets which are using interned state. Please see our documentation on interning [here](https://perfetto.dev/docs/reference/synthetic-track-event#interning) to set the correct flags (note also the need to set `previous_packet_dropped` and `first_packet_on_sequence` on the packet which is emitting the interning state which is also missing in your trace).

Making your trace follow the guidance should fix the issue: if it still does not work then, please reopen the bug and provide the new trace. Thanks!

**Comment by facewindu** [comment]
cc @LalitMaganti (since the issue is closed and I cannot reopen it, I'm not sure you'll be notified about my message above)

**Comment by facewindu** [comment]
Thanks, that helped me figure out the problem in my interning strategy. All good
