### ISSUE TITLE
Perfetto progress bar never stops if I load files quickly

### ISSUE THREAD

**Issue by alecazam** [google/perfetto#744]
I have a single WKWebView, and I send over json data to Perfetto from Swift.  If I advance quickly through my files, then Perfetto starts displaying a progress bar that never stops.  This results in about 15% cpu use to update that progress bar.  But the file is completely loaded, and no progress should be shown. 

When I advance slowly through the list of files this progress bar doesn't appear.  It's the thin blue line seen here under the search text.

I'd like Perfetto to settle, so the app isn't using battery when the dev isn't interacting with it.  

<img width="706" alt="image" src="https://github.com/google/perfetto/assets/3750359/98c18e69-4d26-42f2-9399-e1ad7b375e00">

**Comment by primiano** [comment]
That is likely some race that happens if you load a file before another is loaded.
The PostMessage interface has never been desined to load more than a trace.
The fact that you can load >1 a trace is more an accident than a feature.

We are not intending to support that use case though (an in general any form of embedding Perfetto UI in other tools in an iframe or webview) .
If you need to  open > 1 trace, reload the UI instance and start again.
