### ISSUE TITLE
Add new fields for track_event DataSource

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#751]
I want to add new field(AAA) to track_event DataSource, I encountered two problems,

This field (`optional uint32 AAA = 10`) was added to the message of **TrackEventConfig** in three proto files (`perfetto_config.proto`, `track_event_config.proto`, `perfetto_trace.proto`).

The modified config is as follows: 

```
duration_ms: 10000

buffers {
  size_kb: 65536
  fill_policy: RING_BUFFER
}

data_sources {
  config {
    name: "track_event"
    target_buffer: 0
    track_event_config {
      AAA: 1
    }
  }
}
```

1. When using `system mode` to load this configuration, data can be collected normally. **But there is a problem with the display: The 10 here should be displayed as AAA, but it is its number in TrackEventConfig.**

![img_v3_029d_890247d0-64e3-4292-a62f-c6e80654121g](https://github.com/google/perfetto/assets/31888567/781080d2-a557-4205-8454-2974ac6e7a62)

2. When using `in-process mode` to collect data, an error occurs when loading the configuration:
 **error: No field named "AAA" in proto TrackEventConfig**，
![image](https://github.com/google/perfetto/assets/31888567/bcd5a45b-367b-415b-b295-368e18224ead)
![image](https://github.com/google/perfetto/assets/31888567/e784dc14-0085-415a-8100-112c3b393bd1)

Please tell me how to solve the above problem, thank you~

**Comment by primiano** [comment]
This seems all WAI. I mean, if you add a new field to DataSource, everything will work, but the UI will not, because it cannot possibly know about that part of the schema.

If you do schema modifications, you should pass binary-encoded protobufs to the `perfetto` cmdline client (i.e. WITHOUT `--txt` ) because they are passed through as-is. Also you can't just use the UI to generate a config for some schema it doesn't know about.

It's unclear what your expectation is here
