### ISSUE TITLE
Request: support Hide process 

### ISSUE THREAD

**Issue by nicefuture** [google/perfetto#770]
In legacy Systrace, there is one very important and useful feature, that is, can filter to only show selected Process in the Page. when huge process be there, this feature is very useful that the whole page is very limited and we'd like to just show the selected/focused process

But seems perfetto did not support this feature, thus the whole page is very messy. So we request to have this feature.

**Comment by primiano** [comment]
In perfetto you can pin a track to the top. Which seems to cover this case.

> So we request to have this feature.

This is not how open source works. If you want to have features either:
1. Make a case why something is so important that would benefit most people
2. Make a proposal for contribution and do it yourself (https://perfetto.dev/docs/contributing/getting-started)

You did neither here.

**Comment by saagarjha** [comment]
Unfortunately the pinning feature does not support flows (the arrow things) as they only show up in the unpinned tracks area. This means we've taken to prefiltering the trace before we load it into Perfetto, which we obviously don't want to do. So I guess that's another reason why this would be helpful?

**Comment by stevegolton** [comment]
Flows work between two pinned tracks, or two unpinned tracks but not between a pinned and an unpinned track. Unfortunately this is technically quite difficult because the pinned and unpinned areas are rendered on different canvases. It might be something we support in the future but it's not really on our radar at the moment.

Workspaces might be able to help here. They're a relatively new feature which allows you to copy certain tracks over to a new track list, and organize them how you like using drag & drop. Beware there are still some teething issues and bugs as this is still quite a new feature.

![Image](https://github.com/user-attachments/assets/3c8afccd-8621-4cd1-8c3a-404dcfb17598)

If you want to write a [plugin](https://perfetto.dev/docs/contributing/ui-plugins), you can even automate this process for your specific use case [example](https://github.com/google/perfetto/blob/main/ui/src/plugins/dev.perfetto.SysUIWorkspace/index.ts)

Basic track filtering does now exist, allowing filtering tracks by name, which can help to limit what's showing, though this is fairly limited in terms of it's functionality.

![Image](https://github.com/user-attachments/assets/bd0171eb-e2b3-4f0f-b7b0-d096e01bebdc)

We are planning on adding advanced filter criteria, such as filtering by process and thread name. I'm not sure I can commit to a time scale, but this is coming soon.
