### ISSUE TITLE
How to disable tracing when not needed?

### ISSUE THREAD

**Issue by nikitanodar** [google/perfetto#774]
I want to profile my application only for certain builds while disabling it for anything else. Looking at the code I can't see any definitions that allow to turn the tracing off during the compilation. Sure, I can exclude all categories from the tracing, but that's not the same as disabling it completely, leaving only empty noop macroses.

**Comment by LalitMaganti** [comment]
The overhead of tracing macros when tracing is disabled is very very close to zero so we've not invested in build time support for stripping the macros. Also because of the very diverse range of ways in which Perfetto can be used, there's no likely to be a one size fits all approach to how people want to do stripping.

The suggestion would probably be wrap the macros from Perfetto to integrate with your own build system to ifdef the macros.
