### ISSUE TITLE
Cannot write track events with custom datasource

### ISSUE THREAD

**Issue by gammapibd** [google/perfetto#784]
```
               CustomDataSource::Trace([](CustomDataSource::TraceContext ctx) {
                   auto packet = ctx.NewTracePacket();
                   packet->set_timestamp(42);
                   packet->set_for_testing()->set_str("Hello world!");
               });

                
                CustomDataSource::Trace([](CustomDataSource::TraceContext ctx) {
                    auto packet = ctx.NewTracePacket();
                    packet->set_timestamp(43);
                    auto trackEvent = packet->set_track_event();
                    packet->set_trusted_packet_sequence_id(23);
                    auto* event = packet->set_track_event();
                    event->add_categories("cat");
                    event->set_name("ev1");
                    event->set_type(perfetto::protos::pbzero::TrackEvent::TYPE_INSTANT);
                });
```

I can see a bunch of in the protobuffer result, but there are no packet with "timestamp: 43". If I remove packet->set_track_event(), I can see "timestamp: 43" in the result.
```
packet {
  first_packet_on_sequence: true
  timestamp: 42
  for_testing {
    str: "Hello world!"
  }
  trusted_uid: 0
  trusted_packet_sequence_id: 2
  trusted_pid: 0
  previous_packet_dropped: true
}
```

Why is this the case? How can I record data correctly as mentioned in https://perfetto.dev/docs/reference/synthetic-track-event ?

**Comment by LalitMaganti** [comment]
If you are emitting track_event using the SDK, is there a reason why you are trying to write the packets manually instead of using the track_event macros (https://perfetto.dev/docs/instrumentation/track-events)? The synthetic track_event page was designed for folks specifically *not* using the SDK i.e. they have some other trace format they want to convert to Perfetto to visualise it in the UI or query with trace processor. If you're already using the SDK, there is little need to look at that page at all.

**Comment by LalitMaganti** [comment]
To answer your actual question though, the problem is the line `auto trackEvent = packet->set_track_event();`. Protozero 
(the proto library that Perfetto uses) expects that the fields of a sub-message are all written contiguously. Given that you call set_track_event twice, that causes undefined behaviour. The trusted_packet_sequence_id also should *not* be written if you are using the SDK: again that's only designed if you are writing track_event without using the SDK.

Your code should work if you do something like this:
```
                CustomDataSource::Trace([](CustomDataSource::TraceContext ctx) {
                    auto packet = ctx.NewTracePacket();
                    packet->set_timestamp(43);
                    auto* event = packet->set_track_event();
                    event->add_categories("cat");
                    event->set_name("ev1");
                    event->set_type(perfetto::protos::pbzero::TrackEvent::TYPE_INSTANT);
                });
```

**Comment by gammapibd** [comment]
> If you are emitting track_event using the SDK, is there a reason why you are trying to write the packets manually instead of using the track_event macros (https://perfetto.dev/docs/instrumentation/track-events)? The synthetic track_event page was designed for folks specifically _not_ using the SDK i.e. they have some other trace format they want to convert to Perfetto to visualise it in the UI or query with trace processor. If you're already using the SDK, there is little need to look at that page at all.

I'm trying to:
1. Record trace information lazily at a certain time rather
2. Display not perfectly nested data. According to [ref](https://perfetto.dev/docs/faq#why-are-overlapping-events-in-json-traces-not-displayed-correctly-) "Users are recommended to emit [TrackEvent](https://perfetto.dev/docs/instrumentation/track-events) instead"

**Comment by LalitMaganti** [comment]
It's still not clear to me if you have the following case:
1) you have a C++ program (library, binary whatever) you are trying to instrument to collect tracing information while the system runs
2) if you have some already existing data source you are trying to visualize in the UI without having a live tracing system

The "Synthetic Track Event" page is only appropriate for case 2). For case 1) you should be using the track_event macros in the SDK as described in https://perfetto.dev/docs/instrumentation/track-events. For case 2), you don't need (and shouldn't) use the SDK at all, you can just use any protobuf writing library (e.g. the official library) and just write protos directly. I explained how to do this a few days ago for Python, the instructions for C++ are very similar: https://github.com/google/perfetto/issues/779.
