### ISSUE TITLE
tracing_muxer_impl.cc calls deprecated version of std::atomic_store

### ISSUE THREAD

**Issue by nico** [google/perfetto#785]
After https://github.com/llvm/llvm-project/pull/87111:

```
[19090/49406] CXX clang_x64/obj/third_party/perfetto/src/tracing/client_api_without_backends/tracing_muxer_impl.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF clang_x64/obj/third_party/perfetto...(too long)
../../third_party/perfetto/src/tracing/internal/tracing_muxer_impl.cc:205:8: error: 'atomic_store<perfetto::ProducerEndpoint>' is deprecated [-Werror,-Wdeprecated-declarations]
  205 |   std::atomic_store(&service_, std::move(service));
      |        ^
../../third_party/libc++/src/include/__memory/shared_ptr.h:1606:1: note: 'atomic_store<perfetto::ProducerEndpoint>' has been explicitly marked deprecated here
```

Upstream chromium bug: https://issues.chromium.org/issues/333609032

**Comment by primiano** [comment]
@ddiproietto IIUC https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic std::atomic_load/store on a shared_ptr is being deprecated.

My understanding of the code in tracing_muxer_impl is the following:
- At some point we might swap the service_ instance, on reconnection
- service_ itself is thread-safe (we use it to call NewTraceWriter) 
- the std::shared_ptr control block itself is thread safe (once you obtain a shared_ptr, the target object is guaranteed to be alive)
- The real problem that the atomic_load/store is solving here, is the fact that the shared_ptr itself (the thing that points to the control block) is not thread-safe, so when we swap it to point to another control block , that operation itself needs to be atomic

The obvious solution suggested by [p2869r2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2869r2.pdf) is to use instead `std::atomic<std::shared_ptr<X>>`. However that's supported only in C++20 (where the deprecation starts)

As a matter of pragmatism, I'm quite convinced we could easily add a dedicate mutex just around service_, and that doesn't bother me at all because that mutex will be uncontended 99% of the times (it would be taken only upon loss of socket connection) and an uncontended mutex is an atomic increment/decrement on civilized operating systems.

@nico just to understand a bit more the situation (which I couldn't figure from the attached bug)
- The deprecation seems to have effect only since c++20, but I thought that chromium is still on c++17 (or do you have a bot using c++20)?
- Is there anything we can do to spot these errors earlier? We try to stay up-to-date with chromium's llvm and libcxx (~ realistically we are 3-6 months behind) and build with -Weverything. Any chance I can catch these things sooner so they don't block you?

**Comment by nico** [comment]
Chromium is on c++20 these days.

**Comment by nico** [comment]
For catching it earlier: I noticed it today when trying to roll libc++. I suppose you could try autorolling it. It's been a pain to keep updated this year though: We _just_ managed to land the update to libc++-HEAD-as-of-5-weeks-ago. That's also why we haven't noticed this earlier, even though it changed upstream a few weeks ago.

**Comment by nico** [comment]
> Technically speaking from my viewpoint we seem to be hit by something that is deprecated in C++20, but we can't use c++20 yet :)

The mutex thing you propose sounds good, but `#if __cplusplus >= 202002L /* new thing */ #else /* old thing */ #endif` is also something that exists.

**Comment by primiano** [comment]
> The mutex thing you propose sounds good, but #if __cplusplus >= 202002L /* new thing */ #else /* old thing */ #endif is also something that exists.

Actually @ddiproietto suggested the same and pointed out that my mutex solution is unideal because adds contention across different threads calling CreateTraceWriter(). Another possible solution would be using a rw-mutex but then he told me it's std::shared_mutex seems discouraged because very expensive.

So i'm now looking at this other option. How hard can it be? r.android.com/3088448

However that doesn't build in our repo if I switch to C++20 because now it complains about std::atomic<std::shared_ptr<T>> claiming that shared_ptr is not trivially-copyable.

I think what's happening is that our version of libcxx is too old and back then shared_ptr was not yet trivially-copyable.

So now I have to first figure out a way to upgrade our libcxx to chromium latest, and then try again.

Bear with me !

**Comment by nico** [comment]
🧸

**Comment by primiano** [comment]
Update: I tried up-revving libcxx to 7e7c1619d84230c43f5c25b1ad4e0ade25477cb7  and applying https://r.android.com/3088448 and this fails.
Feels like the [suggested replacement](https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic2) is not supported yet by libcxx.
I have a minified repro here: https://godbolt.org/z/nYjh3P4aG (here's what I'm trying to do in perfetto: https://pastebin.com/raw/0g4BZAbK)

So if we target C++20 && libc++ we can't use std::shared_ptr::atomic_load/store anymore because it's deprecated, and we can't use the new std::atomic<std::shared_ptr> because it's not there yet

**Comment by nico** [comment]
I brought this up at https://github.com/llvm/llvm-project/pull/87111#issuecomment-2112740039 , let's see what upstream says.

**Comment by nico** [comment]
The deprecation got reverted for now: https://github.com/llvm/llvm-project/pull/92920

So no action needed. It will be back eventually, and then we'll have to check for `__cpp_lib_atomic_shared_ptr` and do something conditional probably. But currently, that's not yet implemented in libc++ (hence the revert).

**Comment by LalitMaganti** [comment]
I'll close this out for now in that case and we can reopen this/create a new bug when libc++ is ready. Thanks Nico!
