### ISSUE TITLE
traced_probes crash

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#787]
The running command is: `traced_probes --reset-ftrace --background`, `perfetto --txt -c test.cfg -o test.trace`. `duration_ms=0` in `test.cfg` file.

There is a low probability of the following error reporting, please tell me how to further determine the problem and how to solve it. Thanks~
![image](https://github.com/google/perfetto/assets/31888567/03c924af-b708-4233-8f91-14e82ec88370)

**Comment by LalitMaganti** [comment]
As it stands, this bug is very unactionable as that stack trace does not actually provide any information. Usually when Perfetto exits, it also prints some error message: that is what you need.

Also is there a reason when you are explicitly trying to run those commands instead of using tracebox if you are trying to sideload Perfetto? Tha would be a munch simpler way to achieve what you want.

**Comment by duokuiwang** [comment]
`traced_probes --reset-ftrace --background` Can this process run for a long time? Is there a specific running time threshold?

**Comment by ddiproietto** [comment]
> `traced_probes --reset-ftrace --background`. Can this process run for a long time? Is there a specific running time threshold?

There's no specific time threshold, it should be able to keep running indefinitely.

Your crash contains `base::Watchdog::SerializeLogsAndKillThread()`. This means that the process itself decided to terminate because the watchdog determined that the process is in a bad state (it is using too many resources, or it's been blocked for a long time).

* There's a watchdog configured for memory: https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/traced/probes/probes.cc;l=98;drc=ec27380d313815abb6359dcbdbbe444ef11bb288
* There's a watchdog configured for CPU https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/traced/probes/probes.cc;l=100;bpv=1;bpt=1
* There's a very conservative watchdog for tracing sessions with a timeout, if they don't terminate (https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/traced/probes/probes_producer.cc;l=435;drc=41658e0e867c8cf330febf37084164441f02e06e).
* If an async task takes more than 30 seconds, the watchdog will consider the process stuck (https://source.corp.google.com/h/googleplex-android/platform/superproject/main/+/main:external/perfetto/include/perfetto/ext/base/watchdog.h;l=60;drc=216c4482a09936a4366e5058bed4c5608b2ddd26).

If you look at the logs, you should see a `wdog_reason: ` number (it should match https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/include/perfetto/ext/base/watchdog.h;l=36;drc=41658e0e867c8cf330febf37084164441f02e06e). It will tell you which one of these watchdogs is complaining.
