### ISSUE TITLE
How to quickly locate a ftrace slice on the timeline based on the start timestamp

### ISSUE THREAD

**Issue by duokuiwang** [google/perfetto#798]
**Only the ftrace event data is captured**, and the status information of the thread at different times can be obtained.
The ftrace slice information can be queried through SQL, but it cannot be quickly located on the timeline interface.

How to quickly locate a large number of slices in thread_state based on the start timestamp, as shown in the figure below to select the state of the slice？
![image](https://github.com/google/perfetto/assets/31888567/d8c47ca1-0447-486d-9c90-ea1890fd5642)

**Comment by LalitMaganti** [comment]
Couple of ways:
1) For one off things, you can use the "Pan to Timestamp" command and paste in the timestamp of the slices to navigate to
2) The better solution for more slices is instead to create a debug track (https://perfetto.dev/docs/analysis/debug-tracks) to visualize all the information you want on a single track so you can easily navigate that single track rather than constantly switching between tracks and query results.
