### ISSUE TITLE
How to cut a large perfetto trace to some small file

### ISSUE THREAD

**Issue by tingfengwanxiao** [google/perfetto#800]
Hello,How to use trace_processor_shell to cut a large perfetto trace (for wexample 10G) to some small file ?

**Comment by hanbim520** [comment]
Due to the large size of the trace file, using the --httpd method to display it in the Perfetto UI is very slow. When selecting a range or an event, the query response is extremely slow. I suspect this is due to the slow performance of SQLite queries. Additionally, updating the web interface is also very slow, and sometimes it doesn't return results at all.

**Comment by hanbim520** [comment]
Given this issue, my current consideration is to record for a certain period, then stop, and start a new recording to continue.

**Comment by LalitMaganti** [comment]
> Additionally, updating the web interface is also very slow, and sometimes it doesn't return results at all.

Can you check if this happens only if you have a search open or all the time? There's a KI where having a search slows everything else down. 

> When selecting a range or an event, the query response is extremely slow

I'd rather spend engineering time fixing these issues than making splitting/merging work properly :)

**Comment by hanbim520** [comment]
Sure, once I finish the work at hand, I'll come back to analyze this issue. There's a time difference of about 6 hours between us, so my responses might be a bit slow.
