### ISSUE TITLE
Perfetto UI - An unrecoverable problem occurred

### ISSUE THREAD

**Issue by icebuf** [google/perfetto#817]
Blue website like this:
Perfetto UI - An unrecoverable problem occurred

If you are seeing this message, something went wrong while loading the UI.
Please file a bug (details below) and try these remediation steps:

* Force-reload the page with Ctrl+Shift+R (Mac: Meta+Shift+R) or
  Shift + click on the refresh button.

* [Clear all the site storage and caches](javascript:clearAllCaches();) and reload the page.

* Clear the site data and caches from devtools, following [these instructions](https://developers.google.com/web/tools/chrome-devtools/storage/cache#deletecache).

In any case, **FILE A BUG** attaching logs and screenshots from devtools.
  Googlers:      [go/perfetto-ui-bug](http://go/perfetto-ui-bug)
  Non-googlers:  [github.com/google/perfetto/issues/new](https://github.com/google/perfetto/issues/new)

Uncaught TypeError: chrome.runtime.connect is not a function

Technical Information:
LocalStorage: {"loglevel":"ERROR","recordConfigs":"[]"}

I clear chorme cache and caches from devtools but not useful.

**Comment by primiano** [comment]
This feels like a network error, maybe your network is too slow. Can you reproduce consistently?

**Comment by icebuf** [comment]
Yes, it reproduce whole day.

**Comment by icebuf** [comment]
finally I can open it with Edge. Maybe my chorme has some problem.

**Comment by primiano** [comment]
I asked for devtools, not the version.
This bug is unactionable without seing a log from devtools. Refer to https://balsamiq.com/support/faqs/browserconsole/#:~:text=Google%20Chrome&text=You%20can%20also%20use%20Option,to%20select%20the%20Console%20tab.

Reopen the bug if you have a screenshot of devtools when the issues reproduces.

Very likely it's some chrome extension you have that is messing around with it.

**Comment by icebuf** [comment]
As you said, a extension plugin was affecting Perfetto. I can open Perfetto now when I disabled the plugin. Thanks for your support!
