### ISSUE TITLE
RuntimeError: memory access out of bounds 

### ISSUE THREAD

**Issue by liyixun** [google/perfetto#83]
### Description
I open a protobuf trace file in perfetto ui, but get an error message like this. Is there something wrong in my pb file?Is it clock_tracker's problem？  
![image](https://user-images.githubusercontent.com/14371773/102053978-9cc70c00-3e23-11eb-86ef-ce35b073eaf5.png) 

### Steps
1.open [perfetto ui](https://ui.perfetto.dev/#!/viewer) 
2.download and unzip this file [data.result.zip](https://github.com/google/perfetto/files/5687330/data.result.zip)
3.open this unzip file in perfetto ui

**Comment by primiano** [comment]
The elog is a red herrning (We should suppress it if the main clock doesn't change).
Not sure how you ended up in a situation where you have multiple snapshots, but I think that's not really the issue.
I tried this on ToT, here's the deal

1. On trace_processor_shell it works but it inflates to 54 MB. @LalitMaganti not sure how a 54MB trace becomes 1 GB, might be worth looking into what's happening here.

2. The ui is really faililng because of OOMs. On ToT debug build I get lots of:
`Cannot enlarge memory, asked to go up to 2147422208 bytes, but the limit is 2147418112 bytes!`

Which is probably why @liyixun here is eventually hitting that out-of-bounds.

**Comment by liyixun** [comment]
> The elog is a red herrning (We should suppress it if the main clock doesn't change).
> Not sure how you ended up in a situation where you have multiple snapshots, but I think that's not really the issue.
> I tried this on ToT, here's the deal
> 
> 1. On trace_processor_shell it works but it inflates to 54 MB. @LalitMaganti not sure how a 54MB trace becomes 1 GB, might be worth looking into what's happening here.
> 2. The ui is really faililng because of OOMs. On ToT debug build I get lots of:
>    `Cannot enlarge memory, asked to go up to 2147422208 bytes, but the limit is 2147418112 bytes!`
> 
> Which is probably why @liyixun here is eventually hitting that out-of-bounds.

what does ToT mean @primiano

**Comment by LalitMaganti** [comment]
ToT means Tip of Tre - i.e. the latest commit on master.

I'll be on vacation from tomorrow onwards so I probably won't have time to get to this before the holidays but I'll definitely look into this when I get back

**Comment by LalitMaganti** [comment]
Back from vacation so will be looking at this in the the next week or so when I recover from emails, code reviews etc.

**Comment by LalitMaganti** [comment]
@fmayer this seems to be caused by a blow up in memory because of heap profling tables/trackers. Can we discuss this tomorrow to figure out what the best path forward on this is?

**Comment by LalitMaganti** [comment]
The above commit should have fixed this issue :)

**Comment by fmayer** [comment]
This will be fixed once the UI is rolled out. There is still another issue with this trace that shows an error (because the last snapshot is truncated). You can click that away and still use the UI, though.
