### ISSUE TITLE
[help] perfetto ui cannot display the track written by two source

### ISSUE THREAD

**Issue by csmoe** [google/perfetto#831]
Sorry for bothering you here.

I'm trying to write the trace data from two processes into one perfetto protobuf binary file using the trace_perfetto.proto without the perfetto sdk, but the track events were missing in the ui.
```js
let trace = vector_of_trace_packets;
let buf = trace.encode_proto(trace);
await file.write_all(buf);
```
<img width="1436" alt="image" src="https://github.com/google/perfetto/assets/35686186/6c750842-2cb9-4ac9-9be9-9347774a14b7">

here is the pb txt format convert by `traceconv text` from `test.pftrace`

[test.txt](https://github.com/user-attachments/files/15925690/test.txt)

I only have one trace write module for the whole program, which has a channel and will write all the packets it receives to one file, no matter where or when a packet comes from. Does it make sense? Or a process or thread must use a separate write channel, and the data should be written to different files.

**Comment by LalitMaganti** [comment]
Can you please link the raw trace file?

**Comment by csmoe** [comment]
[test.pftrace.zip](https://github.com/user-attachments/files/15925933/test.pftrace.zip)

**Comment by LalitMaganti** [comment]
The data is in the UI just fine:
![image](https://github.com/google/perfetto/assets/679100/f5ea8cd6-09f4-41ee-bb76-17de21413667)
![image](https://github.com/google/perfetto/assets/679100/c0c13fdd-9d52-40b2-9c05-e5ad376775cb)

The problem is that two tracks have timestamps differing by multiple orders of magnitude: one track has timestamps like 1718953878695000000 and other has timestamps like 774738000. Seems like there is some bug in your proto writing code :)
