### ISSUE TITLE
ZIPs created by GitHub Actions are not supported

### ISSUE THREAD

**Issue by zero9178** [google/perfetto#840]
Error displayed by the UI:
```
UI: https://ui.perfetto.dev/v45.0-f256f01ae

Unsupported zip features at offset 0x0. version=14, flags=8

Trace: not available (FILE). Provide repro steps.
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Referrer: 
```

We have a GitHub actions which performs a longer running benchmark (using a simulator) from which we then get a trace (currently in the legacy chrome tracing format, aka a JSON). This is then uploaded using `upload-artifact@4.3.3`.
Even if specifying just a file to upload, GitHub will wrap the whole artifact as a ZIP.

When wanting to inspect the traces I'd be convenient to simply be able to open the ZIP file and visualize the trace rather than needing to manually unzip after the download and opening the contained JSON file. 
Looking at the error and the perfetto source code it seems as though this use-case is supposed to work but it seems as if the version of the ZIP library used is not able to deal with ZIPs created by GitHub actions. 
Given that GitHub actions is a popular CI framework it'd probably be nice to be able to deal with its ZIP files as well.

For testing purposes I have attached such a ZIP file. To reproduce simply download, click on "Open trace file" and select the `zip` file itself. 
[Perfetto traces (1).zip](https://github.com/user-attachments/files/16116466/Perfetto.traces.1.zip)

**Comment by LalitMaganti** [comment]
ZIP file support was added relatively recently so it's possible that we are being a bit too strict. 

I took a quick look at disabling this check and then ran into some signature issues. Might take a look at this as it seems an interesting problem.

**Comment by primiano** [comment]
I think this has to do with the "data descriptor"

From wikipedia
***If the bit at offset 3 (0x08) of the general-purpose flags field is set, then the CRC-32 and file sizes are not known when the header is written.***


From https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html :+1: 

The data descriptor is only present if bit 3 of the bit flag field is set. In this case, the CRC-32, compressed size, and uncompressed size fields in the local header are set to zero. The data descriptor field is byte aligned and immediately follows the file data. 


So I think in some cases of streaming creation, the file size and CRC are appended after the payload, rather than being present in the header. I think it's not too hard to support.

**Comment by LalitMaganti** [comment]
Yes that's precisely what it is, I already have a patch 95% done for this.

**Comment by primiano** [comment]
hmm okay this is a bit trickier than what I thought. The issue is that this requires the central directory. You cannot use the file entry (Which I believe it's the only thing that we use today) because in those entries the compressed-size is 0, so you can't know where how big the file payload is, and hence cannot know where the data descriptor starts

**Comment by LalitMaganti** [comment]
> because in those entries the compressed-size is 0, so you can't know where how big the file payload is, and hence cannot know where the data descriptor starts

Yes however, the deflate stream is self-terminating so you can just inflate that to know what the end of the stream is. 

Alternatively, most real ZIP implementations emit a signature of 0x08074b50 before the data descriptor as well so you can search for that: https://github.com/madler/sunzip/blob/master/sunzip.c#L1436C32-L1436C44

**Comment by LalitMaganti** [comment]
https://r.android.com/3162596 fixes this.
