### ISSUE TITLE
Can't move timeline of perfetto visualization when mouse click and drag 

### ISSUE THREAD

**Issue by Kyson** [google/perfetto#85]
I need to hold on shift and drag.

But i think dragging is a more common operation for moving timeline

**Comment by LalitMaganti** [comment]
Thanks for filing!

Originally, the UI was indeed designed the way you suggest with mouse click and drag moving the timeline. Over time, we realised that most of our users are very used to the old chrome://tracing UI which has the current behaviour but also supports WASD keyboard navigation.

Since we don't really intend to change this behaviour I will close this issue but I'd strongly suggest using WASD for navigation instead of using the mouse as it's a lot nicer experience :)
