### ISSUE TITLE
Perfetto UI can't show TRACE_EVENTS in kernel

### ISSUE THREAD

**Issue by jig-qcom** [google/perfetto#856]
after I got xxx.perfetto, I open it in Pefetto UI, but can't see the tracepoints I added in kernel, but when I transform it into xxx.systrace, and can see it in the file. something like this:
function1 can't show in UI, but funtion2 can show.

       xxxx  ( 7363) [001] .... 2832.825592: func:B|7363|function1   
       xxxx  ( 7363) [001] .... 2832.825592: func:E|7363|function1

       xxxx  ( 7363) [001] .... 2832.825592: func:B|7363|function2  
       xxxx  ( 7363) [001] .... 2832.825592: func:E|7363|

 function1 is got in kernel code,  I defined a TRACE_EVENT with 3 args, (pid, function_name, is)

#include <linux/tracepoints.h>
TRACE_EVENT(func,
	TP_PROTO(int pid, const char *name, bool isbegin),
         ....
	TP_printk("%s|%d|%s", isbegin ? "B" : "E",
		pid,  name)
)
#define K_TRACE_END(name) trace_func(pid, name, 0)
#define K_TRACE_BEGIN(name) trace_func(pid, name, 1)

how to use it:
K_TRACE_BEGIN("function1");
function1();
K_TRACE_END("function1");

and function2 is got in user space with atrace_begin/end
atrace_begin("function2");
function2();
atrace_end();

I can see both user space and kernel space trace  open with the lagecy UI, when I use systrace script to ctach trace.
but why perfetto can't ?

**Comment by LalitMaganti** [comment]
This is working as intended from the Perfetto side. The first thing to note is that, for performance reasons, Perfetto does *not* look at the "stringified" version of ftrace events. It is instead reading the binary structs which is a lot more efficient. This explains why you are getting a discrepancy between systrace and Perfetto.

On the Perfetto side, what is happening here is a subtle mix of a couple of things:
1) For ftrace events we don't know, we encode them as "generic" events on device: these are JSON like key-value pairs.
2) For generic events, we don't do any special handling when we process the trace (e.g. in the UI) so you won't see any slices generated from them.

There's a couple of ways to proceed
1) Instead of writing a new ftrace event, you can piggy back on writing to /sys/kernel/tracing/trace_marker (I think `trace_printk` might be the canonical way to do that from the kernel) which is what atrace does.
2) You can add upstream support for your new tracing event into Perfetto similar to what Samsung did for their "atrace-like" ftrace event in https://r.android.com/2692206 and https://r.android.com/2727564

**Comment by LalitMaganti** [comment]
OK I found some context from a bug where we were talking to another OEM. The canonical way we recommend is as to change your K_TRACE_BEGIN macro to:
```
    char buf[128];
    snprintf(buf, 128, "B|%d|%s\n", current->tgid, name);
    trace_printk(buf);
```

and `K_TRACE_END` macro to:
```
    char buf[128];
    snprintf(buf, 128, "E|%d\n", current->tgid);
    trace_printk(buf);
```

Then if you enable the `ftrace/print` event in Perfetto, everything should just work.

**Comment by LalitMaganti** [comment]
Not sure what you mean by your message: please clarify how exactly how you are collecting your traces, what you are expecting to see and what you're seeing instead.

**Comment by jig-qcom** [comment]
I know my problem.
just want to confirm one thing.

cmd1: python2 systrace.py -b 10960 sched view idle freq power irq -o "test_trace.html"  

In my test, catching trace using systrace script can parse below prints, and show in Pefetto UI
   xxxx  ( 7363) [001] .... 2832.825592: func:B|7363|function1   
   xxxx  ( 7363) [001] .... 2832.825592: func:E|7363|function1
but can't parse below for traces from kernel (with trace_printk)
   xxxx  ( 7363) [001] .... 2832.825592: func:B|7363|function2  
   xxxx  ( 7363) [001] .... 2832.825592: func:E|7363|

cmd2 : python record_android_trace  -t 10s -b 10960 sched view idle freq power irq  ftrace/print -o test.perfetto-trace

but catching trace with perfetto script is the opposite, can't parse the first pair of  print, but can parse the 2nd pair and show in UI.

Is the differece designed to be like this ?

**Comment by jig-qcom** [comment]
with same code, 
catch trace with systrace script: the contents in xx.html is like this :

      xxx    (   8132) [003] .....  3019.817127: func1: B|8132|func1
      xxx    (   8132) [003] .....  3019.817127: func1: E|8132

while catch trace with perfetto script, convert into .systrace,  the contents is like this:

       xxx  ( 7878) [001] .... 2732.264747: tracing_mark_write: B|7878|func1
       xxx  ( 7878) [002] .... 2732.265127: tracing_mark_write: E|7878

**Comment by LalitMaganti** [comment]
> Is the differece designed to be like this ?

Yes this is an intentional difference, see below.

> it's weird, why using systrace script, the contents before B becomes func1 instead tracing_mark_write ?

That's how trace_printk works in the kernel. The difference between Perfetto and systrace.py again comes from the fact that Perfetto reads the binary ftrace pipe for performance reasons while systrace reads the text pipe. The text makes trace_printk messages use the name of the kernel function as the name in the textual ftrace.

Another OEM used the following trick to have this consistent between Perfetto and systrace.py:
```
static noinline int tracing_mark_write(bool begin, const char *name)
{
	if (begin) {
            char buf[128];
            snprintf(buf, 128, "B|%d|%s\n", current->tgid, name);
            trace_printk(buf);
        } else {
            char buf[128];
            snprintf(buf, 128, "E|%d\n", current->tgid);
            trace_printk(buf);
        }
	return 0;
}

#define K_TRACE_BEGIN(name) tracing_mark_write(1, name)

#define K_TRACE_END() tracing_mark_write(0, 0)
```

Because the function calling the `trace_printk` function is called `tracing_mark_write`, that causes both systrace.py and Perfetto to be consistent with each other.
