### ISSUE TITLE
Support mutiple debug_slices from perfetto UI

### ISSUE THREAD

**Issue by dionysus1016** [google/perfetto#86]
debug_slices is great, is it possible to support mutiple debug_slices that I can create different views and insert them into different debug_slices and view them together. So far I can work around by opening logs in different chrome page and create different view by chrome page.

**Comment by primiano** [comment]
I am not 100% sure I understand the request (maybe @LalitMaganti does). 
@dionysus1016 can you expand?

**Comment by dionysus1016** [comment]
Sure, as told in https://perfetto.dev/docs/visualization/perfetto-ui, there is a debug_slices table, I can query any data into this debug_slices table, e.g., I can query out some key events into the debug_slices and show these key events as a seperate track from perfetto UI. It seems so far these is only debug_slices table, I am wondering whether there could be several debug_slices tables which I can query different events into different table and show them in different tack.

**Comment by LalitMaganti** [comment]
debug_slices is really intended for for dynamic prototyping of a new metric or track in the UI. It's not intended as a "permanent" track which shows up for traces and so I don't think we would want to support multiple tracks on this table. @deepanjanroy to confirm what I said here is correct

I think what you actually want are derived events - these are tables created by metrics which *also* show up in the UI - see https://perfetto.dev/docs/analysis/trace-processor#creating-derived-events for information on that.

Closing this issue as I don't think there's any work to be done on our side here but feel free to comment/reopen if you feel otherwise!

**Comment by deepanjanroy** [comment]
Yup that sounds right - we're not currently planning to support multiple
debug tracks. As a workaround, you can use the depth column to put slices
in different rows in the same track.

**Comment by dionysus1016** [comment]
Thanks!
