### ISSUE TITLE
Issue with Clock Domain Conversion in Perfetto UI for Custom Clock IDs

### ISSUE THREAD

**Issue by wangjiyang** [google/perfetto#877]
I am writing to report a potential issue observed in the Perfetto UI when handling trace data with custom clock IDs, particularly when these IDs are associated with the REALTIME clock. I have noticed an anomaly in how timestamps are managed and displayed, especially in the presence of other trace producers like ftrace that also utilize the REALTIME clock. This seems not working as expected as described in https://perfetto.dev/docs/concepts/clock-sync#operation.

Issue Description: When importing trace data where a custom clock ID (e.g., ID 65) is used and associated with the REALTIME clock, the Trace Processor attempts to convert timestamps to the CLOCK_BOOTTIME domain using the nearest neighbor approximation from ClockSnapshot packets. This conversion sometimes results in negative boottime calculations for traces captured under this custom clock ID, which leads to incorrect ordering of the events in the Perfetto UI. This may happen when android system is rebooted, however, some subsystem inside SoC is still running.

For instance, if there is a  packet under the custom clock ID with timestamp  which is logically earlier than ftrace event with a REALTIME timestamp , the UI incorrectly shows this packet as happening after the ftrace event. I guess this is due to the negative boottime(which is overflowed) offset being applied to the custom clock ID during the conversion process.

Could you look into this issue and give me some feedback?
Thanks

**Comment by LalitMaganti** [comment]
I'd argue that this issue is largely WAI from the point of view UI/trace processor. If you are emitting events such that the timestamp would be negative after conversion to BOOTIME then you are hitting undefined behaviour in the trace processor: timestamps are *never* allowed to be negative.

> This seems not working as expected as described in https://perfetto.dev/docs/concepts/clock-sync#operation.

Nothing about what you say indicates to me that things are not working as described there: the problem comes exactly from the negative timestamps which have never been supported, even when that doc was written.

> This may happen when android system is rebooted, however, some subsystem inside SoC is still running.

I'd argue that this is your real problem: if your trace spans events from before the start of boottime, then you're going to hit UB no matter what you do. Could you not filter out these events which are being emitted before device boot?

>  especially in the presence of other trace producers like ftrace that also utilize the REALTIME clock.

ftrace should not be using realtime, it should be using boottime.

> Issue Description: When importing trace data where a custom clock ID (e.g., ID 65) is used and associated with the REALTIME clock

Slight aside: it's not clear to me why you are complicating things by creating a custom clock when you could be emitting events using the builtin realtime clock? (ID 1 in https://perfetto.dev/docs/reference/trace-packet-proto#BuiltinClock)

**Comment by LalitMaganti** [comment]
If you wanted to (and you were sure that REALTIME would not go backwards during your trace), you can use the `primary_trace_clock` field in the trace config (see https://perfetto.dev/docs/reference/trace-config-proto#TraceConfig.BuiltinDataSource) to set the primary clock to realtime. That would make it possible to visualize your "events emitted before device boot" at the same time as other events.

This is a really fragile solution though because REALTIME can (and often does due to NTP adjustments) go backwards in time and when you do that, everything will break and the UI will refuse to load the trace.

**Comment by wangjiyang** [comment]
In fact I already set primary_trace_clock to REALTIME in order to visualize my "events before device boot". However, it seems still not working. Eg, I have trusted_sequence_id as 1234 for my custom producer, which emits cutom time but have realtime and cutom_time as snapshot, while trusted_sequence_id 1 for default ftrace, which emits boottime and has realtime and boottime as snapshot.
```
CLOCK_REALTIME  100     1200
CLOCK_CUSTOM    60       
CLOCK_BOOTTIME            20
```
I expect this should visualize sequence 1234 much before sequence 1, because its realtime is 1100 earlier than sequence 1. However, it shows very far after sequence 1.

**Comment by LalitMaganti** [comment]
I think it would really help if you could provided a minimal trace with the events which would show the problem so I could reason about them

I could be convinced that there is some bug here but this stuff is really complicated and without a trace I can play around with and query with trace processor, it's hard for me to understand the expected/actual behaviour.

**Comment by wangjiyang** [comment]
Sure. Will provide you a minimal trace tomorrow. Meanwhile, could you point out the source code which handles clock sync?

**Comment by LalitMaganti** [comment]
> Meanwhile, could you point out the source code which handles clock sync?

https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/importers/common/clock_tracker.cc;l=17?q=clock_tracker&sq=

All in this one class :)

**Comment by wangjiyang** [comment]
Hi @LalitMaganti ，
I  attached one perfetto trace, with my customized statsd atoms with clock id 65. Also some ftrace packets with realtime after my custom statsd track. You can see these statsd atoms shows in right side of perfetto ui and very far away after ftrace tracks.

![image](https://github.com/user-attachments/assets/67cf5df5-4df3-42ef-bd6e-d25dadc3bce6)


[trace_with_custom_clock.trace.zip](https://github.com/user-attachments/files/16884251/trace_with_custom_clock.trace.zip)

**Comment by wangjiyang** [comment]
ftrace events is here.

![image](https://github.com/user-attachments/assets/3549cddd-eea1-4c8c-9e22-cfa5a0bd0105)

**Comment by wangjiyang** [comment]
![image](https://github.com/user-attachments/assets/074ac251-bcc3-49ae-b0fd-068e2fdcf1f8)
![image](https://github.com/user-attachments/assets/8d96a716-0668-445f-b650-5e51dd2e5e51)

**Comment by LalitMaganti** [comment]
Wait: your last screenshot shows that your primary trace clock is still boottime? As I said earlier, you need to use realtime as your primary clock (and hope there are not NTP adjustments) otherwise nothing will work as you will have negative timestamps.

**Comment by wangjiyang** [comment]
You mean all primary clock should be set to REALTIME?

**Comment by wangjiyang** [comment]
What's the expected behavior if primary clock is different for different packet swq?

**Comment by LalitMaganti** [comment]
The primary clock is a property of the trace config: *not* of individual packet sequences. The config option (see my link above) changes how trace processor converts timestamps globally.

**Comment by wangjiyang** [comment]
> The primary clock is a property of the trace config: _not_ of individual packet sequences. The config option (see my link above) changes how trace processor converts timestamps globally.

That may be the problem. This trace file is not generated by `traced`. In fact part of it is generated by `trace`, while another part is generated by other data source. I merged both by a python script and expect it to be visualized by perfetto UI. In this case, what's your suggetion in order to merge two or more traces together and take advantage of perfetto ui to visualize all of them as a whole trace, especially they may use different clock domain?

In fact i manually change `primary_trace_clock` inside clocksnapshot and tries the modified version of combined trace in perfetto and nothing changed.

**Comment by wangjiyang** [comment]
sorry fixed typo..

**Comment by primiano** [comment]
I think your problem is that if your primary clock is boottime, then you cannot represent events BEFORE boot because they would require negative TS which are not supported.

Since you are writing the proto manually, I think the most practical solution is the following:
- Use REALTIME clock (or even another custom  clock, doesn't matter) the all the ftrace events, so ns from epoch.
- Emit a clock snapshot and set `ClockSNapshot.primary_trace_clock` in clock = REALTIME
- Use your custom clock for the other events
- Emit a custom snapshot at the beginning that aligns the two clocks once

All the UI uses the "trace clock" and use a consistent unit for them.
The trace clock is by default BOOTTIME but can be overridden using the clock snapshot and setting primary_trace_clock.
You can set the both per-packet (setting TracePacket.timestamp_clock_id) but you can also set a default per-sequence clock by setting `TracePacket.trace_packet_defaults.timestamp_clock_id`. That will become a default-override for all packets in the sequence

**Comment by wangjiyang** [comment]
> * Use REALTIME clock (or even another custom clock, doesn't matter) the all the ftrace events, so ns from epoch.

What I am confused is `primary_trace_clock `'s semantics. Take ftrace event bundles for example. if it already has a clock_snapshot attached, and primary clock set as REALTIME, although it's internal clock_id is default emit `bootime`, why I still need to to convert these `boottime` timestamp into epoch time? I mean trace importer already has this information and can convert it automatically.

![image](https://github.com/user-attachments/assets/c4a946a9-a1ec-4423-9bc0-046aabda2e28)
![image](https://github.com/user-attachments/assets/7eb7eb1b-7178-4aef-89ec-10dcfa30ea1e)

**Comment by LalitMaganti** [comment]
> What I am confused is primary_trace_clock 's semantics.

The semantic is: trace processor looks at the *first* primary_trace_clock in the trace and converts all events to that clock. Any `primary_trace_clock` after that is totally ignored. You can see this logic at https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/trace_processor/importers/common/clock_tracker.h;l=215

So probably you still have BOOTIME as the first `primary_trace_clock` in the trace and that will cause all events to be converted to that clock domain.

> Take ftrace event bundles for example. if it already has a clock_snapshot attached, and primary clock set as REALTIME, although it's internal clock_id is default emit bootime, why I still need to to convert these boottime timestamp into epoch time? I mean trace importer already has this information and can convert it automatically.

If the primary clock is being set correctly, you don't need to do this, trace processor will do the conversion for you.

**Comment by wangjiyang** [comment]
> If the primary clock is being set correctly, you don't need to do this, trace processor will do the conversion for you.

It seems not work as described. Try this perfetto trace I attached.

[primary_clock_set_as_realtime.trace.zip](https://github.com/user-attachments/files/16893393/primary_clock_set_as_realtime.trace.zip)

**Comment by LalitMaganti** [comment]
> It seems not work as described. Try this perfetto trace I attached.

You're right, there is a bug here: we are incorrectly assuming the primary_trace_clock will always be == BOOTTIME which is not valid (i.e. in your case for example).

https://r.android.com/3254563 fixes this assumption and correctly converts all ftrace timestamps to REALTIME.

**Comment by wangjiyang** [comment]
Thanks for your great project and professional work.

**Comment by LalitMaganti** [comment]
Just as an FYI, we are adding native support for merging multiple traces together in the coming weeks. This will solve the problem of "I have multiple files and I want to see them all in the same timeline" without the things like the custom python script you have written.

**Comment by wangjiyang** [comment]
That's a great news. very looking forward this feature.

**Comment by wangjiyang** [comment]
@LalitMaganti
Friendly remind this submit is blocked by Perfetto CI asan issues. Could you please address this issue? Thanks.

**Comment by wangjiyang** [comment]
https://android-review.googlesource.com/c/platform/external/perfetto/+/3254563

**Comment by LalitMaganti** [comment]
I am waiting on @primiano to review, the ASAN failure is a flaky test, not related to this CL.

**Comment by wangjiyang** [comment]
> Just as an FYI, we are adding native support for merging multiple traces together in the coming weeks. This will solve the problem of "I have multiple files and I want to see them all in the same timeline" without the things like the custom python script you have written.

Hi @LalitMaganti , is there anywhere I can check the status of this merging feature? So i can get rid of merging stuff from my local script.

thanks

**Comment by LalitMaganti** [comment]
The feature will be announced on GitHub releases and on our mailing list in the changelog when available. It's still not ready for prime time yet, I've had to put it on pause in favor of some other higher priority work.
