### ISSUE TITLE
Default trace configuration when startup new page

### ISSUE THREAD

**Issue by PlasticUncle** [google/perfetto#88]
When startup a new perffeto page, my trace configuration will be clear.
I want to save my trace configuration so I don't have to  reconfigure it every time I startup new perffeto page.

**Comment by chromy** [comment]
Hey @PlasticUncle :)

This feature was partially implemented last year. It's currently behind a feature flag. You can enable it by:
- Navigating to ui.perfetto.dev
- Opening the dev console. (In Chrome: the three dot menu > 'More tools' > 'Developer Tools', see [docs](https://developers.google.com/web/tools/chrome-devtools/open))
- Running `localStorage.setItem('showConfigs', true);`
- Refreshing the page

This will enable the 'Saved Configs' tab in the config page:

<img width="1640" alt="Screenshot 2021-01-05 at 15 52 27" src="https://user-images.githubusercontent.com/351085/103667580-068f8d00-4f6e-11eb-8ef6-43b511832525.png">

There are some issues with this feature which is why it hasn't been fully enabled.

Cheers,
Hector

**Comment by LalitMaganti** [comment]
We now supporting saving configs so closing.
