### ISSUE TITLE
[Heapprofd client] Reconnect when sockets are disconnected 

### ISSUE THREAD

**Issue by dodola** [google/perfetto#90]
When using heapprofd, I found that the sockets would occasionally get disconnected and would not reconnect, resulting in data loss

![image](https://user-images.githubusercontent.com/1026848/105147065-9d964080-5b3b-11eb-8dcc-4645f8001b4d.png)

**Comment by primiano** [comment]
@fmayer

**Comment by fmayer** [comment]
Hi! Thanks for getting in touch.

This is not generally an error: this just means that the service that is responsible for the profiling disconnected. This can mean the service either disconnected voluntarily, because the profile ended; or alternatively, that it crashed. The log message here is confusing, which we have addressed in newer releases; we now distinguish between those two cases in the log.

Could you share:

* Your build fingerprint (run `adb shell getprop ro.build.fingerprint`)
* How you start the profile
* Some more context around the log line you showed
