### ISSUE TITLE
[Feature Request] Please add VSync markers to Perfetto visualization

### ISSUE THREAD

**Issue by sushraja-msft** [google/perfetto#903]
One thing missing from the old chrome://tracing UI in Perfetto is the ability to visualize VSync boundaries. Seeing VSync boundaries are important for identifying frames that missed the deadline. VSync markers also help orient the user within a trace.

If there is a way to build an extension to solve this gap, that would work as well.

**Comment by LalitMaganti** [comment]
vsync boundaries have not been relevant on Android for >5 years ago and any use of them (including in the legacy Chrome viewer) is giving you a misleading view of the how frames are being rendered.

Frame timeline (https://perfetto.dev/docs/data-sources/frametimeline) is the modern replacement and is used by any Android team who wants to investigate jank these days (surfaceflinger, system_server, SystemUI etc). This also applies just as well to app developers wanting to root-cause jank as well.

**Comment by sushraja-msft** [comment]
Lalit is Perfetto not recommended for chromium perf analysis on platforms other than android? 
On windows, for analysis of Chromium workloads like motionmark the workflow is to analyze what happened between vsync boundaries. Without the Vsync marks this is challenging.

Can you elaborate more on why vsync boundaries are irrelevant on Android - is this because of dynamic frame rate?

**Comment by LalitMaganti** [comment]
> Lalit is Perfetto not recommended for chromium perf analysis on platforms other than android?

To my understanding of the old Chrome UI, the only truly supported use of vsync was on Android. If it's applicable on other platforms I'm not familiar with that but from what I've spoken with the team that does jank analysis on Chrome, they have built a lot of Perfetto based tooling (e.g.https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/ui/src/core_plugins/chrome_scroll_jank/;l=1?q=f:scroll%20f:jank%20f:plugin&sq=) which is far more state of the art than simple vsync based jank analysis.

I've asked Alex (the author of a lot of the scroll jank work) to comment on this issue as well.

> for visibility - I am following up from his BlinkOn 19 talk.

Yeah that was 5 years ago, a lot has changed in that time in Chromium and in Android :) Using talks from that long ago as reference is going to lead you to techniques which are not used on modern day performance analysis in either Chrome or on Android. To be clear both the Chrome and Android performance teams use Perfetto for ~pretty much everything, certainly they are not switching back to legacy UI for something as mundane as jank analysis.

> Can you elaborate more on why vsync boundaries are irrelevant on Android - is this because of dynamic frame rate?

Dynamic frame rate is certainly part of it but in general it also comes down to not all vsyncs being equally important.

Frame timeline on Android for example makes extensive use of this fact: just because you missed a vsync boundary does not mean you caused jank and just because you make a vsync boundary does not mean you did *not* cause jank.

Moreover, not all frames are equal either: even if a frame is missed in some situations (e.g. in a buffer stuffed state), it does not actually cause user visible jank so optimizing for it is meaningless.

**Comment by LalitMaganti** [comment]
Alex summarised it quite succicntly in a message:

> Vsyncs alone are not enough to reason about the pipeline, but might be helpful to orient yourself.

So I definitely think when you say "Seeing VSync boundaries are important for identifying frames that missed the deadline." that's just not true in modern Android/Chrome but maybe "VSync markers also help orient the user within a trace." is true. But OTOH that makes this quite a low priority (nice to have) feature: patches welcome but it's pretty unlikely we will get to it on our side

**Comment by altimin** [comment]
BlinkOn 19 is happening this week and Eric's talk happened earlier today, so this information is quite recent :).

In general, our needs in these areas have been covered by the debug tracks — when we needed to look at vsync intervals, then a simple query (`select ts, lead(ts) over (order by ts) - ts as dur from vsyncs`) plus generating a debug track from them has been sufficient.

Note that most of our analysis has been mostly focused on looking at the timelines of the frame production, with vsync periods being required only occasionally, so we haven't put in place any supporting for that.

If this is a frequent use case for you, I'd recommend just adding a plugin with a command adding a track with the necessary intervals.

Theoretically we could discuss a feature to add vertical highlight to specific regions in the timeline (to match the UX of the chrome://tracing viewer), but I'd say it's a very incremental improvement over the aforementioned things.

**Comment by betasheet** [comment]
I think there's some value in the vertical shading the old UI provided, but as I understand it, adding support for this in the UI requires adding support for this in a generic way and exposing features to control this shading to Perfetto plugins via the plugin API layer. This may not be the easiest project for an external contributor.

Given complexity and the value add over a separate debug track is maybe more limited, so prioritization of this by the Perfetto/Chrome teams isn't easy at the moment :-/

For example, this is what a debug track for this could look like

![Image](https://github.com/user-attachments/assets/5c56a917-6924-4e75-bbcb-5d866e2a45fb)

Query for this:

```
select ts, dur, name from (
  select
    ts,
    lead(ts) over (order by ts) - ts as dur,
    case
      when (row_number() over (order by ts)) % 2 = 0
      then "Vsync A"
      else "Vsync B"
      end as name
  from slice
  where name like '%vsync%'
)
```
