### ISSUE TITLE
about traced_buf_patches_failed data loss

### ISSUE THREAD

**Issue by ChunelFeng** [google/perfetto#909]
i want to make sure the unit for the value of traced_buf_patches_failed.

is it means: center buffer get from share memory in apps, succuess 5337654 times, failed 3 times,

and we do not know  detail bytes size of the loss data?

![Image](https://github.com/user-attachments/assets/67190adc-3d46-4d9d-b590-0c187d804988)

![Image](https://github.com/user-attachments/assets/80037807-3417-4407-b812-4e5257b3c169)

![Image](https://github.com/user-attachments/assets/2002a36d-4316-4fc0-b594-425348c9beeb)

**Comment by LalitMaganti** [comment]
Yeah unfortunately for this data loss type, it's very hard to know how much data was lost exactly. Basically when we were trying to backfill some information retroactively in the buffer, we were unable to do so. Likely it will be on the order of a 100-100 bytes though.

**Comment by ChunelFeng** [comment]
ok, thank you, we do not very care about the detail byte size. 

but i really try larger the center buffer, still loss few data.
is this method works? or any other skill?

**Comment by LalitMaganti** [comment]
If your buffers are large and you are still seeing this, it might be caused by some producer being slow to stop [1]. In which case, this issue is harmless and can be safely ignored.

[1] https://cs.android.com/android/platform/superproject/main/+/main:external/perfetto/src/tracing/service/tracing_service_impl.cc;l=3256?q=external%2Fperfetto%2Fsrc%2Ftracing%2Fservice%2Ftracing_service_impl.cc
