### ISSUE TITLE
crashed  in  traced_probes::GetNewChunk::kAssertAtNStalls value.

### ISSUE THREAD

**Issue by ChunelFeng** [google/perfetto#927]
hi, i fix sdk code in this issue, and perfetto-sdk works well: https://github.com/google/perfetto/issues/899

a new crash happen in traced_probes,  it happens once in about 12 hours.

i will try set kAssertAtNStalls=2000 later.

and just want to know, where can i find log info written by PERFETTO_FATAL or PERFETTO_LOG in my device?

```cpp

      PERFETTO_FATAL(
          "Shared memory buffer max stall count exceeded; possible deadlock");

```

![Image](https://github.com/user-attachments/assets/d770e484-40cd-45ee-9434-e0426c959388)

**Comment by LalitMaganti** [comment]
> and just want to know, where can i find log info written by PERFETTO_FATAL or PERFETTO_LOG in my device?

It can be found in `adb logcat` or on the stderr of the process using the SDK.

The crash indicates that your process is not being scheduled enough to be able to keep up with the tracing bandwidth. Again this crash should be fixed on modern versions of the SDK by switching the tracing policy to drop data instead of crashing.
