### ISSUE TITLE
Overlapping captions

### ISSUE THREAD

**Issue by ibobak** [google/perfetto#928]
There are overlapping captions: it is hard to read the trace. Collected by PyTorchProfiler, the trace is attached below.
Reproduced both in Chrome and Firefox.

![Image](https://github.com/user-attachments/assets/975fff0e-97ed-4535-954f-d7abe1335071)

[jedi_45095.1730987847467009708.pt.trace.zip](https://github.com/user-attachments/files/17663724/jedi_45095.1730987847467009708.pt.trace.zip)

**Comment by LalitMaganti** [comment]
Looked into this. This is actually a bug in the trace file itself not in the viewer. Please find attached a minimal repro which shows the problem:
[jedi_45095.1730987847467009708.pt.trace.json](https://github.com/user-attachments/files/17664517/jedi_45095.1730987847467009708.pt.trace.json)

The problem here is that there are "X" events where the child slice (Ev Idx 66691) has a end time which is after its its parent slice (Ev Idx 5086). This is forbidden according to the [JSON tracing specification](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview?tab=t.0#heading=h.yr4qxyxotyw):

> While duration events allow you to trace the function flow, they must be nested. It is not possible to have non-nested duration events for a given thread. If you need to have durations that do not nest property you should use Async events instead.

As suggested by the spec, you should use async events if you need non-nestable events on a single track. Please also see https://github.com/google/perfetto/issues/503 for a very similar problem.

Closing as there is no issue on the Perfetto side.

**Comment by ibobak** [comment]
This is actually the PyTorch trace, not mine.  But thanks for the answer.
