### ISSUE TITLE
crash at function : WriteChunkRecord()

### ISSUE THREAD

**Issue by ChunelFeng** [google/perfetto#929]
crash at WriteChunkRecord() function. it is very hard to happen another time,

i will use debug version to rerun traced process.

![Image](https://github.com/user-attachments/assets/84c45e61-3b81-4b10-bd66-595972e1c47c)

i see newest version change this, i will try:

![Image](https://github.com/user-attachments/assets/2ff03a4d-4f4a-4a3b-a757-70d15c426e08)

**Comment by LalitMaganti** [comment]
> i will use debug version to rerun traced process.

This is likely a race condition so it's very possible that this will not repro on debug builds. No harm in trying I guess beyond taking time.

> i see newest version change this, i will try:

Unless you update your SDK version, you will keep hitting bugs like this which we've almost certainly fixed since. Chrome has spent the last 3 years slowly integrating Perfetto fully and have discovered many many subtle concurrency issues and subtle bugs over that time. Updating the latest SDK is the only way of not spending all your time rediscovering issues which have long been fixed.

**Comment by ChunelFeng** [comment]
yes, i think we need to update our sdk to newset version, and always follow perfetto release.

but not now, about the end at Dec of this year.
