### ISSUE TITLE
How does Python recognize BUILTIN_CLOCK_MONOTONIC?

### ISSUE THREAD

**Issue by ye3084** [google/perfetto#931]
hello, I can query the data using the Perfetto UI when I include the following configuration in the .pbtx file, but it doesn't work in Python. Are there any specific settings I need to enable for Python to work properly?
```
builtin_data_sources: {
  primary_trace_clock: BUILTIN_CLOCK_MONOTONIC
}
```
```python
from perfetto.trace_processor import TraceProcessor, TraceProcessorConfig
trace_path = r'./trace.perfetto-trace'
tp = TraceProcessor(trace=trace_path,
                    config=TraceProcessorConfig(ingest_ftrace_in_raw=True))
query= """select * from slice"""
qr_it = tp.query(query)
qr_df = qr_it.as_pandas_dataframe()
print(qr_df)
```
output:
```
Empty DataFrame
Columns: [id, type, ts, dur, track_id, category, name, depth, stack_id, parent_stack_id, parent_id, arg_set_id, thread_ts, thread_dur, thread_instruction_count, thread_instruction_delta, cat, slice_id]
Index: []
```
perfetto ui:
![Image](https://github.com/user-attachments/assets/9e9e99f8-1458-44aa-aab2-bc58821a5db1)

**Comment by LalitMaganti** [comment]
The Python API has no special behaviour around primary_trace_clock. Are you sure that you're passing the same file to the Python API and the UI?

To debug any more from our side, we'd need access to the trace file.

**Comment by ye3084** [comment]
> The Python API has no special behaviour around primary_trace_clock. Are you sure that you're passing the same file to the Python API and the UI?
> 
> To debug any more from our side, we'd need access to the trace file.

I confirm that I passed the same file, but this seems to be a non-reproducible error. I conducted multiple traces recently, and the new trace files are all working fine; only that one trace file has issues. Since it’s over 100MB, I have sent it to your email.

**Comment by LalitMaganti** [comment]
> Since it’s 110MB, I have sent it to your email.

I have not received any email. Email address is lalitm@google.com

**Comment by ye3084** [comment]
> I have not received any email. Email address is [lalitm@google.com](mailto:lalitm@google.com)

Thank you for the clarification. I initially sent it to me@lalitm.com, but have now forwarded it to lalitm@google.com.

**Comment by LalitMaganti** [comment]
I just looked at the trace: on Perfetto UI Autopush, `select * from slice` actually returns zero rows, the same as on the Python API. I think this is all caused by aosp/3254563, a fix which is not in the stable Perfetto UI but is in the Python API. If you switch to canary/autopush, you should see consistent behaviour between both.

Taking a step back also, from the Perfetto side, we strongly discourage setting `primary_trace_clock` for Android system traces: it's a config we absolutely do *not* test with and it's really designed more for people collecting traces on Linux/Chrome not on Android. Using monotonic erases important things on Android like suspend periods which are critical to analysing Android traces.
