### ISSUE TITLE
PID overflows to 0 when displayed on the track name

### ISSUE THREAD

**Issue by mkyybx** [google/perfetto#935]
Hi Perfetto maintainers,

    I recently found if I put `"pid":7168000000` to a complete event ("ph":"X") in a json trace file, then Perfetto will display this event to "Process 0". I guess this is because 7168000000 overflows uint32. Could you please solve this problem may be by displaying the PID as string?

    Thank you,

**Comment by LalitMaganti** [comment]
Sorry we are not going to change the pid to a string: pids are integers for performance reasons as people often join on pids in Perfetto and we need those joins to be fast. Moreover, making pids strings would pollute the string pool in trace processor making all strings slower for everyone.

Not supporting obscure non-Chrome related features of chrome://tracing JSON format falls under our standard practice for how we handle JSON traces: https://perfetto.dev/docs/faq#why-does-perfetto-not-support-lt-some-obscure-json-format-feature-gt-

**Comment by LalitMaganti** [comment]
If you are not emitting data for threads/processes, you might instead try emitting our native protobuf based format instead of JSON which supports both non-process/thread based nesting, multiple levels of nesting and the use of uint64 uuids which allow full use of the uint64 space for track ids: https://perfetto.dev/docs/reference/synthetic-track-event#custom-scoped-slices

**Comment by mkyybx** [comment]
Thanks @LalitMaganti !
