### ISSUE TITLE
tool traceconv and trace_processor can not find GLIBC_2.33 and GLIBC_2.34

### ISSUE THREAD

**Issue by lbknxy** [google/perfetto#937]
I want use  **traceconv** and **trace_processor**  tool these days, But get errors,  please help me fix this:  

```
/home/xxx/.local/share/perfetto/prebuilts/trace_processor_shell: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/xxx/.local/share/perfetto/prebuilts/trace_processor_shell)
/home/xxx/.local/share/perfetto/prebuilts/trace_processor_shell: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/xxx/.local/share/perfetto/prebuilts/trace_processor_shell)

```

my pc: 
```
uname -a
Linux xxxpc 5.15.0-124-generic #134~20.04.1-Ubuntu SMP Tue Oct 1 15:27:33 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
and libc versions:

```
strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_2
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
GLIBC_2.29
GLIBC_2.30

```

**Comment by LalitMaganti** [comment]
Unfortunately lyour version of Linux is too old to run the prebuilts we provide. glibc 2.33 was released in 2021 (https://sourceware.org/pipermail/libc-alpha/2021-February/122207.html) so your Linux version has some version before this.

We don't really have the resources to release prebuilts to support older versions of Linux due to the centralised way releases are generated. 

To fix this issue in your side, you would need to compile trace processor from sources. Please see https://perfetto.dev/docs/contributing/getting-started#quickstart for how to do this.
