### ISSUE TITLE
perfetto UI can see streaming data directly from linux target?

### ISSUE THREAD

**Issue by deco-dev** [google/perfetto#945]
Hello.

Environment
Host: Windows amd64(Chrome)
Target: Linux arm64(Ubuntu)
Interface: USB host - device or USB RNDIS.

I want to see profiling data to realtime on perfetto UI. But perfetto UI only supports ADB device.
But my target board is operating Linux arm64(Ununtu). So I can not use adbd.
I tried to this.
In host PC I runs trace_processor_shell -D. and enter perfetto UI.
In target board I runs traced, traced_probes and perfetto -txt -c config.json -o -.
But the trace data just is printed in STDOUT.

Please help me.

**Comment by LalitMaganti** [comment]
There is no "easy & outof the box" support for streaming data over the network/USB from non-Android devices with Perfetto.  If you are willing to get your hands dirty, you might want to checkout traced_relay [1] which is designed for forwarding tracing data across VMs but hypothetically should also be able to forward tracing data over the network across machines. However, note that this is completely untested and we **cannot** provide support for this. You are on your own to figure out this stuff if you go this route.

Also just want to clarify that when collecting traces on Android, the data on the UI is not displayed "relatime" like you seem to suggest. it's just streamed to the host where it's stored in a file/in memory and then when tracing is completed the file is parsed as a whole and then opened.

> In host PC I runs trace_processor_shell -D. and enter perfetto UI.

No idea why running trace_processor_shell here is mentioned, it's not relevant at all really.

> But the trace data just is printed in STDOUT.

Which makes sense because you have specified `-o -` which means "write the trace to the command line".

[1] https://github.com/google/perfetto/blob/2cb2b19bcf55f1923ad78a64b692d397a322c7ae/src/traced_relay/relay_service_main.cc#L31
