### ISSUE TITLE
Increase the monitoring of the memory directly allocated by mmap and mremap.

### ISSUE THREAD

**Issue by huangzeyi2023** [google/perfetto#961]
Part of the memory is directly allocated by mmap and mremap instead of being allocated by functions like libc malloc. There is also a possibility of memory leakage for this part of the memory. Therefore, it is necessary to increase the monitoring of the memory directly allocated by mmap and mremap in heapprofd.

**Comment by huangzeyi2023** [comment]
@LalitMaganti This patch is designed to solve the above problem. Please help review the code. https://android-review.googlesource.com/q/topic:%22heapprofd_mmap%22

**Comment by LalitMaganti** [comment]
We actually noticed your patch already on our CI and discussed it internally. We think it's not suitable to land because this is quite invasive change and there are better ways to solve the same problem. 

Specifically, we think that syscall tracing of mmap/munmap calls is a far better way to solve this problem. This is because mmap/munmap are not frequent calls so there is no reason to implement them as a profiling system: they don't need sampling at all, we can just capture all of them. 

Also beyond the better solution there is no chance the bionic change will be accepted by the bionic maintainers. It's an invasive change and they will just say to do it at the syscall level as described above.

**Comment by huangzeyi2023** [comment]
@LalitMaganti Thank you for your reply.
Is there a plan to put the solution of "syscall tracing of mmap/munmap calls" into production?

**Comment by LalitMaganti** [comment]
Not sure what you mean by "in production". Syscall tracing has been available for years and we added support for filtering to specific syscalls earlier this year.

**Comment by huangzeyi2023** [comment]
What I mean is whether there is a plan to integrate the solution of using "syscall tracing of mmap/munmap calls" to count memory into the Android heapprofd module. In this way, when the heapprofd function is enabled, the memory allocation situation of this part can be monitored.

**Comment by huangzeyi2023** [comment]
Okay, I got it. Is it necessary for me to provide a new patch according to the solution of "syscall tracing of mmap/munmap calls"?

**Comment by LalitMaganti** [comment]
I don't understand. There is no patch required here on the device side. All you need is to enable syscall tracing in your config. That's it.

**Comment by LalitMaganti** [comment]
Closing this out as I think we've solved the root-cause of the question.
