### ISSUE TITLE
[Perfetto SDK] Slice is not end

### ISSUE THREAD

**Issue by Kyson** [google/perfetto#97]
Hi perfetto team,

I am using perfetto sdk (version 12.1) 

I got a problem that some slice show "is not end" when i open trace file in perfetto.dev website, as following

![image](https://user-images.githubusercontent.com/3901140/108486058-9b5d0880-72d8-11eb-8679-20b3acaa864c.png)

But i am sure i called 'TRACE_EVENT_BEGIN' and 'TRACE_EVENT_END' in pairs, and it is not always wrong.

### Initialize config then start trace

```cpp
  perfetto::TraceConfig cfg;
            auto bufferConfig = cfg.add_buffers();
            bufferConfig->set_size_kb(1024 * 128);
            bufferConfig->set_fill_policy(perfetto::protos::gen::TraceConfig_BufferConfig_FillPolicy_DISCARD);

            auto dataSource = cfg.add_data_sources();
            auto *ds_cfg = dataSource->mutable_config();
            ds_cfg->set_name("track_event");
            ds_cfg->set_track_event_config_raw(track_event_cfg.SerializeAsString());

            g_tracing_session->Setup(cfg, -1);
            g_tracing_session->StartBlocking();
```

### Logcat

![image](https://user-images.githubusercontent.com/3901140/108484905-4f5d9400-72d7-11eb-9e0d-f589568dc211.png)

**Comment by primiano** [comment]
Today the Perfetto Tracing client library has a subtlety:
Unless the embedder issues an explicit flush OnStop(), the last packet for each TraceWriter (i.e. of each thread) is lost. This can lead to a bunch of "unfinished events" even if the embedder code did emit the ends on time.
Today the only way to avoid this is to invoke Flush explicitly [1]. It's not that simple though, because the embedder needs to do that on each thread that emitted events in the past. This means that somehow the embedder needs to have some sort of looper and be able to PostTask to its various threads (which then opens other complexities w.r.t. needing to join the flushes and ack the stop closure only after all of them have been done).

## Why it happens
The reason why this works today is the following: when the service scrapes trace packets from the Shared Memory Buffer (SMB), it looks at the "count" field to determine how many packets have been written. Because the count is incremented with a store-release *before* starting a new packet, we can never tell if the last packet in each sequence's chunk has been fully written or is still being written.
Today the service is conservative and always assumes the last packet (for each TraceWriter, i.e. for each thread) is being written and ignores it.
We can't just not-ignore it because doing so will have other bad side-effects when dealing with flushes (when that packet might be seen twice)

If you care about the last event, today the best workaround is to make sure that, on each thread where you write events, you call, on every thread that has emitted a TRACE_EVENT, this:
```
perfetto::TrackEvent::Flush()
```

**Comment by primiano** [comment]
Thanks for the accurate report btw @Kyson , I completely understand that that behavior is surprising.
We had some internal discussion, we should change the way we do the atomic packet increment (At the end of a packet), but doing so is non-trivial a we won't get there too soon.

**Comment by Kyson** [comment]
@primiano Thx for your patient answer.

I think it is not reasonable that i must call `perfetto::TrackEvent::Flush()` on each thread because i can not insert code in every thread.

So make all sequence's chunk be flush to  consumers when i call `perfetto::TrackEvent::Flush()` on any one thread, It would be nice if it was done this way :-)

**Comment by primiano** [comment]
Unfortunately there is no way we can force producers to call Flush on their thread, because we cannot "forcefully execute code" on arbitrary threads.

anyways, this is really just a problem for tests. In production scenarios, you can't expects all events to be balanced because tracing starts and stop and arbitrary points, possibly in the middle of events.

The right fix for test scenarios is changing the order we do the atomics increment in the SMB. but that is a very complex change, especially to do in a backwards compatible way.
Given that the impact of doing so is limited (i.e. this is not a big problem in my view), we will not fix that for a long time because there are more important things to fix.

Until then, if you care about getting visibility of all events in test scenarios, you'll have to call Flush() manually.

**Comment by Kyson** [comment]
I am using perfetto SDK to trace app's all tasks, then compute these tasks execute time by sql trace processor, currently in test scenario and will be apply to production in the future.

But if the last one event can not mark as end, i can not compute every thread task accurately, and i think 'accurate' is important for perfetto.

For now Systrace is the only solution to me but it can not be apply in production scenario.

Hope reconsider to resolve this please...

**Comment by primiano** [comment]
as I said:
1. Yes, you are right, it's a bug / unexpected behavior.
2. No, it's not important enough to be solved soon, there are other things that need to be solved first.

**Comment by elftech** [comment]
It seems that this problem has been fixed in later version.

**Comment by lurker0** [comment]
Same issue is stilled observed in ver 31.0 (released in 2022-11-10 ). Could someone check if it is fixed in latest version (like v48)?
