### ISSUE TITLE
Invalid Hierarchy With 'Complete' & 'Begin'-'End' Events

### ISSUE THREAD

**Issue by DwarfiusDan** [google/perfetto#970]
It seems that mixing both Complete('X') and 'B'-'E' event pairs can lead to invalid layout. It also generates an invalid "data_loss (analysis): misplaced_end_event" error.

**Affects versions:** Stable(v48.1-54a19ff81) and Canary(v48.1-94595b08a).

**Mini repro case**:
`[{"name":"Complete0","cat":"P","ph":"X","ts":0,"dur":10,"pid":0,"tid":1},{"name":"Begin0","cat":"P","ph":"B","ts":0,"pid":0,"tid":1},{"ph":"E","ts":10,"pid":0,"tid":1},{"name":"Complete1","cat":"P","ph":"X","ts":10,"dur":10,"pid":0,"tid":1},{"name":"Begin1","cat":"P","ph":"B","ts":10,"pid":0,"tid":1},{"ph":"E","ts":15,"pid":0,"tid":1}]`

Perfetto fails to handle this case, while Catapult (chrome://tracing) visualizes it correctly

Workaround: replace all Complete events with Begin-End events at appropriate locations

**Comment by LalitMaganti** [comment]
https://r.android.com/3426843 should fix this issue.

Also I have a small aside rant; this is not directed at you, just any future readers who might also report bugs in the JSON format.

I'm really tired of playing whack-a-mole with the JSON format parsing. There are uncountable number of nuances in parsing the JSON format which the trace format spec is totally silent on. And people say "but the legacy trace viewer parses this trace": yes but the legacy viewer also works a totally different way (i.e. as trees of objects rather than a flat tabular representation). What we do has costs in not being as flexible but also allows us to scale to multi-GB traces which is totally impossible for legacy viewer: it chokes on anything larger than a couple of hundred MB in the JSON format. That's not to mention that proto traces usually have a 10x compression ratio vs JSON and we support multi-GB proto traces.

Supporting bit-for-bit how the JSON format is parsed by the legacy viewer is nigh on impossible: we've tried our best but given the potential surface area for weirdness (especially around identical timestamps), I'm very tired of playing this game.

**Comment by DwarfiusDan** [comment]
No worries, not taking it personally - and sorry for piling on more on this front. I've reported this despite your docs stating that protobuf is the main supported medium because this case should be unambiguous - after all, it's an ordered array which would need to be processed likely the same way as with protobuf stream of ordered events(guessing here). So there's a chance it would've been a generic issue.

> That's not to mention that proto traces usually have a 10x compression ratio vs JSON and we support multi-GB proto traces.

I've been generating array-style json profiles, and due to their super repetitive nature they compress extremely well with gzip (560MB -> 21mb). I've tried compressing own binary format, but it lost to json. I'll be experimenting with ProtoBuff next.

**Comment by LalitMaganti** [comment]
> after all, it's an ordered array which would need to be processed likely the same way as with protobuf stream of ordered events(guessing here). So there's a chance it would've been a generic issue.

You would have been absolutely right, I too would think this case is very simple and should "just work".

*Except* for the fact that we introduced some complicated logic due to another bug reported by another user around handling `X` events with identical timestamps where again legacy trace viewer did some very weird logic and we were asked to emulate that (https://github.com/google/perfetto/issues/878 for context).

The fix for that issue *caused* this very issue. Now I'm expecting the fix to this issue to cause some *other* issue. This is what I meant by "whack-a-mole" in my comment above.
